graph TD
    OF -->        PROGRAM-ID
    CLOSE-FILES -->        DATE-WRITTEN
    SUSPEND -->        SOURCE-COMPUTER
    CALL-ERRMSG -->        OBJECT-COMPUTER
    CLOSE-FILES -->        FILE-CONTROL
    CALL-ERRMSG -->        I-O-CONTROL
    CLOSE-FILES -->        DECLARATIVES
    SUSPEND -->        CHECK-ERROR-TYPE
    CALL-ERRMSG -->        CHECK-IO9
    ALARM -->        OPEN-IT
    CALL-ERRMSG -->        COUNT-IT
    CALL-ERRMSG -->        READ-IT
    CLOSE-FILES -->        WRITE-IT
    ALARM -->        REWRITE-IT
    SQL-ERROR -->        DELETE-IT
    CLOSE-FILES -->        START-IT
    CLOSE-SP1-FILE -->        CLOSE-IT
    CLOSE-LTP1-FILE -->        FORM-IT
    CLOSE-LTI1-FILE -->        SUSPEND
    CLOSE-LP1-FILE -->        ALARM
    CLOSE-LN1-FILE -->        FILE-ERRORS
    CLOSE-LXE1-FILE -->        FILE-ERRORS-TERMINATE
    CLOSE-LXG1-FILE -->        SEND-MESS
    CLOSE-LP1-FILE -->        SQL-IO-VALIDATION
    CLOSE-CD1-FILE -->        CLOSE-FILES
    CLOSE-BW1-FILE -->        END-DECLARE
    CLOSE-GI1-FILE -->        SKIP-EARLY-PAYOFF-TEST
    CLOSE-RC2-FILE -->        TEST-PAYOFF-ALLOWED
    CLOSE-BR-FILE -->        SKIP-PAYOFF-CALC
    CLOSE-GB-FILE -->        END-ROUTINE
    SQL-DISCONNECT -->        INVALID-REVERSAL
    SQL-CONNECT -->        EXIT-VALIDATE-REVERSAL
    GET-GPENV -->        PAYMENT-POSTING-EXIT
    CONVERT-MMDDYY-TO-YYYYMMDD -->        PAYOFF-POSTING-EXIT
    INITIALIZATION -->        POST-PO-EXIT
    READ-BR-FILE -->        POST-Z2-EXIT
    CREATE-LOG -->        POST-REFUNDS-PLUS-PY-AGAIN
    OPEN-CD1-FILE -->        POST-REFUNDS-PLUS-PY-NOW
    READ-CD1-FILE -->        POST-REFUNDS-PLUS-PY-EXIT
    CREATE-LOG -->        OTHER-CHG-POSTING-EXIT
    CREATE-LOG -->        BANKRUPT-POSTING-EXIT
    OPEN-GB-FILE -->        REVERSAL-LP1-FILE
    READ-GB-FILE -->        BYPASS-SERVICE
    CLOSE-GB-FILE -->        REVERSAL-SAVE-SCREEN
    CREATE-LOG -->        CALL-LONPF2-FOR-REVERSAL
    OPEN-LN1-FILE -->        REVERSAL-RTN-EXIT
    OPEN-BW1-FILE -->        END-INIT
    OPEN-RC2-FILE -->        EXIT-INITIALIZE
    READ-RC2-FILE -->        EXIT-SAVE-SCREEN
    CLOSE-RC2-FILE -->        TRY-NEXT-STEP-NO
    CREATE-LOG -->        EXIT-CREATE-SPOOL-DIR
    CONVERT-YYYYMMDD-TO-MMDDYY -->        OPEN-WK-OUTPUT
    LOAD-OPEN-FILE -->        CDV-VERIFY-NEXT
    ACCESS-CALL -->        CDV-VERIFY-EXIT
    CREATE-LOG -->        GET-TIME-EXIT
    OPEN-OP-FILE -->        CV-MMDDYY-TO-MMSDDSYY-EXIT
    CREATE-LOG -->        CV-MMDDYY-TO-MMSDDSY4-EXIT
    CREATE-LOG -->        CV-MMDDYY-TO-MMYY-EXIT
    READ-LN1-FILE -->        CV-MMDDYY-TO-YYMM-EXIT
    CREATE-LOG -->        CV-YYYYMMDD-TO-YYYYMM-EXIT
    CREATE-LOG -->        CV-YYYYMMDD-TO-YYMMDD-EXIT
    VALIDATE-REVERSAL -->        CV-MMDDYY-TO-YYYYMMDD-EXIT
    CREATE-LOG -->        CV-MMYY-TO-MMDDYY-EXIT
    CREATE-LOG -->        CV-YYMMDD-TO-MMDDYY-EXIT
    CREATE-LOG -->        CV-YYYYMM-TO-MMDDYY-EXIT
    CREATE-LOG -->        CV-YYYYMMDD-TO-MMDDYY-EXIT
    CREATE-LOG -->        CV-YYMMDD-TO-YYYYMMDD-EXIT
    IBPC-TEST -->        CV-MMDDYYYY-TO-YYYYMMDD-EXIT
    CREATE-LOG -->        VALIDATE-DF-POLICY-EXIT
    CREATE-LOG -->        DEFPOL-MINIMUM-MONTHS-NEXT
    CREATE-LOG -->        DEFPOL-MINIMUM-MONTHS-BETWEEN-EXIT
    CREATE-LOG -->        SETCTBL-EXIT
    CREATE-LOG -->        IBPC-TEST-EXIT
    CREATE-LOG -->        CHECK-PREV
    CREATE-LOG -->        CHECK-PREV-STATUS-EXIT
    CREATE-LOG -->        SET-PY-RATE-EXIT
    CREATE-LOG -->        LPRATE-EXPIRED-INT-LOOP
    CREATE-LOG -->        VALIDATE-SPR-TABLE
    CREATE-LOG -->        INTEREST-DUE-LOOP
    CREATE-LOG -->        ACCEL-INT-LOOP
    CREATE-LOG -->        INTEREST-DUE-FINAL
    CREATE-LOG -->        INTEREST-DUE-EXIT
    CREATE-LOG -->        INTEREST-DUE-PENALTY-21
    CREATE-LOG -->        NO-PENALTY-21
    CREATE-LOG -->        INTEREST-DUE-PENALTY-MS
    CREATE-LOG -->        NO-PENALTY-MS
    CREATE-LOG -->        INTEREST-DUE-PENALTY-NV
    CREATE-LOG -->        INTEREST-DUE-PENALTY-OH
    GET-SPR -->        NO-PENALTY-OH
    CREATE-LOG -->        INTEREST-DUE-PENALTY-GA
    IBPC-TEST -->        NO-PENALTY-GA
    CREATE-LOG -->        INTEREST-DUE-PENALTY-WI
    CREATE-LOG -->        INTEREST-DUE-PENALTY-NEWS
    CREATE-LOG -->        INTEREST-DUE-PENALTY-NC
    CREATE-LOG -->        INTEREST-DUE-PENALTY-25
    VALIDATE-DF-POLICY -->        NO-PENALTY-25
    CREATE-LOG -->        INTEREST-DUE-PENALTY-EXIT
    CREATE-LOG -->        INDU-GET-ALL-INSPREM-EXIT
    CREATE-LOG -->        LATE-ASSESS-EXIT
    COMPUTE-CONTRACTUAL -->        LCAS-FIND-LAST-GRACE-DAY-EXIT
    COMPUTE-RECENCY -->        PAID-THRU-CALCULATION-EXIT
    CREATE-LOG -->        PAID-THRU-CALC-NORMAL-EXIT
    CREATE-LOG -->        PAID-THRU-CALC-NORMAL-E-EXIT
    CREATE-LOG -->        PAID-THRU-ADDON-NEXT
    CREATE-LOG -->        PAID-THRU-ADDON-SUM-EXIT
    CREATE-LOG -->        LATE-CHARGE-CALC-END
    CREATE-LOG -->        LATE-CHARGE-CALC-NORMAL-END
    CREATE-LOG -->        LATE-CHARGE-CALC-EXIT
    CREATE-LOG -->        LCAP-APP-EXIT
    PAYOFF-LOAN-ROUTINE -->        LCAP-A-C-BEGIN
    VARYING -->        LCAP-A-ACCUM
    CREATE-LOG -->        LCAP-A-C-PMT
    CREATE-LOG -->        LCAP-A-AL-OK-TEST
    CREATE-LOG -->        LCAP-A-C-EXIT
    CREATE-LOG -->        LCAP-B-J-DATE-CHK
    CREATE-LOG -->        LCAP-B-J-PMT
    CREATE-LOG -->        LCAP-B-J-RETRY
    CREATE-LOG -->        LCAP-B-J-EXIT
    IBPC-TEST -->        LCAP-D-BEGIN
    LATE-CHARGE-APPLY -->        LCAP-D-ADVANCE
    CREATE-LOG -->        LCAP-D-NOASSESS
    CREATE-LOG -->        LCAP-D-EXIT
    CREATE-LOG -->        LCAP-E-X-DATE-CHK
    CREATE-LOG -->        LCAP-E-X-PMT
    CREATE-LOG -->        LCAP-E-X-RETRY
    CREATE-LOG -->        LCAP-E-X-EXIT
    READ-GI1-FILE -->        LCAP-F-BEGIN
    CREATE-LOG -->        LCAP-F-ADVANCE
    BANKRUPT-POSTING -->        LCAP-F-NOASSESS
    REVERSAL-POSTING -->        LCAP-F-EXIT
    OTHER-CHG-POSTING -->        LCAP-F-CURRENT-PERIOD-NEWCUR
    PAYOFF-POSTING -->        LCAP-F-CURRENT-PERIOD-EXIT
    PAYMENT-POSTING -->        LCAP-H-BEGIN
    CREATE-LOG -->        LCAP-H-ADVANCE
    CREATE-LOG -->        LCAP-H-NOASSESS
    CLOSE-OP-FILE -->        LCAP-H-EXIT
    REMOVE-WORKFILE -->        LCAP-H-CURRENT-PERIOD-NEWCUR
    CLOSE-OP-FILE -->        LCAP-H-CURRENT-PERIOD-EXIT
    OPEN-LP1-FILE -->        LCAP-I-L-BEGIN
    START-LP1-FILE-NOT-GREATER -->        LCAP-I-L-ADVANCE
    READ-LP1-FILE-PREVIOUS -->        LCAP-I-L-NOASSESS
    CREATE-LOG -->        LCAP-I-L-MATURITY-TEST
    CLOSE-LP1-FILE -->        LCAP-I-L-EXIT
    ACCESS-CALL -->        LCAP-I-L-CURRENT-PERIOD-SETDUE
    OPEN-LOG-FILE-EXTEND -->        LCAP-I-L-CURRENT-PERIOD-NEWCUR
    OPEN-LOG-FILE-OUTPUT -->        LCAP-I-L-CURRENT-PERIOD-EXIT
    GET-TIME -->        LCAP-G-K-BEGIN
    WRITE-LOG-FILE -->        LCAP-G-K-ADVANCE
    CLOSE-LOG-FILE -->        LCAP-G-K-NOASSESS
    SETUP-LP-RECORD -->        LCAP-G-K-EXIT
    SETUP-LONPF-BUFFER -->        LCAP-M-BEGIN
    CREATE-LOG -->        LCAP-M-ADVANCE
    CREATE-LOG -->        LCAP-M-NOASSESS
    CREATE-LOG -->        LCAP-M-EXIT
    CREATE-LOG -->        LCAP-M-CURRENT-PERIOD-SETDUE
    CREATE-LOG -->        LCAP-M-CURRENT-PERIOD-NEWCUR
    POST-PO -->        LCAP-M-CURRENT-PERIOD-EXIT
    POST-PO -->        LCAP-N-DATE-CHK
    CREATE-LOG -->        LCAP-N-PMT
    POST-Z2 -->        LCAP-N-RETRY
    READ-LN1-FILE -->        LCAP-N-EXIT
    CREATE-LOG -->        LCAP-P-BEGIN
    POST-REFUNDS-PLUS-PY -->        LCAP-P-ADVANCE
    CREATE-LOG -->        LCAP-P-NOASSESS
    POST-PO -->        LCAP-P-MATURITY-TEST
    POST-REFUNDS-PLUS-PY -->        LCAP-P-EXIT
    CREATE-LOG -->        LCAP-P-CURRENT-PERIOD-SETDUE
    POST-PO -->        LCAP-P-CURRENT-PERIOD-NEWCUR
    SETUP-LP-RECORD -->        LCAP-P-CURRENT-PERIOD-EXIT
    SETUP-LONPF-BUFFER -->        LCAP-S-BEGIN
    CREATE-LOG -->        LCAP-S-ADVANCE
    CREATE-LOG -->        LCAP-S-NOASSESS
    SETUP-LP-RECORD -->        LCAP-S-EXIT
    SETUP-LONPF-BUFFER -->        LCAP-S-CURRENT-PERIOD-NEWCUR
    CREATE-LOG -->        LCAP-S-CURRENT-PERIOD-EXIT
    CREATE-LOG -->        LCAP-COMPUTE-PAYS
    SETUP-LP-RECORD -->        LCAP-CALC-PDTH-EXIT
    SETUP-LONPF-BUFFER -->        LCAP-PAID-THRU-ADDON-NEXT
    CREATE-LOG -->        LCAP-PAID-THRU-ADDON-SUM-EXIT
    CREATE-LOG -->        ITRM-EXIT
    READ-LN1-FILE -->        REBATE-END-ADJ
    READ-LN1-FILE -->        REBATE-EXIT
    PAYMENT-POSTING -->        REBATE-78-EXIT
    SETUP-LP-RECORD -->        REBATE-ACTUARIAL-2-EXIT
    SETUP-LONPF-BUFFER -->        REBATE-ANTICIPATED-EXIT
    CREATE-LOG -->        REBATE-PRORATA-GA-SWING
    CREATE-LOG -->        REBATE-PRORATA-GA-NO-SWING
    SETUP-LP-RECORD -->        REBATE-PRORATA-ROUTINE
    IBPC-TEST -->        REBATE-PRORATA-EXIT
    PAID-THRU-CALCULATION -->        REBATE-ACTUARIAL-IB-EXIT
    SETUP-LONPF-BUFFER -->        REBATE-INS-ANTICIPATED-EXIT
    CREATE-LOG -->        REBATE-ANTICIPATED-N-EXIT
    VARYING -->        REBATE-ANTICIPATED-O-EXIT
    CLOSE-LP1-FILE -->        REBATE-ACTUARIAL-C-EXIT
    READ-EARNINGS -->        REBATE-ACTUARIAL-D-EXIT
    OPEN-LXG1-FILE -->        REBATE-DEFERMENT-EOKMYZ05-EXIT
    READ-LXG1-FILE -->        REBATE-ACTUARIAL-F-EXIT
    CLOSE-LXG1-FILE -->        REBATE-MA-AH-ANTICIPATED-EXIT
    CDV-VERIFY -->        REBATE-GA-SC-EXIT
    CALC-HOLD-LN-ACCERN -->        REBATE-CA-AH-ANTICIPATED-EXIT
    PAID-THRU-CALCULATION -->        REBATE-CA-ANTICIPATED-EXIT
    OPEN-WK-FILE -->        REBATE-CA-CL-ANTICIPATED-EXIT
    WRITE-WK-FILE -->        REBATE-TABLE-FORMULA-EXIT
    REWRITE-WK-FILE -->        REBATE-NET-POFF-MULL-EXIT
    CLOSE-WK-FILE -->        EXIT-RULE-78THS-MEAN
    CREATE-LOG -->        EXIT-TN-PP-SHORT-RATE
    CLEAR-LP-FILE -->        REBATE-MERC-AH-ANTIC-EXIT
    CLEAR-LXG-FILE -->        REBATE-MULLEN-CL-AH-07-EXIT
    VARYING -->        REBATE-MULLEN-CL-07-EXIT
    SAVE-SCREEN -->        REBATE-MULLEN-AH-07-EXIT
    CREATE-WK-FILE -->        REBATE-SHORT-RATE-0C-EXIT
    CREATE-SPOOL-DIR -->        REBATE-78-DAYS-0D-EXIT
    OPEN-PR-FILE -->        REBATE-ACTUARIAL-0E-EXIT
    CLOSE-PR-FILE -->        REBATE-TRUE-PRORATA-0F-EXIT
    CREATE-SPOOL-DIR -->        RB-SAME-PROP-INT-SC-0G-EXIT
    OPEN-PR-FILE -->        REBATE-MX-CL-ANTICIPATED-EXIT
    CLOSE-PR-FILE -->        REBATE-MERC-DAILY-PRORATA-EXIT
    CREATE-SPOOL-DIR -->        REBATE-REFDATE-EXIT
    OPEN-PR-FILE-EXTEND -->        REBATE-ADJUST-REB-REBATE-FLOOR
    OPEN-PR-FILE -->        REBATE-SPEC-RBREDUC-NV
    CLOSE-PR-FILE -->        REBATE-SPEC-RBREDUC-EXIT
    OPEN-PR-FILE-EXTEND -->        REBATE-RBREDUC-NJ-EXIT
    CREATE-LOG -->        REBATE-RBREDUC-NJ-21-EXIT
    OPEN-BR-FILE -->        REBATE-RBEARLY-VYBA-28-EXIT
    OPEN-GI1-FILE -->        REBATE-CALL-SUBPROG-RETRY
    OPEN-CD1-FILE -->        REBATE-EP2-REBATE-CHG
    OPEN-SP1-FILE -->        REBATE-EP2-REBATE-EXTCHG
    OPEN-WK-FILE -->        REBATE-EP2-EXIT
    WRITE-WK-FILE -->        REBATE-EP27-REBATE-CHG
    REWRITE-WK-FILE -->        REBATE-EP27-EXIT
    CLOSE-WK-FILE -->        REBATE-EARLY-97-EXIT
    CONVERT-YYYYMMDD-TO-MMDDYY -->        REBATE-EARLY-99-EXIT
    DIR-ACCESS-CALL -->        REBATE-EARLY-98-EXIT
    CREATE-LOG -->        REBATE-EP3-EXIT
    ACCESS-CALL -->        REBATE-EP11-EXIT
    MKTEMP-CALL -->        REBATE-EP13-EXIT
    OPEN-IT -->        REBATE-EP14-EXIT
    CLOSE-WK-FILE -->        REBATE-EP17-EXIT
    CLOSE-WK-FILE -->        REBATE-EP18-REBATE-CHG
    A -->        REBATE-EP18-EXIT
    C-DATER-MAIN -->        REBATE-EP19-EXIT
    CONVERT-SYS-NUM-NDTE-DATES-IN -->        REBATE-EP20-EXIT
    C-ELAPSED-TIME -->        REBATE-EP22-EXIT
    C-CALL-NEWDATE -->        REBATE-EP24-EXIT
    C-INCREMENT-PERIODS -->        REBATE-EP54-EXIT
    C-CALL-CJUL -->        REBATE-WI-CPI-EXIT
    C-CALL-JUL -->        REBATE-TX-INTEREST-LOOP
    C-WEEKDAY -->        REBATE-TX-INTEREST-END
    C-DATE-COMPARE -->        REBATE-TX-INTEREST-EXIT
    C-DATE-TEST -->        REBATE-TX-INT-UNITED-LOOP
    CONVERT-SYS-NUM-NDTE-DATES-OUT -->        REBATE-TX-INT-UNITED-END
    DATER-ROUTINE -->        REBATE-TX-INT-UNITED-EXIT
    INCREMENT-UNITPER -->        REBATE-TX-INT-0H-LOOP
    INCREMENT-COMMON -->        REBATE-TX-INT-0H-END
    INCREMENT-COMMON -->        REBATE-TX-INT-0H-EXIT
    INCREMENT-COMMON -->        REBTX-CALC-INT-0H-LOOP
    INCREMENT-COMMON -->        REBTX-CALC-INT-0H-END
    INCREMENT-COMMON -->        REBTX-CALC-INT-0H-EXIT
    DATER-ROUTINE -->        REBATE-TRIST-CPI-0I-EXIT
    DATER-ROUTINE -->        REBATE-MEAN-OF-PRORATA-78-EXIT
    DATER-ROUTINE -->        REBATE-78-NET-1-EXIT
    DATER-ROUTINE -->        REBATE-FIND-INS-RATE-INTERPO
    DATER-ROUTINE -->        REBATE-FIND-INS-TABLE
    DATER-ROUTINE -->        REBATE-FIND-INS-RATE-COMPUTE
    DATER-ROUTINE -->        REBATE-FIND-INS-RATE-EXIT
    TIMALL -->        REBATE-DEDUCT-CHARGE-EXIT
    TIMALL -->        REBATE-RBEARLY-21-EXIT
    TIMALL -->        REBATE-RBEARLY-26-EXIT
    TIMALL -->        REBATE-CHECK-ADDON-TRAILER-NEXT
    TIMALL -->        REBATE-CHECK-ADDON-TRAILER-EXIT
    TIMALL -->        PAYOFF-OTHER-INS
    TIMALL -->        PAYOFF-EXIT
    TIMALL -->        PAYOFF-SERCHG-REBATE-EXIT
    DATER-ROUTINE -->        EXIT-CALIFORNIA-SPECIAL-OPTION
    C-TIMALL -->        PAYOFF-INT-ADDONS-NEXT
    C-TIM-RESULTS -->        END-PAYOFF-INT-ADDONS
    C-TIMALL -->        COMPUTE-RECENCY-EXIT
    C-TIMALL -->        RECENCY-ROUTINE-EXIT
    C-TIMALL -->        COMPUTE-RECENCY-DELINQ-EXIT
    C-TIM360-358 -->        COMPUTE-RECENCY-DELINQ-D-EXIT
    C-TIM360-358 -->        COMPUTE-RECENCY-DELINQ-F-EXIT
    C-TIM361 -->        COMPUTE-CONTRACTUAL-POT30
    C-TIM362 -->        COMPUTE-CONTRACTUAL-POT-CHGOFF
    C-TIM365-367 -->        COMPUTE-CONTRACTUAL-CONTINUE
    C-TIM365-367 -->        COMPUTE-CONTRACTUAL-EXIT
    C-TIM999-998 -->        COMPUTE-CONTR-UNITP-A-D-EXIT
    C-TIM999-998 -->        COMPUTE-CONTRACTUAL-D-EXIT
    C-TIMBEG -->        COMPUTE-CONTRACTUAL-F-EXIT
    C-LEAP-YEAR-TEST -->        UPWK-DEF-CALC-EXIT
    C-LEAP-YEAR-TEST -->        UPWK-CONTR-CALC-EXIT
    C-TIMEND -->        UPWK-LC-CALC-EXIT
    C-TIMBEG -->        UPWK-GET-UPER-INFO-EXIT
    C-LEAP-YEAR-TEST -->        EXIT-UNPACK-PAYMENT-SCHEDULE
    C-LEAP-YEAR-TEST -->        EXIT-UNPACK-LT
    C-LEAP-YEAR-TEST -->        EXIT-MOVE-PAYMENT
    C-TIMEND -->        EXIT-PACK-PAYMENT-SCHEDULE
    C-TIMBEG -->        EXIT-PACK-LT
    C-INCR-MONTHS -->        EXIT-MOVE-TO-LT
    C-LEAP-YEAR-TEST -->        EXIT-ADVANCE-SCHED
    C-CALL-JUL -->        CONTRAL-ELAPSED-PAYPER-EXIT
    C-CALL-JUL -->        APRS-GET-EFFRATE-EXIT
    C-TIMEND -->        APR-REGZ-EXIT
    C-TIMBEG -->        APRZ-APR-GET-ARGS
    C-LEAP-YEAR-TEST -->        APRZ-APR-PROCESS
    C-LEAP-YEAR-TEST -->        APRZ-APR-FIN
    C-TIMEND -->        UPER-CALCULATE-EXIT
    C-TIMBEG -->        UPER-SINGLE-PAYS-EXIT
    C-INCR-MONTHS -->        UPER-MONTHLY-UNIT-PERIODS-EXIT
    C-CALL-JUL -->        UPER-YEARLY-UNIT-PERIODS-EXIT
    C-TIMEND -->        PAST-DUE-DAYS-COMPUTE
    C-CALL-JUL -->        PAST-DUE-DAYS-EXIT
    C-CALL-JUL -->        RBACT-ACTUARIAL-PV
    C-INCR-MONTHS -->        RBACT-ACTUARIAL-EXIT
    C-INCR-HALF-MONTHS -->        FIND-ADDON-SPR-EXIT
    C-INCR-DAYS -->        ACCESS-CALL
    C-INCR-DAYS -->        DIR-ACCESS-CALL
    C-INCR-DAYS -->        MKTEMP-CALL
    C-INCR-MONTHS -->        SYSTEM-CALL
    C-CALL-NEWDATE -->        GETENV-CALL
    C-CALL-JUL -->        REMOVE-WORKFILE
    C-CALL-CJUL -->        GET-SPR
    C-INCR-MONTHS -->        CALC-HOLD-LN-ACCERN
    C-INCR-MONTHS -->        READ-EARNINGS
    C-INCR-MONTHS -->        SQL-CONNECT
    C-CALL-NEWDATE -->        SQL-OPEN-UPDATE-CONNECTION
    C-CALL-JUL -->        SQL-CLOSE-UPDATE-CONNECTION
    C-CALL-JUL -->        SQL-SWAP-UPDATE-CONNECTION
    C-CALL-JUL -->        SQL-CONNECT-ERROR
    C-TIM-RESULTS -->        SQL-CONNECT-MAKE
    C-CALL-JUL -->        SQL-CONNECT-WHENEVER
    C-CALL-CJUL -->        SQL-DISCONNECT
    C-LEAP-YEAR-TEST -->        SQL-DEBUG
    UNTIL -->        SQL-ERROR
    C-LEAP-YEAR-TEST -->        SQL-DATE-DECREMENT
    CONVERT-00MMDDYY-TO-CCYYMMDD -->        SQL-DATE-INCREMENT
    CONVERT-00MMDDYY-TO-CCYYMMDD -->        SQL-GET-DATE
    CONVERT-00MMDDYY-TO-CCYYMMDD -->        SQL-SET-DATE
    CONVERT-CCYYMMDD-TO-00MMDDYY -->        SQL-TEXT-DECREMENT
    CONVERT-CCYYMMDD-TO-00MMDDYY -->        SQL-TEXT-INCREMENT
    CONVERT-CCYYMMDD-TO-00MMDDYY -->        SQL-TEXT-FIND-ASCII
    PAID-THRU-CALCULATION -->        OPEN-LOG-FILE-EXTEND
    INCREMENT-MONTHS -->        OPEN-LOG-FILE-OUTPUT
    TIM360 -->        OPEN-LOG-FILE
    TIM360 -->        WRITE-LOG-FILE
    DEFPOL-MINIMUM-MONTHS-BETWEEN -->        CLOSE-LOG-FILE
    OPEN-LP1-FILE -->        GET-SPA-FIELDS
    START-LP1-FILE-NOT-GREATER -->        SET-SPA-FIELDS
    READ-LP1-FILE-PREVIOUS -->        GET-SPB-FIELDS
    TIM360 -->        SET-SPB-FIELDS
    EXPIRATION-DATE-CALCULATION -->        GET-SPC-FIELDS
    TIM -->        SET-SPC-FIELDS
    TIM -->        GET-LXG-FIELDS
    TIM -->        SET-LXG-FIELDS
    TIM -->        GET-LXE-FIELDS
    TIM -->        SET-LXE-FIELDS
    CHECK-PREV-STATUS -->        GET-LTP-FIELDS
    IBPC-TEST -->        SET-LTP-FIELDS
    LPRATE-JUDGEMENT -->        GET-LTI-FIELDS
    LPRATE-USE-EXPIRED-RATES -->        SET-LTI-FIELDS
    LPRATE-JUDGEMENT -->        GET-LP-FIELDS
    LPRATE-ACCELERATION -->        SET-LP-FIELDS
    LPRATE-ACCELERATION -->        GET-LN-FIELDS
    LPRATE-SET-INTPDTH-DATE -->        SET-LN-FIELDS
    INCREMENT-DAYS -->        GET-CD-FIELDS
    INTEREST-DUE-CALCULATION -->        SET-CD-FIELDS
    LPRATE-SET-INTPDTH-DATE -->        GET-BW-FIELDS
    LPRATE-PREPARE-PMT-2 -->        SET-BW-FIELDS
    LPRATE-PREPARE-PMT-2 -->        GET-GI-FIELDS
    LPRATE-JUDGEMENT -->        SET-GI-FIELDS
    LPRATE-CALC-IT -->        GET-RC-FIELDS
    LPRATE-ACCELERATION -->        SET-RC-FIELDS
    LPRATE-CALC-IT -->        GET-BR-FIELDS
    LPRATE-CALC-IT -->        SET-BR-FIELDS
    LPRATE-CALC-IT -->        GET-GB-FIELDS
    LPRATE-PREPARE-PMT-1 -->        SET-GB-FIELDS
    INTEREST-DUE-CALCULATION -->        LOAD-BR-FILE
    LPRATE-PREPARE-PMT-2 -->        OPEN-BR-FILE
    LPRATE-SET-INTPDTH-DATE -->        COUNT-BR-FILE
    LPRATE-EXPIRED-INT -->        START-BR-FILE
    LPRATE-COMPARE-RATES -->        READ-BR-FILE
    INTEREST-DUE-CALCULATION -->        READ-BR-FILE-NEXT
    LPRATE-SET-INTPDTH-DATE -->        CLOSE-BR-FILE
    LPRATE-JUDGEMENT -->        LOAD-GB-FILE
    LPRATE-CALC-BREAK-DATES -->        OPEN-GB-FILE
    LPRATE-FIND-THRU-DATE -->        START-GB-FILE
    INTEREST-DUE-CALCULATION -->        READ-GB-FILE
    INCREMENT-MONTHS -->        READ-GB-FILE-NEXT
    INCREMENT-DAYS -->        CLOSE-GB-FILE
    TIM -->        LOAD-OPEN-FILE
    TIM -->        LOAD-CLOSE-FILE
    TIMALL -->        LOAD-UPDATE-FILE
    INTEREST-DUE-SPECIAL-OPTIONS -->        SET-ALL-TO-SP1
    SELECT-SPR-TABLE -->        SET-SP1-TO-ALL
    INDU-GET-ALL-INSPREM -->        LOAD-SP1-FILE
    INDU-GET-ALL-INSPREM -->        OPEN-SP1-FILE
    INTEREST-DUE-PENALTY -->        START-SP1-FILE
    INTEREST-DUE-MINIMUM -->        READ-SP1-FILE
    INTEREST-DUE-MAXIMUM -->        READ-SP1-FILE-NEXT
    MATURITY-DATE-CALCULATION -->        CLOSE-SP1-FILE
    TIM -->        LOAD-SPA1-FILE
    LOAN-CALCULATIONS -->        OPEN-SPA1-FILE
    TIM365 -->        START-SPA1-FILE
    LOAN-CALCULATIONS -->        READ-SPA1-FILE
    TIM360 -->        READ-SPA1-FILE-NEXT
    MATURITY-DATE-CALCULATION -->        CLOSE-SPA1-FILE
    TIM360 -->        LOAD-SPB1-FILE
    LOAN-CALCULATIONS -->        OPEN-SPB1-FILE
    TIM360 -->        READ-SPB1-FILE
    MATURITY-DATE-CALCULATION -->        CLOSE-SPB1-FILE
    INCREMENT-MONTHS -->        LOAD-SPC1-FILE
    MATURITY-DATE-CALCULATION -->        OPEN-SPC1-FILE
    LOAN-CALCULATIONS -->        READ-SPC1-FILE
    TIM360 -->        CLOSE-SPC1-FILE
    TIM360 -->        LOAD-BW1-FILE
    LOAN-CALCULATIONS -->        OPEN-BW1-FILE
    SETCTBL -->        START-BW1-FILE
    MATURITY-DATE-CALCULATION -->        READ-BW1-FILE
    INCREMENT-MONTHS -->        READ-BW1-FILE-NEXT
    INCREMENT-DAYS -->        CLOSE-BW1-FILE
    UPWK-LC-CALC -->        LOAD-GI1-FILE
    LATE-CHARGE-TEST-ELREAD -->        OPEN-GI1-FILE
    INCREMENT-UNITPER -->        COUNT-GI1-FILE
    TIMALL -->        START-GI1-FILE
    LCAS-GET-GRACE-DATE -->        READ-GI1-FILE
    LCAS-FIND-LAST-GRACE-DAY -->        READ-GI1-FILE-NEXT
    LCAS-CHECK-EXTENDING-GRACE -->        CLOSE-GI1-FILE
    INCREMENT-DAYS -->        LOAD-CD1-FILE
    LCAS-ADJUST-FOR-MONTH-END -->        OPEN-CD1-FILE
    INCREMENT-DAYS -->        START-CD1-FILE
    LCAS-CHECK-HOLIDAY -->        START-CD1-FILE-NOT-GREATER
    LCAS-CHECK-DAY -->        READ-CD1-FILE
    INCREMENT-DAYS -->        READ-CD1-FILE-NEXT
    WEEKDAY -->        READ-CD1-FILE-PREVIOUS
    INCREMENT-DAYS -->        CLOSE-CD1-FILE
    INCREMENT-DAYS -->        LOAD-LN1-FILE
    PAID-THRU-CALC-ADDON -->        OPEN-LN1-FILE
    PAID-THRU-CALC-NORMAL-E -->        START-LN1-FILE
    PAID-THRU-CALC-NORMAL -->        START-LN1-FILE-GREATER
    INCREMENT-UNITPER -->        READ-LN1-FILE
    INCREMENT-UNITPER -->        READ-LN1-FILE-NEXT
    INCREMENT-UNITPER -->        CLOSE-LN1-FILE
    GET-LT-P-REC -->        LOAD-LTI1-FILE
    SEND-MESS -->        OPEN-LTI1-FILE
    PAID-THRU-ADDON-SUM -->        START-LTI1-FILE
    LATE-CHARGE-TEST-ELREAD -->        READ-LTI1-FILE
    UPWK-LC-CALC -->        READ-LTI1-FILE-NEXT
    INCREMENT-UNITPER -->        CLOSE-LTI1-FILE
    LATE-CHARGE-TEST-ELREAD -->        GET-LT-P-REC
    LCAP-CALC-PDTH-ADDON -->        LOAD-LTP1-FILE
    LCAP-CALC-PDTH -->        OPEN-LTP1-FILE
    UNPACK-PAYMENT-SCHEDULE -->        START-LTP1-FILE
    TIMUPER -->        READ-LTP1-FILE
    MATURITY-DATE-CALCULATION -->        READ-LTP1-FILE-NEXT
    LCAP-A-C -->        CLOSE-LTP1-FILE
    LCAP-B-J -->        LOAD-LP1-FILE
    LCAP-D -->        OPEN-LP1-FILE
    LCAP-E-X -->        START-LP1-FILE
    LCAP-F -->        START-LP1-FILE-SCAN
    LCAP-G-K -->        START-LP1-FILE-NOT-GREATER
    LCAP-H -->        READ-LP1-FILE
    LCAP-I-L -->        READ-LP1-FILE-NEXT
    LCAP-M -->        READ-LP1-FILE-PREVIOUS
    LCAP-N -->        CLOSE-LP1-FILE
    LCAP-P -->        LOAD-LXE1-FILE
    LCAP-S -->        OPEN-LXE1-FILE
    LCAP-ASSURE-LCPDTH -->        START-LXE1-FILE
    LCAP-MDTE-CHK -->        READ-LXE1-FILE
    LCAP-ASSESS-CHK -->        READ-LXE1-FILE-NEXT
    LCAP-ASSESS-CHK -->        CLOSE-LXE1-FILE
    LCAP-CALC-TEST -->        LOAD-LXG1-FILE
    LCAP-CALC-PDTH -->        OPEN-LXG1-FILE
    TIM365 -->        START-LXG1-FILE
    LCAP-A-AL-OK-TEST -->        READ-LXG1-FILE
    LCAP-MDTE-CHK -->        READ-LXG1-FILE-NEXT
    LCAP-ASSESS-CHK -->        CLOSE-LXG1-FILE
    LCAP-CALC-TEST -->        OPEN-WK-FILE-OUTPUT
    LCAP-UPD-LCPD -->        OPEN-WK-FILE
    LCAP-UPD-LCPD -->        READ-WK-FILE
    LCAP-UPD-LCPD -->        WRITE-WK-FILE
    LCAP-UPD-LCPD -->        REWRITE-WK-FILE
    LCAP-UPD-LCPD -->        DELETE-WK-FILE
    LCAP-MDTE-CHK -->        CLOSE-WK-FILE
    LCAP-LCPDTH-DATE-TEST -->        LOAD-RC2-FILE
    LCAP-ASSESS-CHK -->        OPEN-RC2-FILE
    LCAP-CALC-TEST -->        START-RC2-FILE
    LCAP-UPD-LCPD -->        READ-RC2-FILE
    LCAP-PICK-PDTH-CALC -->        READ-RC2-FILE-NEXT
    LCAP-LCPDTH-DATE-TEST -->        CLOSE-RC2-FILE
    LCAP-MDTE-CHK -->        LOAD-OP-FILE
    LCAP-MDTE-CHK -->        OPEN-OP-FILE
    LCAP-ASSESS-CHK -->        OPEN-OP-FILE-OUTPUT
    LCAP-CALC-TEST -->        CLOSE-OP-FILE
    LCAP-UPD-LCPD -->        IO-ERROR
    LCAP-UPD-LCPD -->        END-PROGRAM
    LCAP-UPD-LCPD -->        EXIT-PROG
    LCAP-UPD-LCPD -->        STOP-RUN