graph TD
    APIPAY_Inlined.CBL --> C-DATER-MAIN
    C-DATER-MAIN --> DateCompare
    C-DATER-MAIN --> DateIncrement
    C-DATER-MAIN --> DateDecrement
    C-DATER-MAIN --> LeapYearCheck
    C-DATER-MAIN --> ElapsedTime
