flowchart LR
    NUM-DATE --> SV-NUM-DATE
    SYS-DATE --> SV-SYS-DATE
    WS-DATE1 --> P-DATE-IN --> C-CALL-JUL --> WS-JUL-1
    WS-DATE2 --> P-DATE-IN --> C-CALL-JUL --> WS-JUL-2
    WS-JUL-1 & WS-JUL-2 --> [Comparison] --> WS-XSIGN
