      * COPYMEMBER: LIBLP/LPFDUD
      *************************************************************
      *                     'UD'
      *            ( UNEARNED DELINQUENCY STATISTICS FILE )
      * REV:
      *************************************************************
       FD  OUD-FILE
           LABEL RECORDS ARE STANDARD.
       COPY "LIBUP/A30SRC/LP01UD.CPY" REPLACING LEADING "UD" BY "OUD".
