       BYPASS-SERVICE.
           MOVE "RV" TO LP-TRCD.

      * LET REVERSAL 'RV' RECORD HAVE THE LP-PAYDATE OF THE
      * RECORD BEING REVERSED:
           MOVE TRANS-DATE TO LP-TRDATE LP-PAYDATE.

      ***********************************************************
      * LOGIC FROM BEGINNING OF DISPLAY-ENTRY-LINE IN LONPF8:
      ***********************************************************
           SUBTRACT LP-APCUR FROM LP-CURBAL.

      * CANT CHANGE LN-REC IN HERE! LONPF2 WILL EXIT IF LN-REC DOESNT
      * MATCH WK-SAVE-RECORD
           MOVE LN-TOTPAYMNTD TO HOLD-LN-TOTPAYMNTD.

      * UPDATE CONTRACTUAL PAYMENTS TO DATE:
           ADD LP-APCUR TO LN-TOTPAYMNTD
           IF SP-CAL-RATETYPE(1) = "Z"
              SUBTRACT LP-EXTRA-PRIN-LFP FROM LN-TOTPAYMNTD
              ADD LP-EXTRA-PRIN-LFP        TO LN-TOTEXCPAYMNTD.
           IF SP-CONTRFRMLA = "A"
              ADD LP-APLC TO LN-TOTPAYMNTD.
           ADD LP-APINT TO LN-TOTPAYMNTD.

      * COMPUTE PAID THRU DATE
           MOVE LN-1STPYDATE TO PDTH-DATE-WORK.
           PERFORM PAID-THRU-CALCULATION.
           MOVE PDTH-DATE-FULL TO LP-PDTH-DATE.

      * CANT CHANGE LN-REC IN HERE! LONPF2 WILL EXIT IF LN-REC DOESNT
      * MATCH WK-SAVE-RECORD
           MOVE HOLD-LN-TOTPAYMNTD TO LN-TOTPAYMNTD.

           MOVE BP-TRCD TO HOLD-BP-TRCD LP-TRCD.
           MOVE BP-REFCD TO LP-REFNO HOLD-LP-REFNO.

      * PAYMENT UPDATE

           MOVE LN-ACCTNO TO LOAN-KEY.
           MOVE LN-SSNO(1) TO BORROWER-KEY.

