      *================================================================*
      * END COPYBOOK: LIBLP\LPLPGS_SQL.CPY                                *
      *================================================================*
      *================================================================*
      * EMBEDDED COPYBOOK: LIBLP\LPLNGS_SQL.CPY                           *
      *================================================================*
      * COPYMEMBER: LIBLP/LPLNGS_SQL
      ******************************************************************
      *
      * DESCRIPTION: SQL GET & SET - LOAN MASTER FILE
      *
      *=================================================================
      * REV:
      * JKC 2021-0430 ***NEW***
      * JKC 2024-0404 ADDED LN-LOS-APP-ID.
      *
      ******************************************************************
      *-----------------------------------------------------------------
      *    LOAD LN-REC FROM QLN-REC; FOR READ & READ-NEXT
      *-----------------------------------------------------------------
       GET-LN-FIELDS.
           MOVE QLN-OWNBR TO LN-OWNBR.
           MOVE QLN-ACCTNO TO LN-ACCTNO.
           MOVE QLN-CLASS TO LN-CLASS.
           MOVE QLN-SUBCLASS TO LN-SUBCLASS.
           MOVE QLN-LAWCODE TO LN-LAWCODE.
           MOVE QLN-SSNO1 TO LN-SSNO1.
           MOVE QLN-MAKERCD1 TO LN-MAKERCD1.
           MOVE QLN-SSNO2 TO LN-SSNO2.
           MOVE QLN-MAKERCD2 TO LN-MAKERCD2.
           MOVE QLN-SSNO3 TO LN-SSNO3.
           MOVE QLN-MAKERCD3 TO LN-MAKERCD3.
           MOVE QLN-SSNO4 TO LN-SSNO4.
           MOVE QLN-MAKERCD4 TO LN-MAKERCD4.
           MOVE QLN-ORGST TO LN-ORGST.
           MOVE QLN-ORGBR TO LN-ORGBR.
           MOVE QLN-OWNST TO LN-OWNST.
           MOVE QLN-SPRCLASS TO LN-SPRCLASS.
           MOVE QLN-CONVERCD TO LN-CONVERCD.
           MOVE QLN-MIDSTREAM TO LN-MIDSTREAM.
           MOVE QLN-PURCD TO LN-PURCD.
           MOVE QLN-SRCD TO LN-SRCD.
           MOVE QLN-COLLCD TO LN-COLLCD.
           MOVE QLN-COLLID TO LN-COLLID.
           MOVE QLN-POCD TO LN-POCD.
           MOVE QLN-PLCD TO LN-PLCD.
           MOVE QLN-PLTYPE TO LN-PLTYPE.
           MOVE QLN-CONFIDENTCD TO LN-CONFIDENTCD.
           MOVE QLN-ALLOTCD TO LN-ALLOTCD.
           MOVE QLN-RECASTCD TO LN-RECASTCD.
           MOVE QLN-SKIP-TRW TO LN-SKIP-TRW.
           MOVE QLN-STATUSFG TO LN-STATUSFG.
           MOVE QLN-SMALLOAN TO LN-SMALLOAN.
           MOVE QLN-SALEFIN TO LN-SALEFIN.
           MOVE QLN-SERVACCT TO LN-SERVACCT.
           MOVE QLN-LOANTYPE TO LN-LOANTYPE.
           MOVE QLN-ADDON-FG TO LN-ADDON-FG.
           MOVE QLN-PAY-SCHLD-FG TO LN-PAY-SCHLD-FG.
           MOVE QLN-LC-CODE TO LN-LC-CODE.
           MOVE QLN-CAN-LOAN-NO TO LN-CAN-LOAN-NO.
           MOVE QLN-STATFLAGS TO LN-STATFLAGS.

           MOVE QLN-ENTDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-ENTDATE.


           MOVE QLN-LOANDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-LOANDATE.


           MOVE QLN-PURDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-PURDATE.


           MOVE QLN-INTDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INTDATE.


           MOVE QLN-CASHDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-CASHDATE.


           MOVE QLN-FILEDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-FILEDATE.


           MOVE QLN-RESCISSION-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-RESCISSION-DATE.


           MOVE QLN-PART-RECOURSE-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-PART-RECOURSE-DATE.


           MOVE QLN-ORIG-1STPYDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-ORIG-1STPYDATE.


           MOVE QLN-1STPYDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-1STPYDATE.


           MOVE QLN-JDDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-JDDATE.


           MOVE QLN-PLDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-PLDATE.


           MOVE QLN-PL-TRDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-PL-TRDATE.


           MOVE QLN-ACCELDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-ACCELDATE.


           MOVE QLN-REDUDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-REDUDATE.


           MOVE QLN-POFFDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-POFFDATE.


           MOVE QLN-PO-TRDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-PO-TRDATE.


           MOVE QLN-LEGALDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-LEGALDATE.


           MOVE QLN-BNKRPTDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-BNKRPTDATE.


           MOVE QLN-BNKRPT-DISMISS-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-BNKRPT-DISMISS-DATE.


           MOVE QLN-BNKRPT-DISCHARGE-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-BNKRPT-DISCHARGE-DATE.


           MOVE QLN-BNKRPT-REAFFIRM-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-BNKRPT-REAFFIRM-DATE.


           MOVE QLN-DEBTAIDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-DEBTAIDATE.


           MOVE QLN-REPODATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-REPODATE.


           MOVE QLN-REDEEMDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-REDEEMDATE.


           MOVE QLN-SOLDDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-SOLDDATE.


           MOVE QLN-INS-CONFIRM-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INS-CONFIRM-DATE.


           MOVE QLN-PRIOR-RN-FOR10-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-PRIOR-RN-FOR10-DATE.


           MOVE QLN-LAST-RN-FOR10-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-LAST-RN-FOR10-DATE.


           MOVE QLN-TRW-DOFD-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-TRW-DOFD-DATE.


           MOVE QLN-LAST-PYPA-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-LAST-PYPA-DATE.


           MOVE QLN-BT-TRDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-BT-TRDATE.


           MOVE QLN-METRO2-LAST-PMT-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-METRO2-LAST-PMT-DATE.


           MOVE QLN-FOLLOWUP-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-FOLLOWUP-DATE.


           MOVE QLN-LAST-ACCRUAL-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-LAST-ACCRUAL-DATE.

           MOVE QLN-APRATE TO LN-APRATE.
           MOVE QLN-EFFRATE TO LN-EFFRATE.
           MOVE QLN-SMPRATE TO LN-SMPRATE.
           MOVE QLN-YLDRATE TO LN-YLDRATE.
           MOVE QLN-OVRDRATE TO LN-OVRDRATE.
           MOVE QLN-ENDORATE TO LN-ENDORATE.
           MOVE QLN-JDRATE TO LN-JDRATE.
           MOVE QLN-ACCRATE TO LN-ACCRATE.
           MOVE QLN-REDURATE TO LN-REDURATE.
           MOVE QLN-CONRATE TO LN-CONRATE.
           MOVE QLN-SERVPER TO LN-SERVPER.
           MOVE QLN-SELLPR TO LN-SELLPR.
           MOVE QLN-DOWNPY TO LN-DOWNPY.
           MOVE QLN-TRADEIN TO LN-TRADEIN.
           MOVE QLN-LNAMT TO LN-LNAMT.
           MOVE QLN-FINCHG TO LN-FINCHG.
           MOVE QLN-INTCHG TO LN-INTCHG.
           MOVE QLN-SERCHG TO LN-SERCHG.
           MOVE QLN-EXTCHG TO LN-EXTCHG.
           MOVE QLN-MAINTFEE TO LN-MAINTFEE.
           MOVE QLN-POINTS TO LN-POINTS.
           MOVE QLN-PROCEEDS TO LN-PROCEEDS.
           MOVE QLN-ORGTERM TO LN-ORGTERM.
           MOVE QLN-1STPYAMT TO LN-1STPYAMT.
           MOVE QLN-NOREGPY TO LN-NOREGPY.
           MOVE QLN-REGPYAMT TO LN-REGPYAMT.
           MOVE QLN-LASTPYAMT TO LN-LASTPYAMT.
           MOVE QLN-PROCASH TO LN-PROCASH.
           MOVE QLN-TILLNO TO LN-TILLNO.
           MOVE QLN-STATE-FLAG TO LN-STATE-FLAG.
           MOVE QLN-STATE-WORKER TO LN-STATE-WORKER.
           MOVE QLN-STATE-WORKER2 TO LN-STATE-WORKER2.
           MOVE QLN-FEECODE-1 TO LN-FEECODE(1).
           MOVE QLN-FEEAMT-1 TO LN-FEEAMT(1).
           MOVE QLN-FEEOURS-1 TO LN-FEEOURS(1).
           MOVE QLN-FEEFINCHG-1 TO LN-FEEFINCHG(1).
           MOVE QLN-FEECODE-2 TO LN-FEECODE(2).
           MOVE QLN-FEEAMT-2 TO LN-FEEAMT(2).
           MOVE QLN-FEEOURS-2 TO LN-FEEOURS(2).
           MOVE QLN-FEEFINCHG-2 TO LN-FEEFINCHG(2).
           MOVE QLN-FEECODE-3 TO LN-FEECODE(3).
           MOVE QLN-FEEAMT-3 TO LN-FEEAMT(3).
           MOVE QLN-FEEOURS-3 TO LN-FEEOURS(3).
           MOVE QLN-FEEFINCHG-3 TO LN-FEEFINCHG(3).
           MOVE QLN-FEECODE-4 TO LN-FEECODE(4).
           MOVE QLN-FEEAMT-4 TO LN-FEEAMT(4).
           MOVE QLN-FEEOURS-4 TO LN-FEEOURS(4).
           MOVE QLN-FEEFINCHG-4 TO LN-FEEFINCHG(4).
           MOVE QLN-FEECODE-5 TO LN-FEECODE(5).
           MOVE QLN-FEEAMT-5 TO LN-FEEAMT(5).
           MOVE QLN-FEEOURS-5 TO LN-FEEOURS(5).
           MOVE QLN-FEEFINCHG-5 TO LN-FEEFINCHG(5).
           MOVE QLN-FEECODE-6 TO LN-FEECODE(6).
           MOVE QLN-FEEAMT-6 TO LN-FEEAMT(6).
           MOVE QLN-FEEOURS-6 TO LN-FEEOURS(6).
           MOVE QLN-FEEFINCHG-6 TO LN-FEEFINCHG(6).
           MOVE QLN-FEECODE-7 TO LN-FEECODE(7).
           MOVE QLN-FEEAMT-7 TO LN-FEEAMT(7).
           MOVE QLN-FEEOURS-7 TO LN-FEEOURS(7).
           MOVE QLN-FEEFINCHG-7 TO LN-FEEFINCHG(7).
           MOVE QLN-FEECODE-8 TO LN-FEECODE(8).
           MOVE QLN-FEEAMT-8 TO LN-FEEAMT(8).
           MOVE QLN-FEEOURS-8 TO LN-FEEOURS(8).
           MOVE QLN-FEEFINCHG-8 TO LN-FEEFINCHG(8).
           MOVE QLN-FEECODE-9 TO LN-FEECODE(9).
           MOVE QLN-FEEAMT-9 TO LN-FEEAMT(9).
           MOVE QLN-FEEOURS-9 TO LN-FEEOURS(9).
           MOVE QLN-FEEFINCHG-9 TO LN-FEEFINCHG(9).
           MOVE QLN-FEECODE-10 TO LN-FEECODE(10).
           MOVE QLN-FEEAMT-10 TO LN-FEEAMT(10).
           MOVE QLN-FEEOURS-10 TO LN-FEEOURS(10).
           MOVE QLN-FEEFINCHG-10 TO LN-FEEFINCHG(10).
           MOVE QLN-FEECODE-11 TO LN-FEECODE(11).
           MOVE QLN-FEEAMT-11 TO LN-FEEAMT(11).
           MOVE QLN-FEEOURS-11 TO LN-FEEOURS(11).
           MOVE QLN-FEEFINCHG-11 TO LN-FEEFINCHG(11).
           MOVE QLN-FEECODE-12 TO LN-FEECODE(12).
           MOVE QLN-FEEAMT-12 TO LN-FEEAMT(12).
           MOVE QLN-FEEOURS-12 TO LN-FEEOURS(12).
           MOVE QLN-FEEFINCHG-12 TO LN-FEEFINCHG(12).
           MOVE QLN-FEECODE-13 TO LN-FEECODE(13).
           MOVE QLN-FEEAMT-13 TO LN-FEEAMT(13).
           MOVE QLN-FEEOURS-13 TO LN-FEEOURS(13).
           MOVE QLN-FEEFINCHG-13 TO LN-FEEFINCHG(13).
           MOVE QLN-FEECODE-14 TO LN-FEECODE(14).
           MOVE QLN-FEEAMT-14 TO LN-FEEAMT(14).
           MOVE QLN-FEEOURS-14 TO LN-FEEOURS(14).
           MOVE QLN-FEEFINCHG-14 TO LN-FEEFINCHG(14).
           MOVE QLN-FEECODE-15 TO LN-FEECODE(15).
           MOVE QLN-FEEAMT-15 TO LN-FEEAMT(15).
           MOVE QLN-FEEOURS-15 TO LN-FEEOURS(15).
           MOVE QLN-FEEFINCHG-15 TO LN-FEEFINCHG(15).
           MOVE QLN-FEECODE-16 TO LN-FEECODE(16).
           MOVE QLN-FEEAMT-16 TO LN-FEEAMT(16).
           MOVE QLN-FEEOURS-16 TO LN-FEEOURS(16).
           MOVE QLN-FEEFINCHG-16 TO LN-FEEFINCHG(16).
           MOVE QLN-FEECODE-17 TO LN-FEECODE(17).
           MOVE QLN-FEEAMT-17 TO LN-FEEAMT(17).
           MOVE QLN-FEEOURS-17 TO LN-FEEOURS(17).
           MOVE QLN-FEEFINCHG-17 TO LN-FEEFINCHG(17).
           MOVE QLN-FEECODE-18 TO LN-FEECODE(18).
           MOVE QLN-FEEAMT-18 TO LN-FEEAMT(18).
           MOVE QLN-FEEOURS-18 TO LN-FEEOURS(18).
           MOVE QLN-FEEFINCHG-18 TO LN-FEEFINCHG(18).
           MOVE QLN-FEECODE-19 TO LN-FEECODE(19).
           MOVE QLN-FEEAMT-19 TO LN-FEEAMT(19).
           MOVE QLN-FEEOURS-19 TO LN-FEEOURS(19).
           MOVE QLN-FEEFINCHG-19 TO LN-FEEFINCHG(19).
           MOVE QLN-FEECODE-20 TO LN-FEECODE(20).
           MOVE QLN-FEEAMT-20 TO LN-FEEAMT(20).
           MOVE QLN-FEEOURS-20 TO LN-FEEOURS(20).
           MOVE QLN-FEEFINCHG-20 TO LN-FEEFINCHG(20).
           MOVE QLN-INSURED TO LN-INSURED.
           MOVE QLN-INSTYPES TO LN-INSTYPES.
           MOVE QLN-INSELIGIBLE TO LN-INSELIGIBLE.
           MOVE QLN-INSCOMP-1 TO LN-INSCOMP(1).
           MOVE QLN-INSOURS-1 TO LN-INSOURS(1).

           MOVE QLN-INSEFF-DATE-1 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEFF-DATE(1).


           MOVE QLN-INSEXP-DATE-1 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEXP-DATE(1).

           MOVE QLN-INSPREM-1 TO LN-INSPREM(1).
           MOVE QLN-INSCOVR-1 TO LN-INSCOVR(1).
           MOVE QLN-INSCOMM-1 TO LN-INSCOMM(1).
           MOVE QLN-INSANTICERN-1 TO LN-INSANTICERN(1).
           MOVE QLN-INSANTICADJ-1 TO LN-INSANTICADJ(1).
           MOVE QLN-INSUFERN-1 TO LN-INSUFERN(1).
           MOVE QLN-INSACCERN-1 TO LN-INSACCERN(1).
           MOVE QLN-INSEARN-ORDER-1 TO LN-INSEARN-ORDER(1).
           MOVE QLN-INSFINCHG-1 TO LN-INSFINCHG(1).
           MOVE QLN-INSCOMP-2 TO LN-INSCOMP(2).
           MOVE QLN-INSOURS-2 TO LN-INSOURS(2).

           MOVE QLN-INSEFF-DATE-2 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEFF-DATE(2).


           MOVE QLN-INSEXP-DATE-2 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEXP-DATE(2).

           MOVE QLN-INSPREM-2 TO LN-INSPREM(2).
           MOVE QLN-INSCOVR-2 TO LN-INSCOVR(2).
           MOVE QLN-INSCOMM-2 TO LN-INSCOMM(2).
           MOVE QLN-INSANTICERN-2 TO LN-INSANTICERN(2).
           MOVE QLN-INSANTICADJ-2 TO LN-INSANTICADJ(2).
           MOVE QLN-INSUFERN-2 TO LN-INSUFERN(2).
           MOVE QLN-INSACCERN-2 TO LN-INSACCERN(2).
           MOVE QLN-INSEARN-ORDER-2 TO LN-INSEARN-ORDER(2).
           MOVE QLN-INSFINCHG-2 TO LN-INSFINCHG(2).
           MOVE QLN-INSCOMP-3 TO LN-INSCOMP(3).
           MOVE QLN-INSOURS-3 TO LN-INSOURS(3).

           MOVE QLN-INSEFF-DATE-3 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEFF-DATE(3).


           MOVE QLN-INSEXP-DATE-3 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEXP-DATE(3).

           MOVE QLN-INSPREM-3 TO LN-INSPREM(3).
           MOVE QLN-INSCOVR-3 TO LN-INSCOVR(3).
           MOVE QLN-INSCOMM-3 TO LN-INSCOMM(3).
           MOVE QLN-INSANTICERN-3 TO LN-INSANTICERN(3).
           MOVE QLN-INSANTICADJ-3 TO LN-INSANTICADJ(3).
           MOVE QLN-INSUFERN-3 TO LN-INSUFERN(3).
           MOVE QLN-INSACCERN-3 TO LN-INSACCERN(3).
           MOVE QLN-INSEARN-ORDER-3 TO LN-INSEARN-ORDER(3).
           MOVE QLN-INSFINCHG-3 TO LN-INSFINCHG(3).
           MOVE QLN-INSCOMP-4 TO LN-INSCOMP(4).
           MOVE QLN-INSOURS-4 TO LN-INSOURS(4).

           MOVE QLN-INSEFF-DATE-4 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEFF-DATE(4).


           MOVE QLN-INSEXP-DATE-4 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEXP-DATE(4).

           MOVE QLN-INSPREM-4 TO LN-INSPREM(4).
           MOVE QLN-INSCOVR-4 TO LN-INSCOVR(4).
           MOVE QLN-INSCOMM-4 TO LN-INSCOMM(4).
           MOVE QLN-INSANTICERN-4 TO LN-INSANTICERN(4).
           MOVE QLN-INSANTICADJ-4 TO LN-INSANTICADJ(4).
           MOVE QLN-INSUFERN-4 TO LN-INSUFERN(4).
           MOVE QLN-INSACCERN-4 TO LN-INSACCERN(4).
           MOVE QLN-INSEARN-ORDER-4 TO LN-INSEARN-ORDER(4).
           MOVE QLN-INSFINCHG-4 TO LN-INSFINCHG(4).
           MOVE QLN-INSCOMP-5 TO LN-INSCOMP(5).
           MOVE QLN-INSOURS-5 TO LN-INSOURS(5).

           MOVE QLN-INSEFF-DATE-5 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEFF-DATE(5).


           MOVE QLN-INSEXP-DATE-5 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEXP-DATE(5).

           MOVE QLN-INSPREM-5 TO LN-INSPREM(5).
           MOVE QLN-INSCOVR-5 TO LN-INSCOVR(5).
           MOVE QLN-INSCOMM-5 TO LN-INSCOMM(5).
           MOVE QLN-INSANTICERN-5 TO LN-INSANTICERN(5).
           MOVE QLN-INSANTICADJ-5 TO LN-INSANTICADJ(5).
           MOVE QLN-INSUFERN-5 TO LN-INSUFERN(5).
           MOVE QLN-INSACCERN-5 TO LN-INSACCERN(5).
           MOVE QLN-INSEARN-ORDER-5 TO LN-INSEARN-ORDER(5).
           MOVE QLN-INSFINCHG-5 TO LN-INSFINCHG(5).
           MOVE QLN-INSCOMP-6 TO LN-INSCOMP(6).
           MOVE QLN-INSOURS-6 TO LN-INSOURS(6).

           MOVE QLN-INSEFF-DATE-6 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEFF-DATE(6).


           MOVE QLN-INSEXP-DATE-6 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEXP-DATE(6).

           MOVE QLN-INSPREM-6 TO LN-INSPREM(6).
           MOVE QLN-INSCOVR-6 TO LN-INSCOVR(6).
           MOVE QLN-INSCOMM-6 TO LN-INSCOMM(6).
           MOVE QLN-INSANTICERN-6 TO LN-INSANTICERN(6).
           MOVE QLN-INSANTICADJ-6 TO LN-INSANTICADJ(6).
           MOVE QLN-INSUFERN-6 TO LN-INSUFERN(6).
           MOVE QLN-INSACCERN-6 TO LN-INSACCERN(6).
           MOVE QLN-INSEARN-ORDER-6 TO LN-INSEARN-ORDER(6).
           MOVE QLN-INSFINCHG-6 TO LN-INSFINCHG(6).
           MOVE QLN-INSCOMP-7 TO LN-INSCOMP(7).
           MOVE QLN-INSOURS-7 TO LN-INSOURS(7).

           MOVE QLN-INSEFF-DATE-7 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEFF-DATE(7).


           MOVE QLN-INSEXP-DATE-7 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEXP-DATE(7).

           MOVE QLN-INSPREM-7 TO LN-INSPREM(7).
           MOVE QLN-INSCOVR-7 TO LN-INSCOVR(7).
           MOVE QLN-INSCOMM-7 TO LN-INSCOMM(7).
           MOVE QLN-INSANTICERN-7 TO LN-INSANTICERN(7).
           MOVE QLN-INSANTICADJ-7 TO LN-INSANTICADJ(7).
           MOVE QLN-INSUFERN-7 TO LN-INSUFERN(7).
           MOVE QLN-INSACCERN-7 TO LN-INSACCERN(7).
           MOVE QLN-INSEARN-ORDER-7 TO LN-INSEARN-ORDER(7).
           MOVE QLN-INSFINCHG-7 TO LN-INSFINCHG(7).
           MOVE QLN-INSCOMP-8 TO LN-INSCOMP(8).
           MOVE QLN-INSOURS-8 TO LN-INSOURS(8).

           MOVE QLN-INSEFF-DATE-8 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEFF-DATE(8).


           MOVE QLN-INSEXP-DATE-8 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEXP-DATE(8).

           MOVE QLN-INSPREM-8 TO LN-INSPREM(8).
           MOVE QLN-INSCOVR-8 TO LN-INSCOVR(8).
           MOVE QLN-INSCOMM-8 TO LN-INSCOMM(8).
           MOVE QLN-INSANTICERN-8 TO LN-INSANTICERN(8).
           MOVE QLN-INSANTICADJ-8 TO LN-INSANTICADJ(8).
           MOVE QLN-INSUFERN-8 TO LN-INSUFERN(8).
           MOVE QLN-INSACCERN-8 TO LN-INSACCERN(8).
           MOVE QLN-INSEARN-ORDER-8 TO LN-INSEARN-ORDER(8).
           MOVE QLN-INSFINCHG-8 TO LN-INSFINCHG(8).
           MOVE QLN-INSCOMP-9 TO LN-INSCOMP(9).
           MOVE QLN-INSOURS-9 TO LN-INSOURS(9).

           MOVE QLN-INSEFF-DATE-9 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEFF-DATE(9).


           MOVE QLN-INSEXP-DATE-9 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEXP-DATE(9).

           MOVE QLN-INSPREM-9 TO LN-INSPREM(9).
           MOVE QLN-INSCOVR-9 TO LN-INSCOVR(9).
           MOVE QLN-INSCOMM-9 TO LN-INSCOMM(9).
           MOVE QLN-INSANTICERN-9 TO LN-INSANTICERN(9).
           MOVE QLN-INSANTICADJ-9 TO LN-INSANTICADJ(9).
           MOVE QLN-INSUFERN-9 TO LN-INSUFERN(9).
           MOVE QLN-INSACCERN-9 TO LN-INSACCERN(9).
           MOVE QLN-INSEARN-ORDER-9 TO LN-INSEARN-ORDER(9).
           MOVE QLN-INSFINCHG-9 TO LN-INSFINCHG(9).
           MOVE QLN-INSCOMP-10 TO LN-INSCOMP(10).
           MOVE QLN-INSOURS-10 TO LN-INSOURS(10).

           MOVE QLN-INSEFF-DATE-10 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEFF-DATE(10).


           MOVE QLN-INSEXP-DATE-10 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INSEXP-DATE(10).

           MOVE QLN-INSPREM-10 TO LN-INSPREM(10).
           MOVE QLN-INSCOVR-10 TO LN-INSCOVR(10).
           MOVE QLN-INSCOMM-10 TO LN-INSCOMM(10).
           MOVE QLN-INSANTICERN-10 TO LN-INSANTICERN(10).
           MOVE QLN-INSANTICADJ-10 TO LN-INSANTICADJ(10).
           MOVE QLN-INSUFERN-10 TO LN-INSUFERN(10).
           MOVE QLN-INSACCERN-10 TO LN-INSACCERN(10).
           MOVE QLN-INSEARN-ORDER-10 TO LN-INSEARN-ORDER(10).
           MOVE QLN-INSFINCHG-10 TO LN-INSFINCHG(10).
           MOVE QLN-PY-YYYYMM-RECDEL TO LN-PY-YYYYMM-RECDEL.
           MOVE QLN-MTD-PAYS-RECDEL TO LN-MTD-PAYS-RECDEL.
           MOVE QLN-GARNISH-EXTR TO LN-GARNISH-EXTR.
           MOVE QLN-SHIP-SAME-FG TO LN-SHIP-SAME-FG.
           MOVE QLN-AD-D-INS-COVR TO LN-AD-D-INS-COVR.
           MOVE QLN-TOT-PARTIAL-CHGOFF TO LN-TOT-PARTIAL-CHGOFF.
           MOVE QLN-LPO TO LN-LPO.
           MOVE QLN-REP-CD TO LN-REP-CD.
           MOVE QLN-EMP-ID TO LN-EMP-ID.
           MOVE QLN-PROCESS-CD TO LN-PROCESS-CD.
           MOVE QLN-WCBC-CREDITLIM TO LN-WCBC-CREDITLIM.
           MOVE QLN-FOLLOWUP-CD TO LN-FOLLOWUP-CD.
           MOVE QLN-MIP-FG TO LN-MIP-FG.
           MOVE QLN-MIP-MTD-CLAHPAID TO LN-MIP-MTD-CLAHPAID.

           MOVE QLN-MIP-CLPDTH-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-MIP-CLPDTH-DATE.

           MOVE QLN-MIP-TOT-CLPAID TO LN-MIP-TOT-CLPAID.

           MOVE QLN-MIP-AHPDTH-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-MIP-AHPDTH-DATE.

           MOVE QLN-MIP-TOT-AHPAID TO LN-MIP-TOT-AHPAID.
           MOVE QLN-IL-GROSS-INCOME TO LN-IL-GROSS-INCOME.
           MOVE QLN-IL-GROSS-INCOME2 TO LN-IL-GROSS-INCOME2.
           MOVE QLN-RESCISSION TO LN-RESCISSION.
           MOVE QLN-INTERIM-TRW TO LN-INTERIM-TRW.
           MOVE QLN-DLNO TO LN-DLNO.
           MOVE QLN-DLPOOL TO LN-DLPOOL.
           MOVE QLN-DLRECOURSE TO LN-DLRECOURSE.
           MOVE QLN-DLPARTRCAMT TO LN-DLPARTRCAMT.
           MOVE QLN-ORIGPURAMT TO LN-ORIGPURAMT.
           MOVE QLN-PURBAL TO LN-PURBAL.
           MOVE QLN-DLRVPRIN-1 TO LN-DLRVPRIN(1).
           MOVE QLN-DLRVPRIN-2 TO LN-DLRVPRIN(2).
           MOVE QLN-DLRVPRIN-3 TO LN-DLRVPRIN(3).
           MOVE QLN-DLRVCHGS-1 TO LN-DLRVCHGS(1).
           MOVE QLN-DLRVCHGS-2 TO LN-DLRVCHGS(2).
           MOVE QLN-DLRVCHGS-3 TO LN-DLRVCHGS(3).
           MOVE QLN-DLPARVHELD TO LN-DLPARVHELD.
           MOVE QLN-DLPARVPAID TO LN-DLPARVPAID.
           MOVE QLN-DLDISC TO LN-DLDISC.

           MOVE QLN-LCPDTH-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-LCPDTH-DATE.


           MOVE QLN-INTPDTH-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-INTPDTH-DATE.

           MOVE QLN-CURBAL TO LN-CURBAL.
           MOVE QLN-INTBAL TO LN-INTBAL.
           MOVE QLN-LCBAL TO LN-LCBAL.
           MOVE QLN-OTHBAL TO LN-OTHBAL.
           MOVE QLN-OT2BAL TO LN-OT2BAL.
           MOVE QLN-LCPAID TO LN-LCPAID.
           MOVE QLN-LCPARTIALS TO LN-LCPARTIALS.
           MOVE QLN-STMT-COUNTER TO LN-STMT-COUNTER.
           MOVE QLN-PRIOR-STMT-COUNTER TO LN-PRIOR-STMT-COUNTER.
           MOVE QLN-FROZEN-REASON TO LN-FROZEN-REASON.
           MOVE QLN-COUPON-STATEMENT TO LN-COUPON-STATEMENT.
           MOVE QLN-MONTHEND-BAL TO LN-MONTHEND-BAL.
           MOVE QLN-ANTICTERM TO LN-ANTICTERM.
           MOVE QLN-ANTICERN-1 TO LN-ANTICERN(1).
           MOVE QLN-ANTICADJ-1 TO LN-ANTICADJ(1).
           MOVE QLN-UFERN-1 TO LN-UFERN(1).
           MOVE QLN-ACCERN-1 TO LN-ACCERN(1).
           MOVE QLN-EARN-ORDER-1 TO LN-EARN-ORDER(1).
           MOVE QLN-ANTICERN-2 TO LN-ANTICERN(2).
           MOVE QLN-ANTICADJ-2 TO LN-ANTICADJ(2).
           MOVE QLN-UFERN-2 TO LN-UFERN(2).
           MOVE QLN-ACCERN-2 TO LN-ACCERN(2).
           MOVE QLN-EARN-ORDER-2 TO LN-EARN-ORDER(2).
           MOVE QLN-ANTICERN-3 TO LN-ANTICERN(3).
           MOVE QLN-ANTICADJ-3 TO LN-ANTICADJ(3).
           MOVE QLN-UFERN-3 TO LN-UFERN(3).
           MOVE QLN-ACCERN-3 TO LN-ACCERN(3).
           MOVE QLN-EARN-ORDER-3 TO LN-EARN-ORDER(3).
           MOVE QLN-ANTICERN-4 TO LN-ANTICERN(4).
           MOVE QLN-ANTICADJ-4 TO LN-ANTICADJ(4).
           MOVE QLN-UFERN-4 TO LN-UFERN(4).
           MOVE QLN-ACCERN-4 TO LN-ACCERN(4).
           MOVE QLN-EARN-ORDER-4 TO LN-EARN-ORDER(4).
           MOVE QLN-ANTICERN-5 TO LN-ANTICERN(5).
           MOVE QLN-ANTICADJ-5 TO LN-ANTICADJ(5).
           MOVE QLN-UFERN-5 TO LN-UFERN(5).
           MOVE QLN-ACCERN-5 TO LN-ACCERN(5).
           MOVE QLN-EARN-ORDER-5 TO LN-EARN-ORDER(5).
           MOVE QLN-ANTICERN-6 TO LN-ANTICERN(6).
           MOVE QLN-ANTICADJ-6 TO LN-ANTICADJ(6).
           MOVE QLN-UFERN-6 TO LN-UFERN(6).
           MOVE QLN-ACCERN-6 TO LN-ACCERN(6).
           MOVE QLN-EARN-ORDER-6 TO LN-EARN-ORDER(6).
           MOVE QLN-ANTICERN-7 TO LN-ANTICERN(7).
           MOVE QLN-ANTICADJ-7 TO LN-ANTICADJ(7).
           MOVE QLN-UFERN-7 TO LN-UFERN(7).
           MOVE QLN-ACCERN-7 TO LN-ACCERN(7).
           MOVE QLN-EARN-ORDER-7 TO LN-EARN-ORDER(7).
           MOVE QLN-ANTICERN-8 TO LN-ANTICERN(8).
           MOVE QLN-ANTICADJ-8 TO LN-ANTICADJ(8).
           MOVE QLN-UFERN-8 TO LN-UFERN(8).
           MOVE QLN-ACCERN-8 TO LN-ACCERN(8).
           MOVE QLN-EARN-ORDER-8 TO LN-EARN-ORDER(8).
           MOVE QLN-ANTICERN-9 TO LN-ANTICERN(9).
           MOVE QLN-ANTICADJ-9 TO LN-ANTICADJ(9).
           MOVE QLN-UFERN-9 TO LN-UFERN(9).
           MOVE QLN-ACCERN-9 TO LN-ACCERN(9).
           MOVE QLN-EARN-ORDER-9 TO LN-EARN-ORDER(9).
           MOVE QLN-ANTICERN-10 TO LN-ANTICERN(10).
           MOVE QLN-ANTICADJ-10 TO LN-ANTICADJ(10).
           MOVE QLN-UFERN-10 TO LN-UFERN(10).
           MOVE QLN-ACCERN-10 TO LN-ACCERN(10).
           MOVE QLN-EARN-ORDER-10 TO LN-EARN-ORDER(10).
           MOVE QLN-LMO-PRIOR-INTEREST TO LN-LMO-PRIOR-INTEREST.
           MOVE QLN-PRIOR-UNEARNED TO LN-PRIOR-UNEARNED.
           MOVE QLN-ERNDELQ-STOP TO LN-ERNDELQ-STOP.
           MOVE QLN-NONACRERN TO LN-NONACRERN.
           MOVE QLN-PRIOR-NONACRERN TO LN-PRIOR-NONACRERN.

           MOVE QLN-ERN-IB-PDTH-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-ERN-IB-PDTH-DATE.

           MOVE QLN-ERN-IB-PRINBAL TO LN-ERN-IB-PRINBAL.
           MOVE QLN-ERN-IB-INTOWE TO LN-ERN-IB-INTOWE.
           MOVE QLN-TOTERN TO LN-TOTERN.
           MOVE QLN-TOTOTH TO LN-TOTOTH.
           MOVE QLN-TOTINT TO LN-TOTINT.
           MOVE QLN-TOTLCHG TO LN-TOTLCHG.
           MOVE QLN-TOTDEF TO LN-TOTDEF.
           MOVE QLN-TOTSERACCT TO LN-TOTSERACCT.
           MOVE QLN-LCWAIVERS TO LN-LCWAIVERS.
           MOVE QLN-INTWAIVERS TO LN-INTWAIVERS.
           MOVE QLN-TOTPAYMNTD TO LN-TOTPAYMNTD.
           MOVE QLN-TOTEXCPAYMNTD TO LN-TOTEXCPAYMNTD.
           MOVE QLN-TOTNODEF TO LN-TOTNODEF.
           MOVE QLN-YTDNODEF TO LN-YTDNODEF.
           MOVE QLN-TOTNODEFACT TO LN-TOTNODEFACT.
           MOVE QLN-YTDNODEFACT TO LN-YTDNODEFACT.
           MOVE QLN-TOTNOALDEL TO LN-TOTNOALDEL.
           MOVE QLN-YTDNOALDEL TO LN-YTDNOALDEL.
           MOVE QLN-YTDINTPD TO LN-YTDINTPD.
           MOVE QLN-LYRINTPD TO LN-LYRINTPD.
           MOVE QLN-TOTINTPD TO LN-TOTINTPD.
           MOVE QLN-RECASTINT TO LN-RECASTINT.
           MOVE QLN-RECASTPRIN TO LN-RECASTPRIN.
           MOVE QLN-CL-REBATE TO LN-CL-REBATE.
           MOVE QLN-AH-REBATE TO LN-AH-REBATE.
           MOVE QLN-PP-REBATE TO LN-PP-REBATE.
           MOVE QLN-INT-REBATE TO LN-INT-REBATE.
           MOVE QLN-SC-REBATE TO LN-SC-REBATE.
           MOVE QLN-MF-REBATE TO LN-MF-REBATE.
           MOVE QLN-DF-REBATE TO LN-DF-REBATE.
           MOVE QLN-EX-REBATE TO LN-EX-REBATE.
           MOVE QLN-O1-REBATE TO LN-O1-REBATE.
           MOVE QLN-O2-REBATE TO LN-O2-REBATE.
           MOVE QLN-O3-REBATE TO LN-O3-REBATE.
           MOVE QLN-O4-REBATE TO LN-O4-REBATE.
           MOVE QLN-O5-REBATE TO LN-O5-REBATE.
           MOVE QLN-O6-REBATE TO LN-O6-REBATE.
           MOVE QLN-O7-REBATE TO LN-O7-REBATE.
           MOVE QLN-UN-O7-REB TO LN-UN-O7-REB.
           MOVE QLN-UN-O8-REB TO LN-UN-O8-REB.
           MOVE QLN-UN-O9-REB TO LN-UN-O9-REB.
           MOVE QLN-UN-O10-REB TO LN-UN-O10-REB.
           MOVE QLN-PLREASON TO LN-PLREASON.
           MOVE QLN-COLLECTOR TO LN-COLLECTOR.
           MOVE QLN-ACTIONCD TO LN-ACTIONCD.
           MOVE QLN-ACTIONCD2 TO LN-ACTIONCD2.
           MOVE QLN-ATCODE TO LN-ATCODE.
           MOVE QLN-RECODE TO LN-RECODE.
           MOVE QLN-ESCROW-FG TO LN-ESCROW-FG.
           MOVE QLN-PROMDAYS-PASTDUE TO LN-PROMDAYS-PASTDUE.
           MOVE QLN-PROMID TO LN-PROMID.

           MOVE QLN-PROMDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-PROMDATE.

           MOVE QLN-PROMAMT TO LN-PROMAMT.

           MOVE QLN-PROMDATE2 TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-PROMDATE2.


           MOVE QLN-DATE-PAID-LAST TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-DATE-PAID-LAST.

           MOVE QLN-AMT-PAID-LAST TO LN-AMT-PAID-LAST.
           MOVE QLN-LASTCFORMNO TO LN-LASTCFORMNO.

           MOVE QLN-LASTCFORMDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-LASTCFORMDATE.

           MOVE QLN-DELCNT TO LN-DELCNT.
           MOVE QLN-DELCNT2 TO LN-DELCNT2.
           MOVE QLN-CREDITLIM TO LN-CREDITLIM.
           MOVE QLN-CRSCORE TO LN-CRSCORE.
           MOVE QLN-LASTSFORMNO TO LN-LASTSFORMNO.

           MOVE QLN-LASTSFORMDATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-LASTSFORMDATE.

           MOVE QLN-SOLCNT TO LN-SOLCNT.
           MOVE QLN-MESSAGE TO LN-MESSAGE.
           MOVE QLN-OLDACCTNO TO LN-OLDACCTNO.
           MOVE QLN-PRLNNO TO LN-PRLNNO.
           MOVE QLN-PRBAL TO LN-PRBAL.
           MOVE QLN-PRINTDUE TO LN-PRINTDUE.
           MOVE QLN-PRFINCHGRB TO LN-PRFINCHGRB.
           MOVE QLN-PRINSRB TO LN-PRINSRB.
           MOVE QLN-PRPOCD TO LN-PRPOCD.

           MOVE QLN-PRPODATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-PRPODATE.

           MOVE QLN-PRDELINQAMT TO LN-PRDELINQAMT.
           MOVE QLN-PRLNAMT TO LN-PRLNAMT.
           MOVE QLN-PRPDUE-DAYS TO LN-PRPDUE-DAYS.
           MOVE QLN-PRDLDISC-UNEARN TO LN-PRDLDISC-UNEARN.
           MOVE QLN-PRCONPROFILE TO LN-PRCONPROFILE.
           MOVE QLN-SUM-ORIGPURAMT TO LN-SUM-ORIGPURAMT.
           MOVE QLN-SUM-LNAMT TO LN-SUM-LNAMT.
           MOVE QLN-SUM-FINCHG TO LN-SUM-FINCHG.
           MOVE QLN-SUM-INTCHG TO LN-SUM-INTCHG.
           MOVE QLN-SUM-ORGTERM TO LN-SUM-ORGTERM.
           MOVE QLN-SUM-REGPYAMT TO LN-SUM-REGPYAMT.
           MOVE QLN-SUM-EXTCHG TO LN-SUM-EXTCHG.
           MOVE QLN-SUM-SERCHG TO LN-SUM-SERCHG.
           MOVE QLN-SUM-MAINTFEE TO LN-SUM-MAINTFEE.
           MOVE QLN-UNITPER-CD TO LN-UNITPER-CD.
           MOVE QLN-UNITPER-FREQ TO LN-UNITPER-FREQ.
           MOVE QLN-DAYS-IN-UNITPER TO LN-DAYS-IN-UNITPER.
           MOVE QLN-UNITPER-PER-YEAR TO LN-UNITPER-PER-YEAR.
           MOVE QLN-REPOCD TO LN-REPOCD.
           MOVE QLN-BR-TFR-FG TO LN-BR-TFR-FG.
           MOVE QLN-O3INS-DLPROC TO LN-O3INS-DLPROC.
           MOVE QLN-INSPREM-DLADJ TO LN-INSPREM-DLADJ.
           MOVE QLN-PLAMT TO LN-PLAMT.
           MOVE QLN-MTD-PRIN TO LN-MTD-PRIN.
           MOVE QLN-MTD-LC TO LN-MTD-LC.
           MOVE QLN-MTD-INT TO LN-MTD-INT.
           MOVE QLN-MTD-OT TO LN-MTD-OT.
           MOVE QLN-MTD-EX TO LN-MTD-EX.
           MOVE QLN-BNKRPT-CHAPTER TO LN-BNKRPT-CHAPTER.
           MOVE QLN-BMO-CON-STATUS TO LN-BMO-CON-STATUS.
           MOVE QLN-BMO-REC-STATUS TO LN-BMO-REC-STATUS.
           MOVE QLN-APP-NUMBER TO LN-APP-NUMBER.
           MOVE QLN-GIFTNET TO LN-GIFTNET.
           MOVE QLN-GIFTNET-OUR-PO TO LN-GIFTNET-OUR-PO.
           MOVE QLN-PROC-DISBURSED TO LN-PROC-DISBURSED.
           MOVE QLN-NOODDPY TO LN-NOODDPY.
           MOVE QLN-CONPROFILE-1 TO LN-CONPROFILE(1).
           MOVE QLN-CONPROFILE-2 TO LN-CONPROFILE(2).
           MOVE QLN-CONPROFILE-3 TO LN-CONPROFILE(3).
           MOVE QLN-CONPROFILE-4 TO LN-CONPROFILE(4).
           MOVE QLN-CONPROFILE-5 TO LN-CONPROFILE(5).
           MOVE QLN-RECPROFILE-1 TO LN-RECPROFILE(1).
           MOVE QLN-RECPROFILE-2 TO LN-RECPROFILE(2).
           MOVE QLN-RECPROFILE-3 TO LN-RECPROFILE(3).
           MOVE QLN-RECPROFILE-4 TO LN-RECPROFILE(4).
           MOVE QLN-RECPROFILE-5 TO LN-RECPROFILE(5).
           MOVE QLN-TRW-STATUS TO LN-TRW-STATUS.
           MOVE QLN-ORIGIN TO LN-ORIGIN.
           MOVE QLN-PO-TRCD TO LN-PO-TRCD.
           MOVE QLN-NEXIS-CRSCORE TO LN-NEXIS-CRSCORE.
           MOVE QLN-TRW-B-CONSUMER-IND TO LN-TRW-B-CONSUMER-IND.
           MOVE QLN-PARVHELD-PAID-FG TO LN-PARVHELD-PAID-FG.
           MOVE QLN-ACCT-FROZEN TO LN-ACCT-FROZEN.
           MOVE QLN-TRW-SPECIAL-CODE TO LN-TRW-SPECIAL-CODE.
           MOVE QLN-CREATION-STATUS TO LN-CREATION-STATUS.
           MOVE QLN-TOTNOLCHG TO LN-TOTNOLCHG.
           MOVE QLN-LBOX TO LN-LBOX.
           MOVE QLN-EXTRA-PRIN-LFP TO LN-EXTRA-PRIN-LFP.
           MOVE QLN-REMAIN-INT-SINCE-LFP TO LN-REMAIN-INT-SINCE-LFP.
           MOVE QLN-REMAIN-PRIN-SINCE-LFP TO LN-REMAIN-PRIN-SINCE-LFP.
           MOVE QLN-INTERIM-COUPON TO LN-INTERIM-COUPON.
           MOVE QLN-DLCOMM-O3-CMSI TO LN-DLCOMM-O3-CMSI.
           MOVE QLN-DLCOMM-PP-CMSI TO LN-DLCOMM-PP-CMSI.
           MOVE QLN-TRW-J-CONSUMER-IND TO LN-TRW-J-CONSUMER-IND.
           MOVE QLN-ACH TO LN-ACH.
           MOVE QLN-1099-C-FG TO LN-1099-C-FG.
           MOVE QLN-TRW-COMPLIANCE-CODE TO LN-TRW-COMPLIANCE-CODE.
           MOVE QLN-UNWIND-REASON-CODE TO LN-UNWIND-REASON-CODE.
           MOVE QLN-PBI-PBD-FG TO LN-PBI-PBD-FG.
           MOVE QLN-OLD-ACCT-FORMAT-FG TO LN-OLD-ACCT-FORMAT-FG.
           MOVE QLN-APPROVED-BY-USER TO LN-APPROVED-BY-USER.
           MOVE QLN-APPROVED-BY-CODE TO LN-APPROVED-BY-CODE.

           MOVE QLN-APPROVED-BY-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-APPROVED-BY-DATE.

           MOVE QLN-APPROVED-BY-TIME TO LN-APPROVED-BY-TIME.

           MOVE QLN-LTOUCH-DATE TO SQL-DATE-YYYY-MM-DD.
           PERFORM SQL-GET-DATE.
           MOVE SQL-DATE-YYYYMMDD TO LN-LTOUCH-DATE.

           MOVE QLN-LTOUCH-TIME TO LN-LTOUCH-TIME.
           MOVE QLN-LOS-APP-ID  TO LN-LOS-APP-ID.

      *-----------------------------------------------------------------
      *    LOAD QLN-REC FROM LN-REC; FOR WRITE & REWRITE
      *-----------------------------------------------------------------
