      *================================================================*
      * END COPYBOOK: LIBLP\LPLXEGS_SQL.CPY                                *
      *================================================================*
      *================================================================*
      * EMBEDDED COPYBOOK: LIBLP\LPLTPGS_SQL.CPY                           *
      *================================================================*
      * COPYMEMBER: LIBLP/LPLTPGS_SQL
      ******************************************************************
      *
      * DESCRIPTION: SQL GET & SET - LOAN TRAILER - PAYMENT SCHEDULE
      *
      *=================================================================
      * REV:
      * AMM 2021-0510 ***NEW***
      *
      ******************************************************************
      *-----------------------------------------------------------------
      *    LOAD LTP-REC FROM QLTP-REC; FOR READ & READ-NEXT
      *-----------------------------------------------------------------
       GET-LTP-FIELDS.
           MOVE QLTP-BRNO TO LTP-BRNO.
           MOVE QLTP-ACCTNO TO LTP-ACCTNO.
           MOVE QLTP-SEQNO TO LTP-SEQNO.

           IF ( QLTP-LTOUCH-DATE = "1900-01-01" )
              MOVE ZEROES TO LTP-LTOUCH-DATE
           ELSE
              MOVE QLTP-LTOUCH-DATE TO SQL-DATE-YYYY-MM-DD
              PERFORM SQL-GET-DATE
              MOVE SQL-DATE-YYYYMMDD TO LTP-LTOUCH-DATE.

           MOVE QLTP-SCHLD-TERM-1 TO LTP-SCHLD-TERM(1).
           MOVE QLTP-SCHLD-PAYMNT-1 TO LTP-SCHLD-PAYMNT(1).
           MOVE QLTP-SCHLD-TERM-2 TO LTP-SCHLD-TERM(2).
           MOVE QLTP-SCHLD-PAYMNT-2 TO LTP-SCHLD-PAYMNT(2).
           MOVE QLTP-SCHLD-TERM-3 TO LTP-SCHLD-TERM(3).
           MOVE QLTP-SCHLD-PAYMNT-3 TO LTP-SCHLD-PAYMNT(3).
           MOVE QLTP-SCHLD-TERM-4 TO LTP-SCHLD-TERM(4).
           MOVE QLTP-SCHLD-PAYMNT-4 TO LTP-SCHLD-PAYMNT(4).
           MOVE QLTP-SCHLD-TERM-5 TO LTP-SCHLD-TERM(5).
           MOVE QLTP-SCHLD-PAYMNT-5 TO LTP-SCHLD-PAYMNT(5).
           MOVE QLTP-SCHLD-TERM-6 TO LTP-SCHLD-TERM(6).
           MOVE QLTP-SCHLD-PAYMNT-6 TO LTP-SCHLD-PAYMNT(6).
           MOVE QLTP-SCHLD-TERM-7 TO LTP-SCHLD-TERM(7).
           MOVE QLTP-SCHLD-PAYMNT-7 TO LTP-SCHLD-PAYMNT(7).
           MOVE QLTP-SCHLD-TERM-8 TO LTP-SCHLD-TERM(8).
           MOVE QLTP-SCHLD-PAYMNT-8 TO LTP-SCHLD-PAYMNT(8).
           MOVE QLTP-SCHLD-TERM-9 TO LTP-SCHLD-TERM(9).
           MOVE QLTP-SCHLD-PAYMNT-9 TO LTP-SCHLD-PAYMNT(9).
           MOVE QLTP-SCHLD-TERM-10 TO LTP-SCHLD-TERM(10).
           MOVE QLTP-SCHLD-PAYMNT-10 TO LTP-SCHLD-PAYMNT(10).
           MOVE QLTP-SCHLD-TERM-11 TO LTP-SCHLD-TERM(11).
           MOVE QLTP-SCHLD-PAYMNT-11 TO LTP-SCHLD-PAYMNT(11).
           MOVE QLTP-SCHLD-TERM-12 TO LTP-SCHLD-TERM(12).
           MOVE QLTP-SCHLD-PAYMNT-12 TO LTP-SCHLD-PAYMNT(12).
           MOVE QLTP-SCHLD-TERM-13 TO LTP-SCHLD-TERM(13).
           MOVE QLTP-SCHLD-PAYMNT-13 TO LTP-SCHLD-PAYMNT(13).
           MOVE QLTP-SCHLD-TERM-14 TO LTP-SCHLD-TERM(14).
           MOVE QLTP-SCHLD-PAYMNT-14 TO LTP-SCHLD-PAYMNT(14).
           MOVE QLTP-SCHLD-TERM-15 TO LTP-SCHLD-TERM(15).
           MOVE QLTP-SCHLD-PAYMNT-15 TO LTP-SCHLD-PAYMNT(15).
           MOVE QLTP-SCHLD-TERM-16 TO LTP-SCHLD-TERM(16).
           MOVE QLTP-SCHLD-PAYMNT-16 TO LTP-SCHLD-PAYMNT(16).
           MOVE QLTP-SCHLD-TERM-17 TO LTP-SCHLD-TERM(17).
           MOVE QLTP-SCHLD-PAYMNT-17 TO LTP-SCHLD-PAYMNT(17).
           MOVE QLTP-SCHLD-TERM-18 TO LTP-SCHLD-TERM(18).
           MOVE QLTP-SCHLD-PAYMNT-18 TO LTP-SCHLD-PAYMNT(18).
           MOVE QLTP-SCHLD-TERM-19 TO LTP-SCHLD-TERM(19).
           MOVE QLTP-SCHLD-PAYMNT-19 TO LTP-SCHLD-PAYMNT(19).
           MOVE QLTP-SCHLD-TERM-20 TO LTP-SCHLD-TERM(20).
           MOVE QLTP-SCHLD-PAYMNT-20 TO LTP-SCHLD-PAYMNT(20).
           MOVE QLTP-SCHLD-TERM-21 TO LTP-SCHLD-TERM(21).
           MOVE QLTP-SCHLD-PAYMNT-21 TO LTP-SCHLD-PAYMNT(21).
           MOVE QLTP-SCHLD-TERM-22 TO LTP-SCHLD-TERM(22).
           MOVE QLTP-SCHLD-PAYMNT-22 TO LTP-SCHLD-PAYMNT(22).
           MOVE QLTP-SCHLD-TERM-23 TO LTP-SCHLD-TERM(23).
           MOVE QLTP-SCHLD-PAYMNT-23 TO LTP-SCHLD-PAYMNT(23).
           MOVE QLTP-SCHLD-TERM-24 TO LTP-SCHLD-TERM(24).
           MOVE QLTP-SCHLD-PAYMNT-24 TO LTP-SCHLD-PAYMNT(24).
           MOVE QLTP-SCHLD-TERM-25 TO LTP-SCHLD-TERM(25).
           MOVE QLTP-SCHLD-PAYMNT-25 TO LTP-SCHLD-PAYMNT(25).
           MOVE QLTP-SCHLD-TERM-26 TO LTP-SCHLD-TERM(26).
           MOVE QLTP-SCHLD-PAYMNT-26 TO LTP-SCHLD-PAYMNT(26).
           MOVE QLTP-SCHLD-TERM-27 TO LTP-SCHLD-TERM(27).
           MOVE QLTP-SCHLD-PAYMNT-27 TO LTP-SCHLD-PAYMNT(27).
           MOVE QLTP-SCHLD-TERM-28 TO LTP-SCHLD-TERM(28).
           MOVE QLTP-SCHLD-PAYMNT-28 TO LTP-SCHLD-PAYMNT(28).
           MOVE QLTP-SCHLD-TERM-29 TO LTP-SCHLD-TERM(29).
           MOVE QLTP-SCHLD-PAYMNT-29 TO LTP-SCHLD-PAYMNT(29).
           MOVE QLTP-SCHLD-TERM-30 TO LTP-SCHLD-TERM(30).
           MOVE QLTP-SCHLD-PAYMNT-30 TO LTP-SCHLD-PAYMNT(30).
           MOVE QLTP-SCHLD-TERM-31 TO LTP-SCHLD-TERM(31).
           MOVE QLTP-SCHLD-PAYMNT-31 TO LTP-SCHLD-PAYMNT(31).
           MOVE QLTP-SCHLD-TERM-32 TO LTP-SCHLD-TERM(32).
           MOVE QLTP-SCHLD-PAYMNT-32 TO LTP-SCHLD-PAYMNT(32).
           MOVE QLTP-SCHLD-TERM-33 TO LTP-SCHLD-TERM(33).
           MOVE QLTP-SCHLD-PAYMNT-33 TO LTP-SCHLD-PAYMNT(33).
           MOVE QLTP-SCHLD-TERM-34 TO LTP-SCHLD-TERM(34).
           MOVE QLTP-SCHLD-PAYMNT-34 TO LTP-SCHLD-PAYMNT(34).
           MOVE QLTP-SCHLD-TERM-35 TO LTP-SCHLD-TERM(35).
           MOVE QLTP-SCHLD-PAYMNT-35 TO LTP-SCHLD-PAYMNT(35).
           MOVE QLTP-SCHLD-TERM-36 TO LTP-SCHLD-TERM(36).
           MOVE QLTP-SCHLD-PAYMNT-36 TO LTP-SCHLD-PAYMNT(36).
           MOVE QLTP-SCHLD-TERM-37 TO LTP-SCHLD-TERM(37).
           MOVE QLTP-SCHLD-PAYMNT-37 TO LTP-SCHLD-PAYMNT(37).
           MOVE QLTP-SCHLD-TERM-38 TO LTP-SCHLD-TERM(38).
           MOVE QLTP-SCHLD-PAYMNT-38 TO LTP-SCHLD-PAYMNT(38).
           MOVE QLTP-SCHLD-TERM-39 TO LTP-SCHLD-TERM(39).
           MOVE QLTP-SCHLD-PAYMNT-39 TO LTP-SCHLD-PAYMNT(39).
           MOVE QLTP-SCHLD-TERM-40 TO LTP-SCHLD-TERM(40).
           MOVE QLTP-SCHLD-PAYMNT-40 TO LTP-SCHLD-PAYMNT(40).
           MOVE QLTP-SCHLD-TERM-41 TO LTP-SCHLD-TERM(41).
           MOVE QLTP-SCHLD-PAYMNT-41 TO LTP-SCHLD-PAYMNT(41).
 
      *-----------------------------------------------------------------
      *    LOAD QLTP-REC FROM LTP-REC; FOR WRITE & REWRITE
      *-----------------------------------------------------------------
