      ******************************************************************
       INITIALIZATION SECTION.
      ******************************************************************

           MOVE " " TO ERRCD.

           MOVE EXT-CONAME-USER-LOC TO BRANCH HOLD-PROG-BUF-BRANCH.

      *    ACCEPT ORIG-FIL   FROM ENVIRONMENT "FIL".
           ACCEPT TRANS-DATE FROM CENTURY-DATE.

      * WANT DAILY PROCESS PROGRAMS TO THINK YOU ARE IN BATCH AND NOT
      * TO DISPLAY ANYTHING
           MOVE "70" TO EXT-ROUTE-BUF.

      *  CREATE WK-FILE, IF RUNNING FROM EOCRON, WORK FILE IN /USR/TMP
      *  WAS NOT CREATED IN LONPA0
           PERFORM CREATE-WK-FILE.

           MOVE USER-PID TO TEMP-PID.

           MOVE BT-REFCD TO BATCH-REFCD.

      * CREATE SPOOL DIRECTORY AND OPEN SPOOL FILE IN 'EO'
      
      * XXXXXXXXXXXXXXXXXXXXXXXXXX
      * THIS CREATES HAVOC WHEN MULTIPLE USERS TRYING TO CREATE SAME REPORT
      *  EO/APIXXXXXX/0100CUACH AND REPOEX, THE LOG IS OPEN EXTEND
      * HANDLE THIS IN API??
      * XXXXXXXXXXXXXXXXXXXXXXXXXX

           MOVE BATCH-REFCD TO SAVE-EX-SPOOL-NAME.

      * CREATE EO DIRECTORY - HARD CODED RIGHT TO "API"
      * SC9990/EO/APIMMDDYY
           PERFORM CREATE-SPOOL-DIR.
           IF ERRCD NOT = " "
              GO TO END-INIT.

      * AT THIS POINT EX-SPOOL = EO/APIMMDDYY/0100CUACH (BATCH-REFCD)

      *    MOVE EX-SPOOL TO SUMMARY-SPOOL PRU-FILE.
      *    MOVE PRU-FILE TO LOG-SPOOL-DIR.

      * THIS IS TRYING TO CREATE 0100CUACH WHICH WE CAN NOT DO FOR MULTIPLE
      * PROCESSES
      *    PERFORM OPEN-PR-FILE.
      *    IF IO-FG NOT = 0
      *       GO TO END-INIT.
      *    PERFORM CLOSE-PR-FILE.

      * XXXX  MULTIPLE PROCESSES CAN NOT OPEN THIS AT SAME TIME

      * CREATE STEP EO/APIMMDDYY/0100EXCEPT FOR MAIN EXCEPTIONS REPORT
      *    MOVE "EXCEPT" TO SAVE-EX-SPOOL-NAME.
      *    PERFORM CREATE-SPOOL-DIR.
      *    IF ERRCD NOT = " "
      *       GO TO END-INIT.
      *    MOVE EX-SPOOL TO EXCEPT-SPOOL PRU-FILE.
      *    PERFORM OPEN-PR-FILE.
      *    IF IO-FG NOT = 0
      *       GO TO END-INIT.
      *    PERFORM CLOSE-PR-FILE.

      * CREATE STEP EO/APIMMDDYY/0100REPOEX FOR REPO EXCEPTIONS REPORT
      *    MOVE "REPOEX"   TO SAVE-EX-SPOOL-NAME.
      *    PERFORM CREATE-SPOOL-DIR.
      *    IF ERRCD NOT = " "
      *        GO TO END-INIT.
      *    MOVE EX-SPOOL TO REPOEX-SPOOL PRU-FILE.
      *    IF STAT = "00"
      *       PERFORM OPEN-PR-FILE-EXTEND
      *    ELSE
      *       PERFORM OPEN-PR-FILE.
      *    IF IO-FG NOT = 0
      *       GO TO END-INIT.
      *    PERFORM CLOSE-PR-FILE.

      *    MOVE SUMMARY-SPOOL TO PRU-FILE.
      *    PERFORM OPEN-PR-FILE-EXTEND.
      *    IF IO-FG NOT = 0
      *       GO TO END-INIT.

      * THIS SETS UP THE FIRST 32 BYTES OF LOG PATH
           MOVE EX-SPOOL TO LOG-SPOOL-DIR.

      * CREATE STEP EO/APIMMDDYY/0000LOG FOR ERRORS
      *      2023/08/18 01:04 PM 0010 078674 BEGIN SINGLE BATCH PAYMENT POSTING
      * PASS 2023/08/18 01:04 PM 0010 078674 SUCCESSFUL UPDATE
      *      2023/08/18 01:04 PM 0010 033333 BEGIN SINGLE BATCH PAYMENT POSTING
      * FAIL 2023/08/18 01:04 PM 0010 033333 ACCOUNT NOT ON FILE, ABORTED

           MOVE "BEGIN SINGLE BATCH PAYMENT POSTING" TO LOG-MSG.
           PERFORM CREATE-LOG.

           PERFORM OPEN-BR-FILE.
           PERFORM OPEN-GI1-FILE.
           PERFORM OPEN-CD1-FILE.
      * MUST LEAVE SP1-FILE OPEN BECAUSE ADDONSPR READS IT
           PERFORM OPEN-SP1-FILE.

           MOVE BATCH-REFCD TO LP-REFNO.

           MOVE 0 TO HOLD-OVPAID-CHECK.

           GO TO EXIT-INITIALIZE.
       END-INIT.
           MOVE 1 TO ERRCD.
       EXIT-INITIALIZE.
           EXIT.

      ******************************************************************
