      ****************************************************************
      *  NOTE:
      *        IF ELREAD.C DETECTS AN INVALID CODE
      *        DUE TO THE OPTION NOT BEENING PURCHASED
      *        AND FX/ELCLR.C NOT HAVING BEEN RUN,
      *
      *        THE SPR FIELDS:
      *          SP-LC-INFO & SP-LCUNITPER-CD  ARE NOT CHANGED
      *        AND
      *          SP-LC-CODE WILL BE SET TO 0 CAUSING NO LATE CHARGES
      *
      ****************************************************************
       LATE-CHARGE-TEST-ELREAD SECTION.
           IF LN-LC-CODE NOT = SP-LC-CODE
              MOVE LN-LC-CODE TO SP-LC-CODE
              MOVE "CL/ELREAD" TO FORM-NAM
              CALL FORM-PROGX USING SP-LC-INFO SP-LCUNITPER-CD
              CANCEL FORM-PROGX.

      *================================================================*
      * END COPYBOOK: LIBLP\LPLCHG.CPY                                *
      *================================================================*
      *================================================================*
      * EMBEDDED COPYBOOK: LIBLP\LPLCAP.CPY                           *
      *================================================================*
      * COPYMEMBER: LIBLP/LPLCAP
      ******************************************************************
      *          LATE CHARGE APPLY ROUTINE
      *
      *   NAME:  LPLCAP
      *   DESC:  PROVIDED WITH 1ST PAYDATE AND A CURRENT PAYMENT
      *          AND TRANSACTION DATE, DETERMINE HOW MUCH
      *          REPRESENTS LATE CHG (LCAP-APP) OR DEFICENCY TO
      *          COVER LATE CHG (LCAP-OWE), AND PROVIDE AN UPDATED
      *          LATE CHG PAID THRU DATE (LCAP-LPPDTH).
      *
      *          WHEN LCAP-LPTRCD = "AL", ALL POSSIBLE LATE CHARGES
      *          ARE ASSESSED, THUS A LCAP-TRAMT LARGE ENOUGH TO
      *          CONSUME ALL LATE CHARGES DUE IS DEFAULTED.
      *
      *   IN  :  LCAP-TRAMT              (LP-TRAMT)
      *          LCAP-1STPYDATE          (LN-1STPYDATE)
      *          LCAP-PAYDATE            (LP-PAYDATE)
      *          LCAP-LPTRCD             (LP-TRCD)  ** ONLY NEED FOR "AL" **
      *          LCAP-LPAPLC             (LP-APLC)
      *          LCAP-LPAPINT            (LP-APINT)
      *          LCAP-POFF-LPTRCD        (POFF-LPTRCD) ONLY NEED FOR PAYOFFS
      *          LCAP-BATCH-REFCD        (SET FOR BATCH REFCD PAYMENTS)
      *          LCAP-BATCH-REFCD-LC-FG  (SET FOR BATCH REFCD PAYMENTS)
      *
      *   OUT :  LCAP-OWE
      *          LCAP-APP
      *          LCAP-LCPDTH-DATE
      *          LCAP-PARTIALS
      *          LCAP-LCPAID
      *          LCAP-NOLCHG
      *
      *   USED:  LN-TOTPAYMNTD, LN-LCPAID, LN-REGPYAMT, LN-1STPYAMT,
      *          LN-TOTNODEF, LN-LCPDTH-DATE, LN-PARTIALS
      *          SP-LCFRMLA, SP-YEARTYPE
      *   COPY:  LPLCAPW, SPPDTHW, LPLCAS, LPLCASW, INCRMM, DATEWK
      *          LPNDTEW, LPNDTE, LPLCHGW, LPLCHG, LPMDTEW, LPMDTE
      *          JULW, TIMW, JUL
      * REV :
      *  010787 JTG ADDED ROUTINE (LATE-CHARGE-AL-CHECK)
      *             TO STOP ADVANCING PAID THRU AT MMYY
      *             LESS THAN ACCESSMENT DATE.
      *  060287 JTG ADDED LOGIC FOR FORMULA "D"
      *  101287 AMW ADDED GENERIC ROUTINE FOR "E"
      *  112487 JTG CORRECTED BUG IN "D", FOR "AL" TRCD
      *  121687 JTG ADDED LOGIC TO TEST ALLOTMENT
      *              CONDITIONS FOR NO LATE CHARGES
      *  122187 JTG REMOVED FORCED 0% TO SP-LCDELFAC
      *  012588 JTG CORRECTED FORMULA E TO NOT TAKE LATE
      *             CHARGES UNTIL CONTRACTUAL DOLLARS
      *             CATCHES UP WITH LPPDTH.
      *             ALSO; CORRECTED ROUTINE TO EVALULATE
      *             WHETHER PAYMENT IS LATE TO USE STATE
      *             PARAMETER LATE CHARGE YEARTYPE
      *             SP-LCYRTYPE.
      *  022588 JTG CORRECTED BUG IN COMPUTATION OF
      *             PAID THRU PAYMENTS.
      *  052088 BAW ADDED LCAP-LPTRCD FOR "AL" INSTEAD OF
      *             CHANGING THE VALUE OF LCAP-LPTRCD
      *             ADDED LCAP-LPAPLC FOR INPUT
      *  053188 JTG ADDED LOGIC FOR FORMULA "G"
      *  061588 JTG CORRECTED FORMULA "F" TO NOT USE
      *             LP-TRAMT, BUT LCAP-TRAMT.
      *  081188 JTG CORRECTED BUG FOR FORMULA "E", IN
      *             COMPUTATION OF LCAP-PDTH-PAYMENTS
      *  040389 JTG CORRECTED BUG IN FORMULA "D" & "G", WHEN
      *             LATE CHARGES ARE PAID AHEAD OF PDTH
      *             AMOUNT NEEDED SHOULD BE FULL PAYMENT
      *  051889 JTG CHANGED ROUTINES FOR CONTRACTUAL PAYMENTS
      *             TOWARD PDTH TO BE INDEPENDENT OF LC FORMULA
      *             CONTRACTUAL REQUIREMENTS
      *  042390 BAH ADDED LCAP-WRK2 TO REPLACE ALL (X+Y) > Z TYPE IF'S
      *  051790 BAH REPLACE LCPAID WITH TOTLCHG FOR LCFRMLA'S "B" "G"
      *  061290 JTG ADDED LOGIC FOR LCFRMLA = "H" & "I"
      *  072490 JTG ADDED REQUIREMENT TO SEND AMOUNTS APPLIED TO INTEREST
      *             AND AMOUNTS APPLIED TO LATE CHARGES
      *  080190 JTG CORRECTED "I", DON'T USE AMT-NEEDED IF PAID THRU
      *             IS PRIOR TO CURRENT PERIOD
      *  091390 SLC ADDED LOGIC FOR MULLEN LATE CHARGES USING
      *             THE PAYMENT SCHEDULES. FORMULA D ONLY!!
      *  120590 JTG CORRECTED LCAP-A FOR USING ELAPSED-DAYS FROM LPLCAS
      *  121290 JTG FIXED LCAP-I-L, RE: FULL LATE CHG FOR WHOLE DUE PERIODS
      *  121890 JTG CORRECTED ALL FORMULAS TO CONSIDER INTEREST OWING
      *  050892 JTG ALLOWED LCAP-G TO WORK WITH PAY SCHEDULE
      *  060592 JTG ADDED LOGIC FOR LN-LC-CODE (ROSE SHANIS)
      *  061992 JTG ADDED MORE SETS OF LCHG-CURPAY FOR SP-LCTYPE = "M"
      *                    SP-LCFRMLA 'D' OR 'G' ONLY
      *  071092 JTG CORRECTED LCAP-G RE: LATE CHARGES PAID IN EXCESS
      *             OF SCHEDULED PAYMENT, CAUSING NO ASSESS
      *  100692 JTG ADDED LOGIC FOR FORMULA "J" AND "K"
      *             NOTE:
      *                   "B" == "J" (USES LCPAID)
      *                   "G" == "K" (USES LCPAID)
      *  020393 JTG CHANGED TO WORK FOR LT-PAY-SCHLD-TBL (17)
      *  030393 JTG CORRECTED LCAP-B-J TO ADVANCE LCPDTH ON WHEN
      *             THE AMOUNT NEEDED IS RECEIVED
      *  040893 JTG ADDED MORE SETS OF LCHG-CURPAY FOR SP-LCTYPE = "M"
      *                     FOR SP-LCFRMLA 'B' OR 'J'
      *  070695 JTG ADDED SP-LCFRMLA 'L', ALMOST 'I', MERCURY 'UCCC'
      *  082595 JTG ADDED SP-LCFRMLA 'M', MERCURY 'LA'
      *  112995 JTG ADDED SP-LCFRMLA 'N', MERCURY 'NV'
      *  071696 JTG ADDED LOGIC FOR UNIT PERIODS
      *  080696 BAH FIXED BUG USING ELAPSED-MONTHS INSTEAD OF ELAPSED-UNITPER
      *  103096 JTG CHANGED TEST ON LN-LC-CODEX TO TEST FOR "00", WHICH
      *             SHOULD ELIMINATE UNNECESSARY IO ON EL-FILE
      *  112297 JFF ADDED LOGIC FOR SCHEDULE PAYMENTS IN LCAP-I-L
      *  120696 JTG CORRECTED BUG LCAP-I, LCAP-I-CURRENT-PERIOD-NEWCUR
      *             INDEX OUT OF BOUNDS
      *  022597 JTG CORRECTED LCAP-I-L, ASSESSING LATE CHARGES ON
      *             CURRECT ACCOUNTS
      *  041097 JTG CHG TO TEST SP-EXPR-FRMLA-CONT & NOT SP-EXPR-FRMLA = " "
      *  050997 JTG ADDED LOGIC TO LCAP-F FOR PAYMENT SCHEDULES
      *  053097 JTG FIXED LCAP-E, WAS ADVANCING LCPDTH 1 TO MANY TIMES
      *  071597 JTG CORRECTED LCAP-F RE: PAYMENT SCHEDULES, ADVANCE
      *  060898 JTG CORRECTED LCAP-I-L TO STOP ADVANCING LCPDTH UNNECESSARLY
      *             RE: WORLD #JG001
      *  101498 BAH CORRECTED GENERIC-LCAP-BYPASS-CHG, LCAP-LCPDTH-DATE WAS
      *             NOT FORCING 1STPYDA INTO LCPDTH, SEE COMMENTS BELOW.
      *  101498 BAH CORRECTED LCAP-A-C ROUTINE, WAS MOVING 4 DIGIT PDTH-DATE
      *             TO LCAP-LCPDTH-DATE INSTEAD OF PDTH-DATE-FULL, REGENCY (PA)
      *  101598 JTG ADDED LOGIC FOR LCFRMLA = 'R', REVOLVING REGENCY
      *             WHICH BE COMPUTED IN LONPFC.C AND RVSTUP.C
      *  030399 GLF ADDED SET OF LCHG-DAYS-AFTER-DUE, MULLEN #804
      *  990323 JTG ADDED LOGIC FOR BR-LATECHG-ON-ALLOTMENTS, TFC #018
      *  990402 JTG CORRECTED LATE CHARGE ASSESS FOR 'B' & 'J'
      *  990402 JTG REMOVED ATTEMPT TO CORRECTED LATE CHARGE ASSESS FOR 'B'&'J'
      *  990422 JTG CHANGED TO ASSESS A LATE CHARGE EVEN IF ACCOUNT
      *             IS PAID AHEAD EX. LN-AGEING-AMT(1) < 0
      *  JTG 990423 CHANGED TO ASSESS A LATE CHARGE ON CURRENT CHARGES
      *             AND PAST DUE CHARGES
      *  JTG 990812 ADDED LOGIC FOR SP-LCFRMLA = J TO NOT CONSIDER PREVIOUS
      *             PAID LATE CHARGES                                    KEARNEY
      *  JTG 990826 ADDED SCCS-COPY-ROUTINE
      *  JTG 990930 CHANGED LCAP-F TO SET PMT-TO-DATE TEMP TO INCLUDE APPLIED
      *             TO INTEREST, CITIZENS FINANCE:
      *  991102 JTG CHANGED LOGIC TO TEST ALLOTMENT CONDITIONS FOR NO LATE
      *             CHARGE AND ALLOW A LATE CHARGE ON PAYMENTS OTHER THAN 'PA'
      *             CFSC - CINDY
      *  991103 JTG CHANGED LCAP-G-K TO TRULY MAKE LCFRMLA 'K' NOT CONSIDER
      *             PRIOR LATE CHARGES PAID VIA LCPAID, CITIZENS (TN) - JUDY
      *  JTG 991217 CHANGED LOGIC FOR LCFRMLA = 'R', REVOLVING REGENCY
      *             TO ONLY TEST MONTH AND YEAR, SINCE PAYMENT DUE DAY CAN
      *             CHANGE MONTH TO MONTH, WHEN SEEING IF LATE CHARGE WAS
      *             ASSESED SINCE LAST STATEMENT
      *  JTG 000111 ADDED LCAP-NOLCHG  WORLD #218
      *             TO TRACK THE NUMBER OF LATE CHARGES ASSESSED
      *  JTG 000203 CORRECTED LOGIC FOR SP-LCFRMLA = J TO NOT CONSIDER PREVIOUS
      *             PAID LATE CHARGES AND TO CORRECTLY CONSIDER INTESEST PAID
      *             FROM OWING (IB ACCOUNTS)     KEARNEY, REGENCY BR:121 #500157
      *  JTG 000724 ADDED LOGIC FOR LCFRMLA = "H"  RE: TOTAL MONIES REGMGM #1262
      *  JTG 000822 ADDED LOGIC FOR KENTUCKY 60 DAY NO CHARGE LAW, ADDED
      *             SP-RBSPOPT1() = 19, WORLD #233
      *  JTG 000829 CORRECTED LCAP-G-K BUG, TO MAKE LCFRMLA 'K' CONSIDER THE SPR
      *             LATE CHARGE DELINQUENCY FACTOR%    REGENCY #294  (TN) - DIRK
      *  MJD 000911 ADDED TEST OF FOR LOCK BOX ACCOUNTS (MFC PR#227)
      *  JTG 001006 CHANGED LCAP-I-L TO NOT SET LCAP-CURDUE AMOUNT WHEN IT
      *             IS LESS THAN THE DELINQUENCY FACTOR, THIS WILL ALLOW
      *             THE NEXT PAYMENT IF POSTED TO LATE TO TAKE A LATE CHARGE
      *             ACE FINANCIAL PR#297
      *  JTG 001009 CHANGED LCAP-M TO NOT SET LCAP-CURDUE AMOUNT WHEN IT
      *             IS LESS THAN THE DELINQUENCY FACTOR, THIS WILL ALLOW
      *             THE NEXT PAYMENT IF POSTED TO LATE TO TAKE A LATE CHARGE
      *             ACE FINANCIAL PR#297
      *  JTG 010130 ADDED LOGIC TO ALLOW TEST FOR LOCK BOX OR ALLOTMENT ACCOUNTS
      *             THAT WERE POSTED IN LONPW5.C OR LONPW6.C AS "PO"
      *                                                           MERCURY PR#239
      *  JTG 010209 CHANGED NAME "GENERIC-LCAP" TO "LCAP-E"
      *             ADDED LCAP-TRAMT-PLUS-AP, IDEAL PR#315 LCAP-E
      *  JTG 010212 REWRITE LCAP-E LOGIC BY TAKING LCAP-B-J AND LETTING IT
      *             WORK FOR TOTAL MONIES,    IDEAL PR#315
      *  JTG 010212 MODIFIED LCAP-B-J, LCAP-E AND LCAP-N ROUTINES TO TEST 'AL'
      *             AND STOP ASSESSING WHEN THERE IS NO ASSESSMENT
      *  JTG 010326 MODIFIED LCAP-A-C ROUTINE TO TEST 'AL' AND STOP
      *             ASSESSING WHEN THERE IS NO ASSESSMENT
      *  JTG 010625 CREATED LCAP-X (BAD LOGIC) BY PUTTING BACK THE OLD LOGIC
      *             FOR LCAP-E                                     IDEAL PR#1509
      *  JTG 010627 ADDED LOGIC IN EXIT ROUTINE OF ALL FORMULAS TO ASSURE
      *             LCAP-LCPDTH-DATE HAD A VALID DAY IF ACCOUNT IS MONTHLY
      *                                                            IDEAL PR#1509
      *  JTG 010629 REMOVED LCAP-X (BAD LOGIC) AND ADDED LCAP-E-X  IDEAL PR#1509
      *             AND CHANGED TO SUBTRACT LCHG-CHARGE FROM LCAP-AMTNEEDED
      *  JTG 010731 CHANGED LCAP-E-X FOR ANOTHER ATTEMPT TO MAKE 'X'
      *             WORK LIKE DIANE AT IDEAL WANTS. AFTER A FULL
      *             PAYMENT IS SATISFIED AND THE NEXT PAYMENT IS LATE AND
      *             DUE A LATE CHARGE, IF THERE IS NOT ENOUGH MONIES TO APPLY
      *             TOWARDS THE FULL LATE CHARGE TAKE IT ANYWAY FROM MONIES
      *             APPLIED TO SATISFY THE PREVIOUS SHORTAGE       IDEAL PR#1509
      *  JTG 020404 INSURED THAT ACCELERATED ACCOUNTS WILL NOT COMPUTE/TAKE
      *             LATE CHARGES
      *             RE: ALLOWED IB TYPE LOANS TO ACCELERATE JIM R. (ALL) PR#1582
      *  JTG-CS     WHEN SEMI MONTHLY WITH FIRST PAYDATE OF 14TH OR 15TH,
      *      020913 LCPDTH WILL GO TO 02/28/YY OR 02/29/YY WHEN LCPDTH
      *             WAS UPDATED FROM 02/14/YY OR 02/15/YY. THE FOLLOWING
      *             LOGIC RE-ESTABLISHES CYCLES BACK TO THE 14TH OR 15TH.
      *  JTG 021219 ADDED NEW CODE FILE TYPE 'BR' -BATCH PAYMENT REFERENCE CODES
      *             BATCH PAYMENT REVISIONS                         REGACC #0006
      *  BAH 030507 ADDED NEW BRANCH FLAG TO STOP ASSESSING LATE CHARGES FOR
      *             THE ENTIRE BRANCH..THEY MUST SET IT = "N", OTHERWISE IT
      *             WILL CONTINUE TO CHARGE LATE CHARGES...MODERN PR# 2036
      *  JTG 030528 ADDED SP-LCFRMLA = 'P' LIKE 'I'                  PACE #408
      *  JTG 030519 ADDED LOGIC TO LCAP-B-J TO CORRECTLY HANDLE
      *             IB ACCOUNTS WHERE MONEY IS APPLIED TO INTEREST  REGENCY #403
      *  BAH 030620 ADDED TEST FOR GP-I-AM-MODERN TO THE BR-ASSESS-LATE-CHGS
      *             RE USED A BR FLAG THAT MUST OF HAD A "N" IN IT...
      *  BAH 030814 LCAP-A-C WAS MISSING MOVE TO LCHG-LATE FOR FORMULA C,
      *             CAUSING NO LATE CHARGE BUT EVERYTHING ADVANCED AND ACTED
      *             AS IF IT TOOK A LATE CHARGE, BUT IT DIDNT CAUSE THIS FIELD
      *             WAS 0, DAVID (BAY FINANCE)
      *  040401 BAH ADDED SP-LC-ON-JUDGEMENTS FOR RIVERSIDE, PR# 2272, STATE
      *             LAW SAYS NO LATE CHARGES ON JUDGEMENT ACCOUNTS
      *  040405 BAH PACESETTER "I" WAS STILL USING 4 DIGIT PDTH....CHANGED
      *             PDTH-DATE TO PDTH-DATE-FULL
      *  040708 JTG CORRECTED LIBLP/LPLCAP, LCAP-A-C TO NOT GO INTO A
      *             NEVER ENDING LOOP WHEN OERATOR POSTS A PAYMENT
      *             IN EXCESS OF LOAN'S BALANCE                    REGENCY #J047
      *  051206JG&CS ACCOUNTS WITH LCPDTH OF 2/28 DID NOT ADVANCE LCPDTH
      *             CORRECTLY IF 1STPYDA > 28 FOR MARCH.  ON SEMI MONTHLY WITH
      *             DUE DATES OF 14 OR 15 OR 30, IT CHANGED THE CYCLE DATES
      *             CAUSING LATE CHARGES ON SUBSEQUENT PMTS PR#502 TRITON
      *  100211CS   FIXED LCAP-CALC-PDTH-ADDON SECTION.  WAS MOVING PDTH-DATE-
      *             FULL TO NDTE-DATE, INCREMENTING UNITPER, AND THEN MOVING
      *             IN THE FIRST PAY DAY. THIS WAS CAUSING A PROBLEM BECAUSE
      *             IT CAUSED PDTH-DATE-FULL IN FEB IF FIRST DUE DAY WAS 29,
      *             30,OR 31, BECAUSE IT MADE PDTH-DATE-FULL = 02/31/09.  THIS
      *             LATER GOT TESTED IN LCAP-B-J & BECAUSE LCAP-LCPDTH-DATE WAS 2/28
      *             THEY WERE NOT EQUAL & LCPDTH WAS NOT ADVANCED PR#675
      *  100309 BLM BARB & CINDY, FIX FORMULA E & X FOR PAYMENT SCHEDULES.
      *             IN LCAP-E-X-PMT IT WAS MOVING REGPAY TO LCAP-AMTNEEDED
      *             INSTEAD OF SCHEDULED AMOUNT, REGWAN PR# 3506
      *  100309 BLM BARB & CINDY, FIX FORMULA B & J FOR PAYMENT SCHEDULES.
      *             IT WAS MOVING REGPAY TO LCAP-AMTNEEDED
      *             INSTEAD OF SCHEDULED AMOUNT, REGWAN PR# 3506
      *  100309  CS  WHEN WE FIXED B/J/E/X TO WORK WITH PAYMENT SCHEDULES WE
      *              MISSED AN ADD TO LCAP-PMT-NO AFTER SATISFYING ANY SHORTAGE       *              FROM PRIOR PAYMENTS. RAN IN TO THIS WHEN WE WERE ON THE
      *              LAST PAYMENT IN A LEVEL OF SCHEDULE WITH A SHORTAGE, IT
      *              COVERED THE SHORTAGE, BUT THEN STILL THOUGHT YOU WERE ON
      *              THE SAME PAYMENT.  ADDED THIS TEST IN LPCAP-B-J-PMT, LCAP-
      *              E-X-PMT: IF LCAP-AMTNEEDED < LCAP-TRAMT, AFTER SUBTRACT
      *              OF LCAP-AMTNEEDED, IF LN-PAY-SCHLD-FG = "Y", ADD 1 TO
      *              LCAP-PMT-NO. REGWAN PR# 3506
      *  100330 BLM  BARB & CINDY, WHEN CHECKING TO SEE IF TRAMT IS ENOUGH TO
      *              COVER LATE-CHARGE (LCHG-CHARGE), NEED TO SUBTRACT ESCROW
      *              AMT FROM TRAMT IF ACCOUNT HAS ESCROW.  WE ADD ESCROW AMT
      *              BACK IN TO LCAP-TRAMT TO MAKE SURE IT COMPUTES AMT
      *              NEEDED CORRECTLY, BUT FOR EXAMPLE, IF THE ENTIRE TRAMT
      *              IS PUT TO ESCROW, THERE IS NOTHING LEFT TO APPLY TO
      *              LATE CHARGE AND IT WILL GO NEGATIVE!  REGWAN PR# 3506
      *  100813CS    FIXED LCAP-I-L-NOASSESS NOT TO INCLUDE LCAP-LPAPINT IN
      *              COMPUTE OF LCAP-WRK, SEE EXPLANATION AT TOP OF LCAP-I-L-
      *              NO-ASSESS  PL694
      *  110105CS    ATTEMPT TO FIX "H" TO USE SP-DELFAC. THIS CODE IS SUPPOSED
      *              TO ACT LIKE 'F' BUT KEVIN/JIM SAID IT NEEDED TO CONSIDER.        *              ORIG SAVE AS LPLCAP.110105  REGACC #279
      *  110215 MJD  ADDED LOGIC FOR SP-LCFRMLA = "S"  SIMILAR TO "F" WORLD #723
      *                ******** CHANGES STILL IN PROGRESS *******
      *  120730  CS  IF SP-LC-INT-ON-REPO-NON-PL = "N", DONT ASSESS LATE CHG
      *                                                   REGACC PR#314
      *  160113 BAH SPLIT OUT LTFILE, LTPFILE, RENAMED LT- LTP- PD0003
      *  160615 BLM FIX LCAP-R TO CALL GETLTR SINCE REVOLVING FIELDS ARE IN
      *             LTRFILE, NOT LNFILE, PD0003
      * KEC 2016.1116 {PD#00003} PARADATA <A30> [JAY CISZEWSKI]
      *         ADDED LTR-SEQNO TO LTR1-KEY.
      * BLM 170309 CHANGE COMPARE OF PDTH-WK-YR TO USE PDTH-WK-CCYY, PD0006
      * BAH 170403 LCAP-LCPAID CAN BE A DATE AND MUST STAY MMDDYY BECAUSE
      *            WE CAN NOT DECIPHER WHICH ONES ARE DATES AND WHICH ARE AMTS
      *            WHEN UPGRADING THE LOAN FILE AND PAYMENT FILE! SO WE CANT
      *            CHANGE THE WAY THE DATE WAS FORMATTED IN A15
      * KEC 20190219 REMOVED REDEFINE FOR LN-LC-CODEX; UNUSED
      * BAH 20190625 REMOVED LN-REVOLVING, PT0153 LCFRMLA "R"
      * BAH 20220121 COMMENTED OUT INDIVIDUAL MOVES OF LCAP-CURDATE-MM,-YY
      *              ADDED MOVE LCAP-CURDATE TO LCAS-LCPDTH-DATE.
      *              CINDY FOUND WHILE TESTING
      * BAH 20230328 ADDED SP-LCFRMLA "T" FOR "WI" #1597
      **************************************************************************
