       LCAP-S-BEGIN.
      * TEST IF LATE CHARGE PAID THRU (LCAP-LCPDTH) IS
      * ON OR AFTER MATURITY, IF SO EXIT:
           PERFORM LCAP-MDTE-CHK.
           IF ELAPSED-DAYS NOT > 0
              GO TO LCAP-S-EXIT.

      * IS PAYMENT ON OF AFTER MATURITY+GRACE?
      *    IS THE LCPDTH GREATER THEN THE 2ND TO LST PAYDATE?
      *       IS THE PAYMENT MADE AFTER THE GRACE PERIOD?
      *          THEN ADVANCE LCPDTH TO MAT DATE AND DO NOT CHARGE LC
      
           MOVE MDTE-DATE TO NDTE-DATE.
           MOVE SP-LCGRACE TO NDTE-HOLD.
           PERFORM INCREMENT-DAYS.
           IF LCAP-PAYDATE > NDTE-DATE
              MOVE MDTE-DATE TO NDTE-DATE
              MOVE LN-UNITPER-CD TO DATER-UNITPER-CD
              MOVE LN-UNITPER-FREQ TO DATER-UNITPER-FREQ
              MOVE -1 TO NDTE-HOLD
              PERFORM INCREMENT-UNITPER
              IF LCAP-LCPDTH-DATE NOT < NDTE-DATE
                 MOVE MDTE-DATE TO LCAP-LCPDTH-DATE
                 GO TO LCAP-S-EXIT.

      * ASSESSING LATE CHARGES? (AL)
      * IF SO, STOP ASSESSING WHEN LATE CHARGES ARE BROUGHT
      * UP TODATE, WHEN LATE CHARGE PAID THRU (LCAP-LCPDTH)
      * IS ON OR AFTER PAYDATE:
           IF LCAP-LPTRCD = "AL"
              MOVE LCAP-PAYDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS NOT > 0
                 GO TO LCAP-S-EXIT
              ELSE
                 MOVE 0 TO LCAP-CURDATE
                           LCAP-CURDUE.

      * DOES PAYMENT AND LCPDTH INDICATE AN ASSESSMENT ?
           PERFORM LCAP-ASSESS-CHK.
           IF LCAS-ASSESS NOT = "Y"
              GO TO LCAP-S-NOASSESS.

      * TEST FOR AMTNEEDED LESS THAN THE DELINQUINCY FACTOR
      * IN (SPR'S), IF SO ASSESS NO LATE CHARGE:
      * TEST FOR LAST CURRENT PAYMENT:
           IF LCAP-LST-CURDATE NOT = 0
              MOVE LCAP-LST-CURDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS = 0
                 MOVE LCAP-LST-CURDUE TO LCAP-AMTNEEDED
                 IF LCAP-LST-CURDUE < LCAP-DELFAC
                    GO TO LCAP-S-ADVANCE.

      * DETERMINE THE AMOUNT OF THE LATE CHARGE:
      * IF SP-LCTYPE = 'C', LCHG-LATE IS INITIALIZED,
      * SINCE LATE CHARGE IS BASED ON % OF AMOUNT DELINQUENT:
           MOVE LCAP-AMTNEEDED TO LCHG-LATE.
           MOVE LCAP-LCPDTH-DATE TO LCHG-LCPDTH-DATE.
           PERFORM LCAP-CALC-TEST.

      * IF LCAP-TRAMT IS NOT ENOUGH TO COVER CHARGE, USE OWING:
           IF LCAP-TRAMT < LCHG-CHARGE
              COMPUTE LCAP-OWE = LCAP-OWE +
                                  (LCHG-CHARGE - LCAP-TRAMT)
              ADD LCAP-TRAMT TO LCAP-APP
              MOVE 0 TO LCAP-TRAMT
           ELSE
              ADD LCHG-CHARGE TO LCAP-APP
              SUBTRACT LCHG-CHARGE FROM LCAP-TRAMT.

