      **************************************************************
      *   SP-LCFRML = M   LA LATE CHARGE FORMULA
      *
      *   NOTE:
      *        LCAP-PARTIALS (HOLDS LCAP-CURDUE AT EXIT)
      *        LCAP-LCPAID   (HOLDS LCAP-CURDATE (MMDD.YY) AT EXIT)
      **************************************************************
       LCAP-M SECTION.
           MOVE LCAP-TOTPAYMNTD TO LCAP-PAYMNTD.
           MOVE LCAP-PARTIALS TO LCAP-LST-CURDUE.
      * REARRANGE LAST PAYDATE (MMDD.YY) INTO (MMDDYY):
           MULTIPLY LCAP-LCPAID BY 100 GIVING DATE-MMDDYY.
           PERFORM CONVERT-MMDDYY-TO-YYYYMMDD.
           MOVE DATE-YYYYMMDD TO LCAP-CURDATE
                                 LCAP-LST-CURDATE.

           ADD LN-TOTLCHG LCAP-LPAPLC LCAP-LPAPINT GIVING LCAP-WRK.
           IF LCAP-WRK < LCAP-AMTNEEDED
              SUBTRACT LCAP-WRK FROM LCAP-AMTNEEDED.

      * SEE IF CONTRACTUAL PAID THRU IS LESS THAN LCPDTH,
      * IF SO SET AMTNEEDED TO REGULAR PAYMENT:
           MOVE LCAP-TOTPAYMNTD TO LCAP-WRK.
           COMPUTE PDTH-PAYMNTD LCAP-TOTPAYMNTD =
                             LCAP-TOTPAYMNTD + LN-TOTLCHG.
           PERFORM LCAP-CALC-PDTH.

           MOVE LN-REGPYAMT TO LCAP-UNPAID-PORTION.
           IF LCAP-TOTPAYMNTD < LN-1STPYAMT
              MOVE LN-1STPYAMT TO LCAP-UNPAID-PORTION.
           COMPUTE LCAP-UNPAID-PORTION ROUNDED =
              PDTH-REMAIN * LCAP-UNPAID-PORTION.

           IF LCAP-UNPAID-PORTION < LN-TOTLCHG
              MOVE LN-REGPYAMT TO LCAP-AMTNEEDED
              IF LCAP-TOTPAYMNTD < LN-1STPYAMT
                 MOVE LN-1STPYAMT TO LCAP-AMTNEEDED
              END-IF
              SUBTRACT LCAP-UNPAID-PORTION FROM LCAP-AMTNEEDED.
           MOVE LCAP-WRK TO LCAP-TOTPAYMNTD.

           IF LCAP-LST-CURDATE = 0
                     OR (LCAP-LST-CURDATE NOT = 0
                               AND LCAP-LST-CURDUE = 0)
              MOVE PDTH-DATE-FULL TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS < 0
                 MOVE LN-REGPYAMT TO LCAP-AMTNEEDED.

      * SETUP CURRENT PAYMENT AND LAST CURRENT PAYMENT,
      * SEE IF CURRENT PAYMENT IS ON TIME:
           PERFORM LCAP-M-CURRENT-PERIOD.

       LCAP-M-BEGIN.
      * ASSESSING LATE CHARGES? (AL)
      * IF SO, STOP ASSESSING WHEN LATE CHARGES ARE BROUGHT
      * UP TODATE, WHEN LATE CHARGE PAID THRU (LCAP-LCPDTH)
      * IS ON OR AFTER PAYDATE:
           IF LCAP-LPTRCD = "AL"
              MOVE LCAP-PAYDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS NOT > 0
                 GO TO LCAP-M-EXIT
              ELSE
                 MOVE 0 TO LCAP-CURDATE
                           LCAP-CURDUE.

      * DOES PAYMENT AND LCPDTH INDICATE AN ASSESSMENT ?
           PERFORM LCAP-ASSESS-CHK.
           IF LCAS-ASSESS NOT = "Y"
              GO TO LCAP-M-NOASSESS.

      * TEST FOR LAST CURRENT PAYMENT:
           IF LCAP-LST-CURDATE NOT = 0
              MOVE LCAP-LST-CURDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS = 0
                 MOVE LCAP-LST-CURDATE TO NUM-DATE
                 MOVE PDTH-DATE-FULL   TO SYS-DATE
                 PERFORM TIM
                 IF ELAPSED-DAYS < 0
                    MOVE LCAP-LST-CURDUE TO LCAP-AMTNEEDED
                 ELSE
                    IF LCAP-AMTNEEDED > LCAP-LST-CURDUE
                       MOVE LCAP-LST-CURDUE TO LCAP-AMTNEEDED.

      * TEST FOR AMTNEEDED LESS THAN THE DELINQUINCY FACTOR
      * IN (SPR'S), IF SO ASSESS NO LATE CHARGE:
           IF LCAP-AMTNEEDED < LCAP-DELFAC
              GO TO LCAP-M-ADVANCE.

      * DETERMINE THE AMOUNT OF THE LATE CHARGE:
      * IF SP-LCTYPE = "C" OR "J", LCHG-LATE IS INITIALIZED,
      * SINCE LATE CHARGE IS BASED ON % OF AMOUNT DELINQUENT:
           MOVE LCAP-AMTNEEDED TO LCHG-LATE.
           MOVE LCAP-LCPDTH-DATE TO LCHG-LCPDTH-DATE.
           PERFORM LCAP-CALC-TEST.

      * IF LCAP-TRAMT IS NOT ENOUGH TO COVER CHARGE, USE OWING:
           IF LCAP-TRAMT < LCHG-CHARGE
              COMPUTE LCAP-OWE = LCAP-OWE +
                                  (LCHG-CHARGE - LCAP-TRAMT)
              ADD LCAP-TRAMT TO LCAP-APP
              MOVE 0 TO LCAP-TRAMT
           ELSE
              ADD LCHG-CHARGE TO LCAP-APP
              SUBTRACT LCHG-CHARGE FROM LCAP-TRAMT.

       LCAP-M-ADVANCE.
           PERFORM LCAP-UPD-LCPD.
           MOVE LN-REGPYAMT TO LCAP-AMTNEEDED.
           GO TO LCAP-M-BEGIN.

      *******************************************************
      * NO ASSESSMENT IS REQUIRED; ADVANCE LCAP-LCPDTH-DATE
      * TO WHERE PAYMENTS TODATE ARE PAID THRU, ONLY
      * IF IT WILL ADVANCE LCPDTH, SINCE LCPDTH COULD
      * HAVE ADVANCED BEYOND PAID THRU VIA TIME.
      *******************************************************
       LCAP-M-NOASSESS.
           IF LCAP-LPTRCD NOT = "AL"
              ADD LCAP-TRAMT LCAP-PAYMNTD GIVING PDTH-PAYMNTD.

           IF LCAP-LPTRCD NOT = "AL"
              ADD LN-TOTLCHG LCAP-LPAPLC LCAP-APP LCAP-LPAPINT
                                                 GIVING LCAP-WRK
              ADD LCAP-WRK TO PDTH-PAYMNTD
              COMPUTE PDTH-PAYMENTS = LCAP-WRK / LN-REGPYAMT
              IF PDTH-PAYMENTS > 1
                 COMPUTE PDTH-PAYMNTD =
                    PDTH-PAYMNTD - ( PDTH-PAYS * LN-REGPYAMT).

           IF LCAP-LPTRCD NOT = "AL"
              PERFORM LCAP-CALC-PDTH
              MOVE NDTE-DATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS NOT < 0
                 MOVE PDTH-DATE-FULL TO LCAP-LCPDTH-DATE
                 IF LCAP-UNPAID-PORTION NOT = 0
                          AND LCAP-UNPAID-PORTION < LCAP-DELFAC
                    PERFORM LCAP-UPD-LCPD.

      * INSURE THAT LCPDTH ADVANCES TO CURRENT PAYMENT DATE
      * IF  CURRENT  PAYMENT IS NOT DELIQUENT:
           IF LCAP-CURDATE NOT = 0
              MOVE LCAP-CURDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS > 0
                 IF LCAP-CURDUE < LCAP-DELFAC
                    IF ELAPSED-DAYS > 0
                       MOVE LCAP-CURDATE TO LCAP-LCPDTH-DATE
                    ELSE
                       PERFORM LCAP-UPD-LCPD.

       LCAP-M-EXIT.
           MOVE LCAP-CURDUE TO LCAP-PARTIALS.
      * REARRANGE DATE (MMDDYY) TO (MMDD.YY):
           MOVE LCAP-CURDATE TO DATE-YYYYMMDD.
           PERFORM CONVERT-YYYYMMDD-TO-MMDDYY.
           MULTIPLY DATE-MMDDYY BY 0.01 GIVING LCAP-LCPAID.

      ***********************************************
      *    TEST CURRENT PAYMENT ON TIME
      *
      *    IF SO, ESTABLISH WHETHER ITS A NEW PERIOD
      *    OR LAST PAYMENT PERIOD AND SETUP AMOUNTS
      *    DELIQUENT FOR LAST OR BOTH PERIODS.
      ***********************************************
