       LCAP-N-RETRY.
           IF LCAP-TRAMT > LCAP-AMTNEEDED
              PERFORM LCAP-UPD-LCPD
              GO TO LCAP-N-PMT.

      * TEST TO SEE IF THE SHORTAGE IS NOT GREATER
      * THAN THE DELINQUINCY FACTOR, SETUP IN STATE PARAMETERS.
      *
           COMPUTE LCAP-WRK2 = LCAP-AMTNEEDED - LCAP-TRAMT.
           IF LCAP-WRK2 < LCAP-DELFAC
              PERFORM LCAP-UPD-LCPD.

