      ***********************************************
      *    TEST CURRENT PAYMENT ON TIME
      *
      *    IF SO, ESTABLISH WHETHER ITS A NEW PERIOD
      *    OR LAST PAYMENT PERIOD AND SETUP AMOUNTS
      *    DELIQUENT FOR LAST OR BOTH PERIODS.
      ***********************************************
       LCAP-M-CURRENT-PERIOD SECTION.
           MOVE " " TO LCAP-PRIOR-1STPY.
           MOVE 0   TO LCAP-CURDUE.
           ADD LCAP-LPAPLC LCAP-LPAPINT TO LCAP-TRAMT.

      * IF PAYMENT IS BEFORE 1ST PAYMENT IS DUE,
      * FORCE CURRENT DUE DATE TO 1 MONTH PRIOR TO
      * FIRST PAYMENT DUE DATE:
           MOVE LCAP-PAYDATE TO LCAP-CURDATE
                                NUM-DATE.
           MOVE LCAP-1STPYDATE TO SYS-DATE.
           PERFORM TIM.
           IF ELAPSED-DAYS > 0
              MOVE "Y" TO LCAP-PRIOR-1STPY
              MOVE LCAP-1STPYDATE TO NDTE-DATE
              MOVE -1 TO NDTE-HOLD
              PERFORM INCREMENT-MONTHS
              MOVE NDTE-DATE TO LCAP-CURDATE
              GO TO LCAP-M-CURRENT-PERIOD-SETDUE.

      * IF TODAY IS ON OR AFTER PAYMENT DUE DATE OF THIS MONTH,
      *  SET UP THIS MONTHS DUE DATE TO SEE IF THE PAYMENT WAS ON TIME:
      * IF THE PAYMENT CAME IN BEFORE THIS MONTHS DUE DATE, SET UP
      *  LAST MONTHS DUE DATE TO SEE IF THE PAYMENT WAS ON TIME:
           IF LCAP-CURDATE-DD NOT < LCAP-1STPYDATE-DD
              MOVE -1 TO NDTE-HOLD
           ELSE
              MOVE -2 TO NDTE-HOLD.

           MOVE LCAP-1STPYDATE-DD TO LCAP-CURDATE-DD.
           MOVE LCAP-CURDATE TO NDTE-DATE.
           PERFORM INCREMENT-MONTHS.
           MOVE NDTE-DATE TO LCAP-CURDATE.

      * TEST TO SEE IF THE PAYMENT WAS MADE ON TIME:
           MOVE LCAP-CURDATE TO LCAS-LCPDTH-DATE.
           MOVE LCAP-1STPYDATE TO LCAS-1STPYDATE.
           MOVE LCAP-PAYDATE TO LCAS-PAYDATE.
           PERFORM LATE-ASSESS-ROUTINE.
           IF LCAS-ASSESS = "Y"
              MOVE 0 TO LCAP-CURDATE
              GO TO LCAP-M-CURRENT-PERIOD-EXIT.

      * PAYMENT WAS ON TIME, SO SET IT UP AS CURRENT PAYMENT:
           MOVE LCAP-CURDATE TO NDTE-DATE.
           MOVE 1 TO NDTE-HOLD.
           PERFORM INCREMENT-MONTHS.
           MOVE NDTE-DATE TO LCAP-CURDATE.

      * IF CURRENT PAYDATE IS THE SAME AS LAST CURRENT PAYDATE,
      * SET CURRENT PAYMENT DATE TO LAST CURRENT PAYMENT DATE,
      * MAKE CURRENT DUE EQUAL TO REDUCED LAST CURRENT DUE:
       LCAP-M-CURRENT-PERIOD-SETDUE.
           IF LCAP-CURDATE NOT = LCAP-LST-CURDATE
              GO TO LCAP-M-CURRENT-PERIOD-NEWCUR.
           MOVE LCAP-LST-CURDATE TO LCAP-CURDATE.
           IF LCAP-TRAMT < LCAP-LST-CURDUE
              SUBTRACT LCAP-TRAMT FROM LCAP-LST-CURDUE
                                        GIVING LCAP-CURDUE
           ELSE
              MOVE 0 TO LCAP-CURDUE.
           MOVE 0 TO LCAP-LST-CURDATE
                     LCAP-LST-CURDUE.
           GO TO LCAP-M-CURRENT-PERIOD-EXIT.

       LCAP-M-CURRENT-PERIOD-NEWCUR.
      * SET UP AMOUNT LATE CHARGES CAN STILL BE CALCULATED ON:
           MOVE LN-REGPYAMT TO LCAP-CURDUE.
           IF LN-1STPYAMT NOT = 0
              IF LCAP-CURDATE = LCAP-1STPYDATE
                 MOVE LN-1STPYAMT TO LCAP-CURDUE.

           IF LCAP-TRAMT < LCAP-CURDUE
              SUBTRACT LCAP-TRAMT FROM LCAP-CURDUE
              IF LCAP-CURDUE < LCAP-DELFAC
                 MOVE 0 TO LCAP-CURDUE
              END-IF
           ELSE
              MOVE 0 TO LCAP-CURDUE.

       LCAP-M-CURRENT-PERIOD-EXIT.
      * SET LAST CURRENT DATE BACK ONE MONTH TO ALLOW
      * COMPARISON WITH LCPDTH:
           IF LCAP-LST-CURDATE NOT = 0
              MOVE LCAP-LST-CURDATE TO NDTE-DATE
              MOVE -1 TO NDTE-HOLD
              PERFORM INCREMENT-MONTHS
              MOVE NDTE-DATE TO LCAP-LST-CURDATE.

           SUBTRACT LCAP-LPAPLC LCAP-LPAPINT FROM LCAP-TRAMT.

      ***********************************************
      *  SP-LCFRMLA = N   (MERCURY, NV)
      ***********************************************
