      * NO ASSESSMENT REQUIRED, ADVANCE LCAP-LCPDTH-DATE
      * TO WHERE PAYMENTS TODATE ARE PAID THRU
      * IF IT WILL ADVANCE LCPDTH ONLY, SINCE
      * ADVANCEMENT OF LCPDTH COULD HAVED OCCURED
      * VIA TIME.
       LCAP-D-NOASSESS.
           IF LCAP-LPTRCD NOT = "AL"
              ADD LCAP-TRAMT LCAP-PAYMNTD GIVING PDTH-PAYMNTD
                                                 LCAP-PAYMNTD
              PERFORM LCAP-PICK-PDTH-CALC
              MOVE NDTE-DATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS > 0
                 MOVE PDTH-DATE-FULL TO LCAP-LCPDTH-DATE.

      * ? PAST MATURITY
      * IF SO FORCE LCAP-LCPDTH-DATE TO MATURITY:
           PERFORM LCAP-MDTE-CHK.
           IF ELAPSED-DAYS NOT > 0
              MOVE MDTE-DATE TO LCAP-LCPDTH-DATE.

