      **************************************************************
      *   SP-LCFRML = I & L   INDIANA   LATE CHARGE FORMULA (PRIN ONLY)
      *
      *   NOTE:
      *        LCAP-PARTIALS (HOLDS LCAP-CURDUE AT EXIT)
      *        LCAP-LCPAID   (HOLDS LCAP-CURDATE [MMDD.YY] AT EXIT)
      **************************************************************
       LCAP-I-L SECTION.
           MOVE LCAP-TOTPAYMNTD TO LCAP-PAYMNTD.
           MOVE LCAP-PARTIALS TO LCAP-LST-CURDUE.
      * REARRANGE LAST PAYDATE (MMDD.YY) INTO (MMDDYY):
           MULTIPLY LCAP-LCPAID BY 100 GIVING DATE-MMDDYY.
           PERFORM CONVERT-MMDDYY-TO-YYYYMMDD.
           MOVE DATE-YYYYMMDD TO LCAP-CURDATE
                                 LCAP-LST-CURDATE.

           ADD LN-TOTLCHG LCAP-LPAPLC LCAP-LPAPINT GIVING LCAP-WRK.
           IF SP-LCFRMLA = "L"
              IF LCAP-WRK < LCAP-AMTNEEDED
                 SUBTRACT LCAP-WRK FROM LCAP-AMTNEEDED
              ELSE
                 NEXT SENTENCE
           ELSE
              IF LCAP-AMTNEEDED NOT = LCAP-UNPAID-PORTION
                 SUBTRACT LCAP-WRK FROM LCAP-AMTNEEDED.

      * SEE IF CONTRACTUAL PAID THRU IS LESS THAN LCPDTH,
      * IF SO SET AMTNEEDED TO REGULAR PAYMENT:

           MOVE LCAP-TOTPAYMNTD TO LCAP-WRK.
      
           COMPUTE PDTH-PAYMNTD
                   LCAP-TOTPAYMNTD = LCAP-TOTPAYMNTD + LN-TOTLCHG.

           IF LN-PAY-SCHLD-FG = "Y"
              MOVE LCAP-PAYMNTD TO LCAP-HOLDER
              MOVE PDTH-PAYMNTD TO LCAP-PAYMNTD
              PERFORM LCAP-PICK-PDTH-CALC
              MOVE LCAP-HOLDER TO LCAP-PAYMNTD
           ELSE
              PERFORM LCAP-PICK-PDTH-CALC.

           IF LN-PAY-SCHLD-FG = "Y"
              MOVE SCHD-AMT(LCAP-PMT-NO) TO LCAP-WRK2
              COMPUTE LCAP-WRK2 ROUNDED = LCAP-REMAIN * LCAP-WRK2
           ELSE
              MOVE LN-REGPYAMT TO LCAP-WRK2
              IF LCAP-TOTPAYMNTD < LN-1STPYAMT
                 MOVE LN-1STPYAMT TO LCAP-WRK2
              END-IF
              COMPUTE LCAP-WRK2 ROUNDED =
                      PDTH-REMAIN * LCAP-WRK2.

           IF LCAP-WRK2 < LN-TOTLCHG
              IF LN-PAY-SCHLD-FG = "Y"
                 MOVE SCHD-AMT(LCAP-PMT-NO) TO LCAP-AMTNEEDED
              ELSE
                 MOVE LN-REGPYAMT TO LCAP-AMTNEEDED
                 IF LCAP-TOTPAYMNTD < LN-1STPYAMT
                    MOVE LN-1STPYAMT TO LCAP-AMTNEEDED
                    IF SP-LCFRMLA = "L"
                       SUBTRACT LCAP-WRK2 FROM LCAP-AMTNEEDED
                    ELSE
                       NEXT SENTENCE
                 ELSE
                    IF SP-LCFRMLA = "L"
                       SUBTRACT LCAP-WRK2 FROM LCAP-AMTNEEDED.
           MOVE LCAP-WRK TO LCAP-TOTPAYMNTD.

           IF LCAP-LST-CURDATE = 0
                    OR (LCAP-LST-CURDATE NOT = 0
                               AND LCAP-LST-CURDUE = 0)
              MOVE PDTH-DATE-FULL TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS < 0
                 IF LN-PAY-SCHLD-FG = "Y"
                    MOVE SCHD-AMT(LCAP-PMT-NO) TO LCAP-AMTNEEDED
                 ELSE
                    MOVE LN-REGPYAMT TO LCAP-AMTNEEDED.

      * SETUP CURRENT PAYMENT AND LAST CURRENT PAYMENT,
      * SEE IF CURRENT PAYMENT IS ON TIME:
           PERFORM LCAP-I-L-CURRENT-PERIOD.

       LCAP-I-L-BEGIN.
      * TEST IF LATE CHARGE PAID THRU (LCAP-LCPDTH) IS
      * ON OR AFTER MATURITY, IF SO EXIT:
           PERFORM LCAP-MDTE-CHK.
           IF ELAPSED-DAYS NOT > 0
              GO TO LCAP-I-L-EXIT.

      * ASSESSING LATE CHARGES? (AL)
      * IF SO, STOP ASSESSING WHEN LATE CHARGES ARE BROUGHT UP TODATE,
      * WHEN LATE CHARGE PAID THRU (LCAP-LCPDTH) IS ON OR AFTER PAYDATE:
           IF LCAP-LPTRCD = "AL"
              MOVE LCAP-PAYDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS NOT > 0
                 GO TO LCAP-I-L-EXIT
              ELSE
                 MOVE 0 TO LCAP-CURDATE
                           LCAP-CURDUE.

      * DOES PAYMENT AND LCPDTH INDICATE AN ASSESSMENT ?
           PERFORM LCAP-ASSESS-CHK.
           IF LCAS-ASSESS NOT = "Y"
              GO TO LCAP-I-L-NOASSESS.

      * TEST FOR LAST CURRENT PAYMENT:
           IF LCAP-LST-CURDATE NOT = 0
              MOVE LCAP-LST-CURDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS = 0
                 MOVE LCAP-LST-CURDATE TO NUM-DATE
                 MOVE PDTH-DATE-FULL   TO SYS-DATE
                 PERFORM TIM
                 IF ELAPSED-DAYS < 0
                    MOVE LCAP-LST-CURDUE TO LCAP-AMTNEEDED
                 ELSE
                    IF LCAP-AMTNEEDED > LCAP-LST-CURDUE
                       MOVE LCAP-LST-CURDUE TO LCAP-AMTNEEDED.

      * TEST FOR AMTNEEDED LESS THAN THE DELINQUINCY FACTOR
      * IN (SPR'S), IF SO ASSESS NO LATE CHARGE:
           IF LCAP-AMTNEEDED < LCAP-DELFAC
              GO TO LCAP-I-L-ADVANCE.

      * DETERMINE THE AMOUNT OF THE LATE CHARGE:
      * IF SP-LCTYPE = "C" OR "J", LCHG-LATE IS INITIALIZED,
      * SINCE LATE CHARGE IS BASED ON % OF AMOUNT DELINQUENT:
           MOVE LCAP-AMTNEEDED TO LCHG-LATE.
           MOVE LCAP-LCPDTH-DATE TO LCHG-LCPDTH-DATE.
           PERFORM LCAP-CALC-TEST.

      * IF LCAP-TRAMT IS NOT ENOUGH TO COVER CHARGE, USE OWING:
           IF LCAP-TRAMT < LCHG-CHARGE
              COMPUTE LCAP-OWE = LCAP-OWE +
                                  (LCHG-CHARGE - LCAP-TRAMT)
              ADD LCAP-TRAMT TO LCAP-APP
              MOVE 0 TO LCAP-TRAMT
           ELSE
              ADD LCHG-CHARGE TO LCAP-APP
              SUBTRACT LCHG-CHARGE FROM LCAP-TRAMT.

       LCAP-I-L-ADVANCE.
           PERFORM LCAP-UPD-LCPD.
           IF LN-PAY-SCHLD-FG = "Y"
              ADD 1 TO LCAP-PMT-NO
              MOVE SCHD-AMT(LCAP-PMT-NO) TO LCAP-AMTNEEDED
                                            LCHG-CURPAY
           ELSE
              MOVE LN-REGPYAMT TO LCAP-AMTNEEDED.

           GO TO LCAP-I-L-BEGIN.

      *******************************************************
      * NO ASSESSMENT IS REQUIRED; ADVANCE LCAP-LCPDTH-DATE
      * TO WHERE PAYMENTS TODATE ARE PAID THRU, ONLY
      * IF IT WILL ADVANCE LCPDTH, SINCE LCPDTH COULD
      * HAVE ADVANCED BEYOND PAID THRU VIA TIME.
      *******************************************************
       LCAP-I-L-NOASSESS.

           IF LCAP-LPTRCD NOT = "AL"
              ADD LCAP-TRAMT LCAP-PAYMNTD GIVING PDTH-PAYMNTD.

      *08/13/15 PR#694
      *MULLEN REPORTED ACCOUNT THAT WAS PAID AHEAD DID NOT ADVANCE
      *LATE CHARGE PAID THRU, CAUSING THE NEXT ON TIME PAYMENT TO
      *ASSESS A LATE CHARGE. THE ACCOUNT WAS PAID AHEAD BUT THE PAYMENT WENT
      *TO INTEREST-OWING. WHEN I WAIVED THE INTEREST-DUE, THE ACCOUNT ADVANCED
      *LCPDTH SO I ADDED SUBTRACT OF LCAP-LPAPINT(INT-OWE)FROM LCAP-WRK. I
      *AM NOT QUITE SURE WHY WE ADD LN-TOTLCHG,LCAP-LPAPLC,LCAP-APP
      *LCAP-LPAPINT TO THIS WORKER. I DO REMEMBER PACESETTER DID NOT WANT
      *AN ACCT TO BE PAST DUE BECAUSE OF PAID LATE CHGS BUT ALSO DID NOT
      *WANT HIM TO BE PAID AHEAD IF HE DID PAY THEM BUT I SEE NO REASON THAT
      *COLLECTED INTEREST OWING SHOULD BE INCLUDED IN THIS WORKER.
      *
      *IN MULLEN'S EXAMPLE LCAP-WRK WAS 30.00(LN-TOTLCHG) + 408.92(INT
      *OWE, WHEN IT COMPUTED PDTH-PAYMENTS IT WAS > 1, SO IT SUBTRACTED
      *A REGPYAMT FROM PAYMENTS TO DATE.
      *
      *HERE IS THE ACCOUNT
      *          TRCD   AMT   INT       PDTH  LCPD       INT/LC OWE
      * 03/28/10  D2                    05/10  05/10        789.73
      * 05/28/10  PY   408.92 408.92    06/10  05/10        868.96
      *WHEN I WAIVED THE INTEREST OWING
      *          TRCD   AMT   INT       PDTH  LCPD       INT/LC OWE
      * 03/28/10  D2                    05/10  05/10        789.73
      * 05/28/10  PY   408.92           06/10  06/10        868.96
      *
      *PAYMENTS TO DATE WAS THE SAME AMOUNT IN BOTH EXAMPLES, BUT DID NOT
      *ADVANCE LCPDTH WITH INTEREST OWING COLLECTED.

           IF LCAP-LPTRCD NOT = "AL"
              IF SP-LCFRMLA = "I" OR "L"
                 ADD LN-TOTLCHG LCAP-LPAPLC LCAP-APP LCAP-LPAPINT
                                                    GIVING LCAP-WRK
                 ADD LCAP-WRK TO PDTH-PAYMNTD

      *PL#694 SEE ABOVE
                 SUBTRACT LCAP-LPAPINT FROM LCAP-WRK

                 COMPUTE PDTH-PAYMENTS = LCAP-WRK / LN-REGPYAMT
                 IF PDTH-PAYMENTS > 1
                    COMPUTE PDTH-PAYMNTD =
                       PDTH-PAYMNTD - ( PDTH-PAYS * LN-REGPYAMT).

           IF LCAP-LPTRCD NOT = "AL"
              IF LN-PAY-SCHLD-FG = "Y"
                 MOVE LCAP-PAYMNTD TO LCAP-HOLDER
                 MOVE PDTH-PAYMNTD TO LCAP-PAYMNTD
                 PERFORM LCAP-PICK-PDTH-CALC
                 MOVE LCAP-HOLDER TO LCAP-PAYMNTD
              ELSE
                 PERFORM LCAP-PICK-PDTH-CALC
              END-IF
              MOVE NDTE-DATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS NOT < 0
                 MOVE PDTH-DATE-FULL TO LCAP-LCPDTH-DATE
                 IF LCAP-UNPAID-PORTION NOT = 0
                          AND LCAP-UNPAID-PORTION < LCAP-DELFAC
                    PERFORM LCAP-UPD-LCPD.

      * INSURE THAT LCPDTH ADVANCES TO CURRENT PAYMENT DATE
      * IF  CURRENT  PAYMENT IS NOT DELIQUENT:
           IF LCAP-CURDATE NOT = 0
              MOVE LCAP-CURDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS > 0
                 IF LCAP-CURDUE < LCAP-DELFAC
                    IF ELAPSED-DAYS > 0
                       MOVE LCAP-CURDATE TO LCAP-LCPDTH-DATE
                    ELSE
                       PERFORM LCAP-UPD-LCPD.

      * ? PAST MATURITY,
      * IF SO FORCE LCAP-LCPDTH-DATE TO MATURITY:
       LCAP-I-L-MATURITY-TEST.
           PERFORM LCAP-MDTE-CHK.
           IF ELAPSED-DAYS NOT > 0
              MOVE SYS-DATE TO LCAP-LCPDTH-DATE.

       LCAP-I-L-EXIT.
           MOVE LCAP-CURDUE TO LCAP-PARTIALS.
      * REARRANGE DATE (MMDDYY) TO (MMDD.YY):
           MOVE LCAP-CURDATE TO DATE-YYYYMMDD.
           PERFORM CONVERT-YYYYMMDD-TO-MMDDYY.
           MULTIPLY DATE-MMDDYY BY 0.01 GIVING LCAP-LCPAID.

      ***********************************************
      *    TEST CURRENT PAYMENT ON TIME
      *
      *    IF SO, ESTABLISH WHETHER ITS A NEW PERIOD
      *    OR LAST PAYMENT PERIOD AND SETUP AMOUNTS
      *    DELIQUENT FOR LAST OR BOTH PERIODS.
      ***********************************************
