      ***************************************************************
      *   SP-LCFRML = H    LOUISIANA LATE CHARGE FORMULA
      *                    LIKE 'F' EXCEPT TOTAL MONIES
      *
      *   NOTE:
      *        LCAP-PARTIALS (HOLDS LCAP-CURDUE AT EXIT)
      *        LCAP-LCPAID   (HOLDS LCAP-CURDATE [MMDD.YY] AT EXIT)
      ***************************************************************
       LCAP-H SECTION.
      * SET PMT-TO-DATE TEMP TO INCLUDE APPLIED TO INTEREST, CITIZENS FINANCE:
           ADD LCAP-TOTPAYMNTD LCAP-LPAPINT GIVING LCAP-PAYMNTD.

           MOVE LCAP-PARTIALS TO LCAP-LST-CURDUE.
      * REARRANGE LAST PAYDATE (MMDD.YY) INTO (MMDDYY):
           MULTIPLY LCAP-LCPAID BY 100 GIVING DATE-MMDDYY.
           PERFORM CONVERT-MMDDYY-TO-YYYYMMDD.
           MOVE DATE-YYYYMMDD TO LCAP-CURDATE
                                 LCAP-LST-CURDATE.

      * SEE IF CONTRACTUAL PAID THRU IS LESS THAN LCPDTH,
      * IF SO SET AMTNEEDED TO REGULAR PAYMENT:
           MOVE PDTH-DATE-FULL TO SYS-DATE.
           PERFORM LCAP-LCPDTH-DATE-TEST.
           IF ELAPSED-DAYS < 0
              IF LN-PAY-SCHLD-FG = "Y"
                 MOVE SCHD-AMT(LCAP-PMT-NO) TO LCAP-AMTNEEDED
              ELSE
                 MOVE LN-REGPYAMT TO LCAP-AMTNEEDED.

      * SETUP CURRENT PAYMENT AND LAST CURRENT PAYMENT,
      * SEE IF CURRENT PAYMENT IS ON TIME:
           PERFORM LCAP-H-CURRENT-PERIOD.

       LCAP-H-BEGIN.
      * TEST IF LATE CHARGE PAID THRU (LCAP-LCPDTH) IS
      * ON OR AFTER MATURITY, IF SO EXIT:
           PERFORM LCAP-MDTE-CHK.
           IF ELAPSED-DAYS NOT > 0
              GO TO LCAP-H-EXIT.

      * ASSESSING LATE CHARGES? (AL)
      * IF SO, STOP ASSESSING WHEN LATE CHARGES ARE BROUGHT
      * UP TODATE, WHEN LATE CHARGE PAID THRU (LCAP-LCPDTH)
      * IS ON OR AFTER PAYDATE:
           IF LCAP-LPTRCD = "AL"
              MOVE LCAP-PAYDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS NOT > 0
                 GO TO LCAP-H-EXIT
              ELSE
                 MOVE 0 TO LCAP-CURDATE
                           LCAP-CURDUE.

      * DOES PAYMENT AND LCPDTH INDICATE AN ASSESSMENT ?
           PERFORM LCAP-ASSESS-CHK.
           IF LCAS-ASSESS NOT = "Y"
              GO TO LCAP-H-NOASSESS.

      * TEST FOR AMTNEEDED LESS THAN THE DELINQUINCY FACTOR
      * IN (SPR'S), IF SO ASSESS NO LATE CHARGE:
      * TEST FOR LAST CURRENT PAYMENT:
           IF LCAP-LST-CURDATE NOT = 0
              MOVE LCAP-LST-CURDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS = 0
                 MOVE LCAP-LST-CURDUE TO LCAP-AMTNEEDED
                 IF LCAP-LST-CURDUE < LCAP-DELFAC
                    GO TO LCAP-H-ADVANCE.

      * DETERMINE THE AMOUNT OF THE LATE CHARGE:
      * IF SP-LCTYPE = 'C', LCHG-LATE IS INITIALIZED,
      * SINCE LATE CHARGE IS BASED ON % OF AMOUNT DELINQUENT:
           MOVE LCAP-AMTNEEDED TO LCHG-LATE.
           MOVE LCAP-LCPDTH-DATE TO LCHG-LCPDTH-DATE.
           PERFORM LCAP-CALC-TEST.

      * IF LCAP-TRAMT IS NOT ENOUGH TO COVER CHARGE, USE OWING:
           IF LCAP-TRAMT < LCHG-CHARGE
              COMPUTE LCAP-OWE = LCAP-OWE +
                                  (LCHG-CHARGE - LCAP-TRAMT)
              ADD LCAP-TRAMT TO LCAP-APP
              MOVE 0 TO LCAP-TRAMT
           ELSE
              ADD LCHG-CHARGE TO LCAP-APP
              SUBTRACT LCHG-CHARGE FROM LCAP-TRAMT.

       LCAP-H-ADVANCE.
           PERFORM LCAP-UPD-LCPD.
           IF LN-PAY-SCHLD-FG = "Y"
              ADD 1 TO LCAP-PMT-NO
              MOVE SCHD-AMT(LCAP-PMT-NO) TO LCAP-AMTNEEDED
                                            LCHG-CURPAY
           ELSE
              MOVE LN-REGPYAMT TO LCAP-AMTNEEDED.
           GO TO LCAP-H-BEGIN.

      * NO ASSESSMENT IS REQUIRED; ADVANCE LCAP-LCPDTH-DATE
      * TO WHERE PAYMENTS TODATE ARE PAID THRU, ONLY
      * IF IT WILL ADVANCE LCPDTH, SINCE LCPDTH COULD
      * HAVE ADVANCED BEYOND PAID THRU VIA TIME.
       LCAP-H-NOASSESS.
           IF LCAP-LPTRCD NOT = "AL"
              ADD LCAP-TRAMT LCAP-PAYMNTD GIVING PDTH-PAYMNTD
                                                 LCAP-PAYMNTD
      *1262
              ADD LCAP-APP TO PDTH-PAYMNTD LCAP-PAYMNTD
              PERFORM LCAP-PICK-PDTH-CALC
              MOVE NDTE-DATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS NOT < 0
                 MOVE PDTH-DATE-FULL TO LCAP-LCPDTH-DATE
                 IF LCAP-UNPAID-PORTION NOT = 0
                     AND LCAP-UNPAID-PORTION < LCAP-DELFAC
                     PERFORM LCAP-UPD-LCPD.

      * INSURE THAT LCPDTH ADVANCES TO CURRENT PAYMENT DATE
      * IF  CURRENT  PAYMENT IS NOT DELIQUENT:
           IF LCAP-CURDATE NOT = 0
              MOVE LCAP-CURDATE TO SYS-DATE
              PERFORM LCAP-LCPDTH-DATE-TEST
              IF ELAPSED-DAYS > 0
                 IF LCAP-CURDUE < LCAP-DELFAC
                    MOVE LCAP-CURDATE TO LCAP-LCPDTH-DATE.

      * ? PAST MATURITY,
      * IF SO FORCE LCAP-LCPDTH-DATE TO MATURITY:
           PERFORM LCAP-MDTE-CHK.
           IF ELAPSED-DAYS NOT > 0
              MOVE SYS-DATE TO LCAP-LCPDTH-DATE.

       LCAP-H-EXIT.
           MOVE LCAP-CURDUE TO LCAP-PARTIALS.
      * REARRANGE DATE TO (MMDD.YY):
           MOVE LCAP-CURDATE TO DATE-YYYYMMDD.
           PERFORM CONVERT-YYYYMMDD-TO-MMDDYY.
           MULTIPLY DATE-MMDDYY BY 0.01 GIVING LCAP-LCPAID.

      ***********************************************
      *    TEST CURRENT PAYMENT ON TIME
      *
      *    IF SO, ESTABLISH WHETHER ITS A NEW PERIOD
      *    OR LAST PAYMENT PERIOD AND SETUP AMOUNTS
      *    DELIQUENT FOR LAST OR BOTH PERIODS.
      ***********************************************
