      ************************************************
      *    SET INTEREST PDTH (ASSESS FROM DATE)
      ************************************************
       LPRATE-SET-INTPDTH-DATE SECTION.
           MOVE LN-INTDATE TO INDU-DATE-1.
           IF LN-INTPDTH-DATE NOT = 0
              MOVE LN-INTPDTH-DATE TO INDU-DATE-1
           ELSE
              IF (LN-DATE-PAID-LAST NOT = 0)
                       AND (LN-DATE-PAID-LAST NOT = LN-LOANDATE)
                 MOVE LN-DATE-PAID-LAST TO INDU-DATE-1.

      *************************************************************************
      *   NAME:  LPINDU - INTEREST DUE CALCULATION
      *   DESC:  COMPUTE INTEREST DUE AT GIVEN PAY DATE
      *   IN  :  INDU-DATE-1  (LN-INTDATE OR LAST INTEREST ACCESS)
      *          INDU-DATE-2  (LP-PAYDATE)
      *          INDU-CURBAL (LN-CURBAL - LN-OT2BAL)
      *          INDU-RATE   (LN-EXPRRATE, LN-ENDORATE, ETC)
      *          INDU-LPTRCD (PAYMENT TRANSACTION CODE)
      *          INDU-YEARTYPE (YEAR TYPE BASED ON RATE BEING USED)
      *          INDU-INTMETHOD (INTEREST METHOD BASED ON RATE USED)
      *   OUT :  INDU-INTEREST
      *          INDU-DAYS
      *          INDU-PENALTY
      *   USED:
      * REV :
      *  092287 JTG REMOVED COMMA'S  ALSO CHANGED
      *             LOGIC FOR SELECTING RATE TABLE
      *             TO MAKE IT BETTER READ.
      *  092287 JTG MODIFIED TO ALLOW A SPACE IN
      *             BREAKTYPE IF SINGLE RATE TABLES.
      *  033188 JTG ADDED LOGIC FOR SPECIAL REFUND
      *             CONDITIONS
      *  041888 SLC CHANGED 99.9999 TO 999.999 TO MAKE
      *             COMPATABLE WITH NEW RATE DEFINITION.
      *             ADDED THE FOLLOWING OPTIONS:
      *             IF INDU-RATE = 999.998 USE LN-SMPRATE
      *             IF INDU-RATE = 999.997 USE ACCELERATION
      *             TABLE FROM SPR.
      *  050288 SLC YEARTYPE AND INT METH NOW PASSED TO INDU.
      *  032789 JTG CHANGED HOLLLYWODD FINANCE PO MAX
      *             60 INT. CALC ON RENEWAL TO TEST
      *             SPECIAL OPT 1 AND NOT RECAST CODE.
      *  080189 JTG ADDED LOGIC FOR SP-RBSPOPT1 = 5 SPRING (NJ)
      *  081089 JTG ADDED LOGIC FOR SP-RBSPOPT2 = 2 SPRING (NJ)
      *  100589 SLC ADDED SPECIAL OPTION TO CALC INTEREST BASE ON
      *             MAX NUMBER OF DAYS TO ACCRUE FOR IB ACCRUE REPORT
      *  012690 JTG ADDED OUTPUT OF INDU-DAYS
      *  053190 JTG ADDED SP-RBSPOPT1 = 8, PACESETTER
      *  083190 BAH ADDED REDUCTION OF SERVICE CHARGE FOR
      *             CHARGEABLE CODES 'I' AND 'P'
      *  031491 JTG ADDED REDUCTION OF INSURANCE PREMIUMS FOR
      *             CHARGEABLE CODES 'S' AND 'P'
      *  JTG 062995 ADDED SP-OPT-CAL-CHGABLE, MERCURY MI SERCHG
      *  JTG 092095 STOPPED REDUCTION OF CURRENT BALANCE ON 'PC' TYPE
      *             ACCOUNTS, WHEN THE SPR INTEREST CHARGABLE CODE
      *             EXCLUDED 'SERCHG AND /OR INSURANCE PREMIUMS'
      *  JTG 112795 ADDED SP-RBREDUC = 9999.02, 'NV' MERCURY ACTION SPRDER = 09
      *  JTG 120297 CHANGED TO ESTABLISH NO LIMIT ON SP-MAX-IB-ACR-DAYS
      *             CBC CAPITAL SINGLE PAY LOAN 12 MONTHS
      *  JTG 011698 PUT THE CODE IN FOR LOGIC THAT SHOULD HAVE BEEN ADDED
      *             BACK ON 092095, FOR STOPPING REDUCTION OF CURRENT BALANCE
      *             ON 'PC' TYPE ACCOUNTS, WHEN THE SPR INTEREST CHARGABLE CODE
      *             EXCLUDED 'SERCHG AND /OR INSURANCE PREMIUMS'
      *  JTG 990216 ADDED INTEREST-DUE-PENALTY-OH, SPECIAL OPTION #1 (16).
      *  JTG 991202 ADDED SP-RBREDUC = 9999.03, 'GA' NEW SOUTH PREPAY PENALTY
      *  JTG 000104 ADDED SP-RBREDUC = 9999.04 WISCONSIN IB REAL ESTATE
      *             PREPAY PENALTY, WISCONSIN #1031
      *             PLUS XFER OF PENALTY TO MSPENALTY IN LONPF SCREEN
      *  JTG 000124 ADDED SP-CAL-MAX-AT-ESTIMATE INSTANT AUTO #1047
      *  000225 MJD ADDED SP-RBREDUC = 9999.05 NEW SOUTH FLAT $75.00
      *             PREPAY PENALTY, (NEWS PR#1101)
      *  000804 BAH NEW SOUTH, RBREDUC = 9999.03, WAS NOT STORING THE
      *             PENALTY IN INDU-PENALTY, IT WAS ADDING IT DIRECTLY
      *             INTO INDU-INTEREST,,,FAX FROM KEVIN
      *  JTG 000822 ADDED LOGIC FOR KENTUCKY 60 DAY NO CHARGE LAW, ADDED
      *             SP-RBSPOPT1() = 19, WORLD #233
      *  JTG 000914 CORRECTED BUG IN PASS TO SETCTBL, ROUTINE WAS PASSING
      *             LN-LNAMT INSTEAD OF INTEREST CHARGEABLE  WORLD #J011
      *  BAH 010108 ADDED CLEAR OF INDU-PENALTY, NEEDED TO BE SURE IT WAS
      *             0 CAUSE IT WILL SUBTRACT THIS FROM NO-DEFERMENT IN
      *             SPINQ0 CAUSE IT CALLS CRNORC WITH "PO" WITH CREATES
      *             AN INTEREST PENALTY INCLUDED IN THE NO-DEFERMENT
      *             LENDMARK (KEVIN)
      * JTG 020722 CHANGED FOR (MIP) MONTHLY INSURANCE PREMIUMS   REGENCY #1801
      *  BAH 020828 ALLOWED RBREDUC(7) = 9999.01 TO WORK FOR IB'S, ADD PENALTY
      *             TO INDU-INTEREST, PIKCO PR# 1900
      *  BAH 021216 CHANGE ABOVE CALCULATED A PENALTY ON EVERY PAYMENT !!
      *             NEEDS TO CHECK FOR "PO" AND "PA" ONLY
      *  BAH 040623 ADDED RBSPOPT1 = 21, THRIFT INVESTMENT PR# 2334
      *  BAH 160921 ADDED LT-REC ON THE CALL OF REBA01, LINKAGE ERROR AT
      *             CUSTOMER REBA01 WAS CHANGED 6 YEARS AGO! FIRST METRO #949
      *  BAH 180702 CHANGED A01 PASSING FIELDS TO BE IN LPRATEW SO REBATE 
      *             COPY MEMBERS DO NOT NEED TO BE IN HERE!
      *   CS 211105 CHANGED INTEREST-DUE CALCULATION IF ELAPSED-YRTYPE IS 0
      **************************************************************************
