       NO-PENALTY-GA.
           GO TO INTEREST-DUE-PENALTY-EXIT.

      * WISCONSIN PRE-PAYOFF PENALTY, WISCONSIN FINANCE (IB REAL ESTATE)
      * IF PAYOFF IS PRIOR TO 4TH YEAR TAKE PENALTY:
      
