       POST-REFUNDS-PLUS-PY-NOW.

      * READ UPDATED LOAN (ONE MORE TIME, IN CASE THERE WERE NO REBATES)

           PERFORM READ-LN1-FILE.

      * MUST SET TO " " TO GET DEFAULT BP-TRCD SET:
           MOVE " " TO HOLD-BP-TRCD.

      * MERCURY RE:256X
      * MUST SET ORIG-LN-.... TO LN-..... VALUES SINCE THEY HAVE
      * CHANGED WHEN LONPF2.C WAS CALLED ABOVE AND PAYMENT-POSTING
      * ROUTINE SET THEM TO THE ORIGINAL VALUES WHEN THE LOAN WAS
      * FIRST PROCESSED.

           MOVE LN-LBOX    TO ORIG-LN-LBOX.
           MOVE LN-ALLOTCD TO ORIG-LN-ALLOTCD.

           PERFORM PAYMENT-POSTING.

           MOVE WK-LP-REC TO LP-REC.

