      *-----------------------------------------------------------------
       READ-BW1-FILE.
           PERFORM READ-IT.
           MOVE BW-PATH-OWNBR  TO BW-OWNBR. 
           MOVE BW-PATH-SQL    TO E-FILE.
           MOVE BW1-KEY        TO E-KEYX.
           INITIALIZE QBW-REC.

           MOVE BW-OWNBR   TO QBW-OWNBR.
           MOVE BW-SSNO    TO QBW-SSNO.

           EXEC SQL
            SELECT BWFILE.BW_OWNBR,
                   BWFILE.BW_SSNO,
                   BWFILE.BW_LNAME,
                   BWFILE.BW_FNAME,
                   BWFILE.BW_MNAME,
                   BWFILE.BW_NICKNAME,
                   BWFILE.BW_GENERATION,
                   BWFILE.BW_ADR1,
                   BWFILE.BW_ADR2,
                   BWFILE.BW_CITY,
                   BWFILE.BW_STATE,
                   BWFILE.BW_ZIP,
                   CAST(BWFILE.BW_LTOUCH_DATE
                                                  AS VARCHAR(10)),
                   CAST(BWFILE.BW_REFDATE AS VARCHAR(10)),
                   CAST(BWFILE.BW_BDATE AS VARCHAR(10)),
                   BWFILE.BW_PHONE,
                   BWFILE.BW_CELL_PHONE,
                   BWFILE.BW_NATIONALITY,
                   BWFILE.BW_GENDER,
                   BWFILE.BW_DEPEND,
                   BWFILE.BW_RENTCD,
                   BWFILE.BW_TIMEADDR,
                   BWFILE.BW_CREDITCD,
                   BWFILE.BW_STRTGCD,
                   BWFILE.BW_DWELLCD,
                   BWFILE.BW_COUNTY,
                   BWFILE.BW_ORIGIN,
                   BWFILE.BW_CENSUSCD,
                   BWFILE.BW_ORGSLSMN,
                   BWFILE.BW_REPCODE,
                   BWFILE.BW_SPSSNO,
                   BWFILE.BW_SPLNAME,
                   BWFILE.BW_SPFNAME,
                   CAST(BWFILE.BW_SP_BDATE AS VARCHAR(10)),
                   BWFILE.BW_EMPLOYER,
                   BWFILE.BW_EMPLPOS,
                   BWFILE.BW_EMPPHONE,
                   BWFILE.BW_EMPEXT,
                   BWFILE.BW_EMPYEARS,
                   BWFILE.BW_EMPPAY,
                   BWFILE.BW_EMPPAYOT,
                   BWFILE.BW_EMPPAYSR,
                   BWFILE.BW_EMPADDR1,
                   BWFILE.BW_EMPADDR2,
                   BWFILE.BW_EMPCITY,
                   BWFILE.BW_EMPSTATE,
                   BWFILE.BW_EMPZIP,
                   BWFILE.BW_WORKHRS,
                   BWFILE.BW_LOANS,
                   BWFILE.BW_INTYTD,
                   BWFILE.BW_INTLYR,
                   BWFILE.BW_LIASMLN,
                   BWFILE.BW_LIAOTH,
                   CAST(BWFILE.BW_LASTPODATE
                                                  AS VARCHAR(10)),
                   BWFILE.BW_PRLOANS,
                   BWFILE.BW_RE_INTYTD,
                   BWFILE.BW_RE_INTLYR,
                   BWFILE.BW_CREDIT_LIMIT,
                   BWFILE.BW_CREDIT_SCORE,
                   BWFILE.BW_CRED_SCORE_1,
                   BWFILE.BW_CRED_SCORE_2,
                   BWFILE.BW_CRED_SCORE_3,
                   BWFILE.BW_CRED_SCORE_4,
                   BWFILE.BW_BNKRPT_SCORE_1,
                   BWFILE.BW_BNKRPT_SCORE_2,
                   BWFILE.BW_BNKRPT_SCORE_3,
                   BWFILE.BW_BNKRPT_SCORE_4,
                   BWFILE.BW_LAST_FORM_NO,
                   CAST(BWFILE.BW_LAST_FORM_DATE
                                                  AS VARCHAR(10)),
                   CAST(BWFILE.BW_PRIOR_RN_FOR10_DATE
                                                  AS VARCHAR(10)),
                   CAST(BWFILE.BW_LAST_RN_FOR10_DATE
                                                  AS VARCHAR(10)),
                   CAST(BWFILE.BW_ADR_PHONE_CHG_DATE
                                                  AS VARCHAR(10)),
                   BWFILE.BW_BAD_ADR_FG,
                   BWFILE.BW_BAD_PHONE_FG,
                   BWFILE.BW_BAD_EMPPHONE_FG,
                   BWFILE.BW_BAD_MISC_PHONE1_FG,
                   BWFILE.BW_BAD_MISC_PHONE2_FG,
                   BWFILE.BW_BAD_CELL_FG,
                   BWFILE.BW_MISC_PHONE_1,
                   BWFILE.BW_MISC_EXT_1,
                   BWFILE.BW_MISC_PHONE_CD_1,
                   BWFILE.BW_MISC_PHONE_2,
                   BWFILE.BW_MISC_EXT_2,
                   BWFILE.BW_MISC_PHONE_CD_2,
                   BWFILE.BW_MISC_PHONE_3,
                   BWFILE.BW_MISC_EXT_3,
                   BWFILE.BW_MISC_PHONE_CD_3,
                   BWFILE.BW_MISC_PHONE_4,
                   BWFILE.BW_MISC_EXT_4,
                   BWFILE.BW_MISC_PHONE_CD_4,
                   BWFILE.BW_MISC_PHONE_5,
                   BWFILE.BW_MISC_EXT_5,
                   BWFILE.BW_MISC_PHONE_CD_5,
                   BWFILE.BW_MISC_PHONE_6,
                   BWFILE.BW_MISC_EXT_6,
                   BWFILE.BW_MISC_PHONE_CD_6,
                   BWFILE.BW_CONTACT_DESC_1,
                   BWFILE.BW_CONTACT_PHONE_1,
                   BWFILE.BW_CONTACT_EXT_1,
                   BWFILE.BW_CONTACT_RELATION_1,
                   BWFILE.BW_CONTACT_DESC_2,
                   BWFILE.BW_CONTACT_PHONE_2,
                   BWFILE.BW_CONTACT_EXT_2,
                   BWFILE.BW_CONTACT_RELATION_2,
                   BWFILE.BW_CONTACT_DESC_3,
                   BWFILE.BW_CONTACT_PHONE_3,
                   BWFILE.BW_CONTACT_EXT_3,
                   BWFILE.BW_CONTACT_RELATION_3,
                   BWFILE.BW_CONTACT_DESC_4,
                   BWFILE.BW_CONTACT_PHONE_4,
                   BWFILE.BW_CONTACT_EXT_4,
                   BWFILE.BW_CONTACT_RELATION_4,
                   BWFILE.BW_CONTACT_DESC_5,
                   BWFILE.BW_CONTACT_PHONE_5,
                   BWFILE.BW_CONTACT_EXT_5,
                   BWFILE.BW_CONTACT_RELATION_5,
                   BWFILE.BW_CONTACT_DESC_6,
                   BWFILE.BW_CONTACT_PHONE_6,
                   BWFILE.BW_CONTACT_EXT_6,
                   BWFILE.BW_CONTACT_RELATION_6,
                   BWFILE.BW_CONTACT_DESC_7,
                   BWFILE.BW_CONTACT_PHONE_7,
                   BWFILE.BW_CONTACT_EXT_7,
                   BWFILE.BW_CONTACT_RELATION_7,
                   BWFILE.BW_CONTACT_DESC_8,
                   BWFILE.BW_CONTACT_PHONE_8,
                   BWFILE.BW_CONTACT_EXT_8,
                   BWFILE.BW_CONTACT_RELATION_8,
                   BWFILE.BW_CONTACT_DESC_9,
                   BWFILE.BW_CONTACT_PHONE_9,
                   BWFILE.BW_CONTACT_EXT_9,
                   BWFILE.BW_CONTACT_RELATION_9,
                   BWFILE.BW_CONTACT_DESC_10,
                   BWFILE.BW_CONTACT_PHONE_10,
                   BWFILE.BW_CONTACT_EXT_10,
                   BWFILE.BW_CONTACT_RELATION_10,
                   BWFILE.BW_SRCD,
                   BWFILE.BW_CALL_ON_SUNDAY,
                   BWFILE.BW_SOLICIT,
                   BWFILE.BW_CONFIDENTIAL,
                   BWFILE.BW_PRIVACY_OPT_OUT,
                   BWFILE.BW_OPT_IN_EMAIL,
                   BWFILE.BW_OPT_IN_TEXT,
                   BWFILE.BW_CITY_TAX_CD,
                   CAST(BWFILE.BW_DEALTRACK_CHG_DATE
                                                  AS VARCHAR(10)),
                   BWFILE.BW_DECEASED,
                   CAST(BWFILE.BW_DECEASED_DATE
                                                  AS VARCHAR(10)),
                   BWFILE.BW_EMAIL,
                   BWFILE.BW_IDENT_NO,
                   BWFILE.BW_IDENT_TYPE,
                   BWFILE.BW_IDENT_STATE,
                   BWFILE.BW_MILITARY_FLAG,
                   BWFILE.BW_ORGBR,
                   CAST(BWFILE.BW_CEASE_DESIST_DATE AS VARCHAR(10)),
                   BWFILE.BW_CEASE_DESIST_TYPE,
                   CAST(BWFILE.BW_UMC_EXPIRE_DATE AS VARCHAR(10)),
                   CAST(BWFILE.BW_UMC_PR_EXPIRE_DATE AS VARCHAR(10))
            INTO :QBW-REC
            FROM DBO.BWFILE
            WHERE BWFILE.BW_OWNBR = :QBW-OWNBR
              AND BWFILE.BW_SSNO = :QBW-SSNO
           END-EXEC.

           PERFORM SQL-IO-VALIDATION.

           IF ( IO-FG = 8 )     *>LOCKED
              GO TO READ-BW1-FILE.

           IF ( IO-FG = 0 )
              PERFORM GET-BW-FIELDS.

      *-----------------------------------------------------------------
