      ******************************************************************
      * PREPAYMENT PENALTY FOR MX VYBA LOANS (WORLD PR#0954)
      *
      * THE FOLLOWING DESCRIPTION IS COPIED DIRECTLY FROM THE REQEST:
      * -------------------------------------------------------------
      *  THE CALCULATION WOULD BE THE AMOUNT FINANCED TIMES THE EFFECTIVE
      *  RATE, DIVIDED BY 365 TIMES THE NUMBER OF DAYS FROM DATE OF LOAN
      *  UNTIL FIRST PAY DATE, OR PAYOFF DATE, WHICHEVER IS EARLIER.
      *
      *  SO, IF THE LOAN PAYS OFF BEFORE THE FIRST PAY DATE, IT WILL BE FOR
      *  THE NUMBER OF DAYS LOAN WAS OPEN.  IF IT IS AFTER THE FIRST PAY
      *  DATE BUT IS IN THE FIRST 12 MONTHS, IT WILL BE THE INTEREST THAT
      *  SHOULD HAVE BEEN CHARGED FOR THE EXTENDED FIRST PAY DATE.
      *
      *  EXAMPLE, DATE OF LOAN 09/01/13.  DATE OF FIRST PAYMENT 11/07/13.
      *  AMOUNT FINANCED $20,000. RATE IS EFFECTIVE 75%.
      *
      *  CUSTOMER PAYS OFF ON 10/25/13.  THIS IS PRIOR TO THE FIRST PAY DATE,
      *  SO THE CHARGE WILL BE FOR ONLY THE NUMBER OF DAYS FROM DATE OF
      *  LOAN TO PAYOFF DATE, WHICH ON A 365 DAY YEAR TYPE IS 54 DAYS.
      *  SO WE WILL TAKE $20,000.00 TIMES .75 DIVIDED BY 365 TIMES 54,
      *  OR 20000 X .75 = 15000/365=41.09589 X 54 = $2,219.18 EARLY
      *  PAYOFF PENALTY.
      *
      *  CUSTOMER PAYS OFF ON 12/25/13.  THIS IS AFTER THE FIRST PAY DATE,
      *  SO THE CHARGE WILL BE FOR ONLY THE NUMBER OF DAYS FROM DATE OF
      *  LOAN TO THE FIRST PAY DATE, WHICH ON A 365 DAY YEAR TYPE IS 67 DAYS.
      *  SO WE WILL TAKE $20,000.00 TIMES .75 DIVIDED BY 365 TIMES 67,
      *  OR 20000 X .75 = 15000/365=41.09589 X 67 = $2,753.42 EARLY PAYOFF
      *  PENALTY. THE EARLY PAYOFF AMOUNT IS SUBTRACTED FROM THE NORMAL
      *  REFUND AMOUNT, THUS INCREASING THE PAYOFF BY THE AMOUNT OF THE
      *  EARLY PENALTY.
      *
      *  CUSTOMER PAYS OFF ON 11/24/14 NO PENALTY SINCE IT IS MORE THAN 12
      *  MONTHS FROM DATE OF LOAN.
      *
      ******************************************************************
       REBATE-RBREDUC-VYBA-28 SECTION.
           MOVE 0 TO REB-MS-PENALTY.
           IF REB-LPTRCD = "PO" OR "PB"
              IF REB-PAYDATE < LN-ORIG-1STPYDATE
                 PERFORM LOAN-CALCULATIONS
                 MOVE LN-LOANDATE TO NUM-DATE
                 MOVE REB-PAYDATE TO SYS-DATE
                 PERFORM TIM365
                 COMPUTE REB-MS-PENALTY ROUNDED =
                     ( FINANCED-AMOUNT * LN-EFFRATE * ELAPSED-DAYS ) /
                            (365 * 100)
              ELSE
                 MOVE LN-LOANDATE TO NUM-DATE
                 MOVE REB-PAYDATE TO SYS-DATE
                 PERFORM TIM365
                 IF ELAPSED-MONTHS NOT < 12
                    GO TO REBATE-RBEARLY-VYBA-28-EXIT
                 END-IF
                 MOVE LN-LOANDATE TO NUM-DATE
                 MOVE LN-ORIG-1STPYDATE TO SYS-DATE
                 PERFORM TIM365
                 PERFORM LOAN-CALCULATIONS
                 COMPUTE REB-MS-PENALTY ROUNDED =
                     ( FINANCED-AMOUNT * LN-EFFRATE * ELAPSED-DAYS ) /
                            (365 * 100)
              ELSE
                 MOVE 0 TO REB-MS-PENALTY.

           COMPUTE REB-REBATE = REB-REBATE - REB-MS-PENALTY
           IF REB-REBATE < 0
              MOVE 0 TO REB-REBATE
           END-IF.

       REBATE-RBEARLY-VYBA-28-EXIT.
           EXIT.

      *********************************************
      *   ROUTINE TO CALL SUBPROGRAM:
      *
      *   MOVE FIELDS TO PASS TO REB-COMMON
      *   MOVE PROGRAM NAME TO REB-FORM-PROG
      *   IF NO CANCEL OF SUBPROG IS REQUESTED
      *      MOVE " " TO REB-CANCEL-FG.
      *********************************************
