      *================================================================*
      * END COPYBOOK: LIBLP\LPAMTS.CPY                                *
      *================================================================*
      *================================================================*
      * EMBEDDED COPYBOOK: LIBGB\REBATE.CPY                           *
      *================================================================*
      * COPYMEMBER: LIBGB/REBATE
      ***************************************************************
      * ADDON NOTES: SHOULD EST. REB-LN-EXTCHG. REB-LN-SERCHG?
      *              REB-LN-INTCHG?
      *
      * NOTE : EARLY PROVISIONS DO NOT WORK WITH ADDONS!!!
      *          SEE CINDY'S NOTE FROM 10/12/2023
      *
      *
      *          ---REBATE CALCULATIONS
      *
      *   NAME:  REBATE
      *   DESC:  GENERALIZED REBATE CALCULATIONS
      *
      *   W A R N I N G:
      *            THIS PROGRAM CALLS A SUB PROGRAM AND REQUIRES
      *            THAT THE PROGRAM CONTAINING THIS COPY MEMBER
      *            HAVE THE STATEMENT:
      *
      *       =======>  MOVE FORM-PATHNAME TO FORM-PATH <=======
      *
      *---------------------------------------------------------
      *    N O T E:
      *
      *  ------> REB-REMTERM IS NOW AN OUTPUT FIELD, SO
      *          INSURE ITS INTEGRITY AFTER IT IS USED
      *          TO CALCULATED THE REFUND.
      *
      *         NEW FORMULAS DEALING WITH MULTIPLE CHARGE REBATES
      *         EX. INTEREST + SERVICE CHARGE.....DEFERMENTS
      *         MUST REVIEW EARNINGS VERY CARFULLY SINCE
      *         EARNINGS ARE REFLECTED IN COMPONET FORMAT.
      *           (LPEADJ)
      *---------------------------------------------------------
      *
      *   IN  :  REB-PAYDATE    - DATE OF PAYOFF
      *          REB-ORGTERM    - ORIGINAL TERM TO REBATE ON
      *          REB-SUB        - INS/INT TABLE LEVEL IN SP-FILE
      *          REB-TOTCHG     - PREMIUM/INTEREST TO REBATE
      *          REB-LPTRCD     - CURRENT TRANSACTION CODE
      *                           NEEDED FOR SP-RBSPOPT1 = 2
      *                             WITH  TRCD PB, RN, AND SC
      *                           NEEDED FOR SP-RBSPOPT2 = 2
      *                             WITH  TRCD PB AND RN
      *          REB-STATEWK    - INPUT WORK FIELD
      *                           ALWAYS CLEARED AT REBATE-EXIT.
      *                           NEEDED FOR RBFRMLA 'H' (GA)
      *                           INITIALIZED IN LPPOFF TO AMOUNT
      *                           OF INTEREST REBATE
      *          REB-RECAST     - Y - ALLOW RECASTING.
      *          REB-DEF-STOP   - SET TO 'Y' IN LONPFB AND LONPFA
      *                           TO IDENTIFY REBATE IS CALL FROM
      *                           A POSTING ROUTINE
      *   OUT :  REB-REBATE     - REBATE AMT; NEVER < 0
      *          REB-SUB        - = 0 SIGNALS ERROR
      *          REB-PRES-VALUE - USED ONLY BY LPCERN ERNFRMLA = 11
      *          REB-REMTERM    - REMAINING TERM USED IN CALCULATIONS
      *   USED:
      *   COPY:  REBATEW, LPNDTE, LPNDTEW, JUL, JULW
      *          TIMALL, TIM365, TIM360, LPAMTSW, LPAMTS
      *          TIMW, DATEWK, INCRMM
      * REV:
      *  052086 JTG MODIFIED 78THS ANTIC. TO TEST
      *            OVRDRATE 1ST.
      *  061886 JTG ADDED LOGIC FOR SP-RBDEFER CODE
      *  061886 JTG ADDED LOGIC TO FIX SP-RBDET CODES FOR SP-RBFRMLA 3
      *  061886 JTG ADDED LOGIC TO TEST FOR PRIOR TO REFDATE.
      *  112586 JTG ADDED TEST FOR SP-RBDEFER( ) = 2
      *             AND IF SO TO NOT CONSIDER DEFERMENTS
      *             IN THE COMPUTATION OF REBATE.
      *  082487 AMW ADDED REBATE FORMULA 7 FOR ACTUARIAL
      *             SECURITY OF AMERICA
      *  082887 AMW ADDED 'X' LOGIC FOR SP-RBDTE
      *             TO USE INTDATE/PURDATE
      *  120187 JTG MODIFIED ACTUARIAL REBATE FORMULA 2
      *             TO REBATE IN FULL IF PAYOFF PRIOR TO START DATE.
      *             ALSO, ADDED NEW FLAG REB-SKIPDEF-FG SO
      *             EARNINGS ROUTINES COULD DO AN ACTUARIAL
      *             -REBATE WITHOUT DEFERMENTS CONSIDERED
      *  021988 JPN ADDED ROUTINES FOR EARLY REBATE FORMULAS 1 AND 2.
      *  022388 JTG ADDED LOGIC FOR NEW DEDUCT FROM CHARGE CODE, 9999.01
      *  042888 BAW ADDED LOGIC FOR FORMULA 8
      *  042988 JPN ADDED LOGIC FOR SP-RBSPOPT1=2 SP-DEDCHG=9999.02
      *  051688 JPN ADDED LOGIC FOR FORMULA 'A'
      *  062188 JTG ADDED LOGIC FOR FORMULA 'B' AND 'C'
      *  090788 JTG OPENED UP FOR 13 REBATE LEVELS
      *  092188 JTG CHANGED TO PERFORM (COMPUTE INSURANCE TERM)
      *  110188 JTG ADDED LOGIC FOR SP-RBREDUC = 9999.01
      *             AND LOGIC TO CALL SUB PROGRAMS
      *             ADDED LOGIC FOR SP-RBEARLY = 3
      *             ADDED LOGIC FOR SP-RBSPOPT1 = 3
      *  121388 JTG ADDED LOGIC FOR SP-RBMINRET 9999.01 IOWA
      *  011788 JTG ADDED LOGIC FOR FORMULA 'D' IOWA
      *  021089 JTG DISABLED SP-RBDEFER FOR FORMULA 'D' IOWA
      *                 AND  SP-RBNOMON FOR FORMULA 'D'
      *  022889 JTG ADDDED TENNESSEE DEFERMENT REBATE LOGIC
      *  030389 JTG CORRECTED FORMULA "D" WHEN COMPUTED
      *             -REBATE WAS GREATER THAN LN-INTCHG
      *  030689 JTG ADDED SP-RBSPOPT2 = 1, HOLLYWOOD (FL)
      *  041089 JTG ADDED LOGIC FOR SP-RBSPOPT1 = 4
      *  041989 JTG ADDED LOGIC FOR SP-RBFRMLA = F
      *  071289 SLC CORRECTED FORMULA "F" WHEN COMPUTED
      *             -REBATE WAS GREATER THAN LN-INTCHG
      *  072089 JTG CHANGE LOGIC TO USE LN-ORIG-1STPYDATE
      *             AND NOT LN-1STPYDATE
      *  072789 JTG ADDED REBATE FORMULA "G" FOR
      *             IDEAL (MA) AH REBATE
      *  080189 JTG ADDED SP-RBSPOPT1 = 5 FOR SPRING FINANCE
      *  081189 JTG ALLOWED FORMULA F TO USE SWING RULE
      *  090189 JTG ADDED SP-RBSPOPT2 = 3 (GEORGIA)
      *  091489 JTG CHANGED SP-RBSPOPT1 = 5 TO BE A REBATE
      *             REDUCTION AND NOT A DEDUCT FROM CHARGE
      *  092889 JTG FIXED FRMLA 'F', SWING 0 ELAPSED-REM NOT TO TAKE
      *             EXTRA MONTH ELAPSED
      *  100489 JTG FURTHER FIXED SWING RULE TO WORK
      *  102489 JTG ADDED RBFRMLA = H AND I, SERCHG (GA)
      *  110889 JTG ADDED LOGIC FOR SP-RBEARLY = 4 OR 5 (GA)
      *  121589 JTG FIXED BUG FRMLA F (2ND FROM LAST PAY PERIOD)
      *  010890 SLC ADDED RBFRMLA = J, FOR MURDOCK.
      *  011890 JTG ADDED LOGIC FOR SP-RBMIN(7) = 999.01 (GA)
      *  021690 JTG ALLOWED SP-RBDEF FOR DEFERMENT REBATES
      *  041790 JTG LET ACTUARIAL-F TREAT SINGLE PAY LOANS
      *             AS IF NOT COMPOUNDING TAKES PLACE
      *  042690 JTG ADDED LOGIC FOR SP-RBEARLY = 7 & 8, PACESETTER
      *  051090 JTG ALLOWED USRULE, FOR ACTUARIAL-F
      *  052990 JTG ADDED RBFRMLA = K (PACESETTER DEFERMENT)
      *  080990 JTG CHANGED ROUTINE TO WORK FOR ADDONS
      *  090690 BAH ADDED RBFRMLA = M (MULLEN DEFERMENT)
      *  113090 JTG TOOK OUT LOGIC FRO DATE-ROUTINE (D-DATE)
      *  21090 SLC ADDED REB-RECAST TO INDICATE IF WE ARE TO RECAST.
      *             ALSO ADDED CALL TO REBC01 (RECAST).
      *  011091 JTG CHANGED SPOPT2 = 5 FROM 30 TO 15 DAYS
      *  011591 JTG CHANGED TEST ON REB-ADDON-FG = "N"
      *                   TO ONLY LOOK AT ACCOUNTS WITH ADDONS
      *  011791 JTG FURTHER CORRECTION FOR ABOVE CHANGE
      *  011891 JTG STOPPED SP-RBMINRET TEST ON ADDON RECORDS
      *  011591 JTG CHANGED TEST ON REB-ADDON-FG = "N"
      *                   AND NO CHANGE IN FINCHG OCCURED
      *  032791 JTG CORRECTED SP-RBMINRET TEST ON ADDON RECORDS
      *  052191 JTG CHANGED SP-RBEARLY = 8 (PACESETTER) 78 CALC
      *  090391 JTG ADDED SP-RBFRMLA = "N", PACESETTER
      *             CORRECTED PROBLEM FOR AM. THRIFT SINCE THEY
      *             BOTH USE SP-RBEARLY = 8
      *  100491 JTG CORRECTED TRISTATE FORMULA 'D'
      *  110191 JTG CORRECTED MISSISSIPPI INT REBATE
      *             EXTCHG ADDED INTO REB-TOTCHG TWICE
      *  123091 JTG ADDED REB-PRES-VALUE (EDDIE GOLDSTICKER)
      *  041592 JTG CHANGED TO PRORATA REFUND IF 'PB' OR 'RN'
      *             RE: SP-RBSPOPT = 7 (MULLEN)
      *  071392 JTG ADDED SP-RBFRMLA = 'O' & SET OF B01-FRMLA,
      *             TENN DEF REBATE, COLONIAL
      *  071792 JTG ADDED SP-RBFRMLA = 'P' UVALDE TX (AH)
      *  082092 JTG SET B01-DEF-STOP FROM REB-DEF-STOP
      *              FOR COLONIAL, TN DEFERMENT REBATE ROUTINE
      *  110692 JTG CORRECTED PRORATA REFUND IF 'PB' OR 'RN'
      *             RE: SP-RBSPOPT = 7 (MULLEN)
      *  122192 JTG ADDED SP-RBFRMLA = 'Q', VIRGINIA INS. ACTUARIAL
      *  011893 JTG SET B01-DEF-STOP FROM REB-DEF-STOP
      *              FOR CALIFORNIA, DEFERMENT REBATE ROUTINE
      *  012293 JTG ADDED SP-RBSPOPT1 = 10 FOR TIME FINANCE (CA)
      *                   TO BE USED WITH REFUND FORMULA 'L'
      *  021993 JTG ADDED SP-RBDEDCHG = 9999.03 FOR HOME CREDIT
      *  071993 JTG ADDED SP-RBSPOPT1 = 11 FOR MULLEN FINANCE (CA)
      *                   TO BE USED WITH REFUND FORMULA 'L'
      *  090193 JTG INCLUDED REM-REMTERM IN OUTPUT
      *  100793 BAH ADDED SP-RBEARLY = 99, FLAT CANCEL IF WITHIN
      *                                    3 DAYS, WORLD, TN
      *  082294 JTG CHANGED LOGIC FOR SP-RBREDUC = 9999.01 TO TEST
      *             SPECIFICLY FOR 'PB" OR "RN" OR "SC", SO CALLED
      *             PAYOFF WILL WORK
      *  113094 JTG ADDED SP-RBFRMLA = 'R' FOR TIME LOAN, CA AH REFUND
      *  021095 JTG ADDED SP-RBFRMLA = 'S' FOR TIME LOAN, CA CL REFUND
      *  051995 SLC ADDED SP-RBFRMLA = 'U' FOR AH REFUND FOR MERC.
      *  061095 JTG ADDED SP-RBEARLY = 9, FULL REFUND PRIOR TO START
      *             DATE (1ST - 30) MERCURY
      *  061595 JTG ADDED TEST ON BR-NOT-OURS-REFUND, MERCURY
      *  062795 JTG ADDED SP-RBEARLY = 10 (MERCURY) 1/30 78THS BF 1ST
      *  070295 SLC ADDED SP-RBFRMLA = 'V' AND 'W' FOR DEFER REFUND FOR MERC.
      *  070595 JTG CHANGED REBATE-FIND-INS-RATE TO TEST FOR INTERPOLATION
      *             OR NEXT HIGH
      *  092695 BAH ADDED SP-RBEARLY = 11 "MS" (MERCURY), FULL REFUND PRIOR
      *             TO FIRST PAY DATE, REFUNDISPRO RATA TO THE DAY
      *  101695 JTG ADDED SP-RBFRMLA = 'X', MERCURY 'WI' DEFERMENT REFUND
      *  101795 BAH ADDED SP-RBMIN(6) = 999.02, MERCURY 'OK' PP #L022
      *  111095 BAH ADDED SP-RBEARLY = 12 "AL" (MERCURY), PREPAID WITHIN 90
      *             DAYS BY COMPANY, PRO RATA TO THE DAY (SPREAR=1).
      *  111595 BAH ADDED SP-SPOPT1 = 12, MERCURY 'AL' INTEREST REFUND FORMULA
      *             ACTION SPRR78 = 13 RULE OF 78/PRIOR TO 1STPYDATE
      *  111695 BAH ADDED SP-RBFRMLA = "Y", MERCURY 'SC' DEF REFUND FORMULA
      *  111695 BAH ADDED SP-RBFRMLA = "Z", MERCURY 'AZ' DEF REFUND FORMULA
      *  112095 JTG CORRECTED SP-RBEARLY = 11, SO TRCD'S OTHER THAN
      *             'PO, PB, RN, SC' WOULD WORK
      *  112195 JTG ADDED SP-RBEARLY = 13, MERCURY NEVADA ACTION SPFRC=8
      *             FOR CUSTOMER PAYOFF
      *  111295 JTG ADDED SP-RBOPT1 = 13, ACTUARIAL 'F' NEAREST
      *             DUE DATE OPTION MERCURY ARIZONA ACTION 24
      *  112495 JTG ADDED SP-RBEARLY = 13 MERCURY 'NV' PP REFUND ACTION 8
      *  112795 JTG ADDED SP-RBREDUC = 9999.02, 'NV' MERCURY SPRDER = 09
      *  122195 BAH CHANGED FRMLA "U" TO USE IR RATE TABLE (MERCURY-CA)
      *             CALLS CL/IRREBT TO GET THE RATE
      *  011096 JTG ADDED SP-RBFRMLA2 = 1, MERCURY 'AZ' FIRE REFUND (PP)
      *  021296 JTG ADDED SP-RBSPOPT1 = 15, MERCURY 'OREGON' RULE OF
      *             ANTICIPATION
      *  050796 JTG CORRECTED REBATE-ACTUARIAL-F, SP-RBSPOPT1-FIRST-30,
      *             TO SET INTDATE TO NO LESS THAN ORIGINAL INTDATE
      *  051496 JF  INTEGRATED LIBGB/RBACT INTO REBATE-ACTUARIAL-F
      *  060596 JTG CORRECTED BUG IN ACTUARIAL-F WHICH DIDN'T PASS
      *             REB-TOTCHG TO RBACT-TOTCHG
      *  082996 BAH ADDED RBEARLY = 14, SUN, LA FOR ALABAMA
      *  020397 JTG CORRECTED RBFRMLA = 'V' & 'W' TO CORRECTLY COMPUTE
      *             DEFERMENT REFUND WHEN PAYOFF IS AFTER ORIGINAL LOAN
      *             MATURITY, REBATE-MERC-DAILY-PRORATA
      *  020497 JTG SP-RBEARLY = 10, CHANGED TO TEST FOR PAYDATE PRIOR
      *             TO INTEREST START DATE AND SET FULL REFUND
      *  021197 BAH SP-RBEARLY = 15, ALABAMA, SAME AS "MS" 12, EXCEPT 120 DAYS
      *             #L043
      *  021497 BAH ADDED A01-PAYDATE TO PERFORM REBATES INSIDE OF REBA01
      *  051397 JTG ADDED RBEARLY = 16, SUN, ALABAMA, JUST LIKE "MS" 3,
      *             EXCEPT 120 DAYS, PR#443
      *  051397 JTG ADDED SP-RBEARLY = 17, CLAY FINANCIAL SINGLE PAY LOANS ONLY
      *  062597 BAH ADDED SP-RBEARLY 18, 19 AND 20 FOR WORLD, A90-9,10 AND 11
      *  072997 MJD ADDED EARLY PROVISION FOR ACQUISITION CHARGES. REQ#163
      *  092697 JTG CHANGED TO ALLOW ADDON INTEREST REBATE TO WORK RBFRMLA = F
      *  100197 JTG ADDED LOGIC FOR SP-RBMINRET 9999.02 SC, WORLD
      *  020898 JTG CHANGED TO PASS REB-SKIPDEF-FG TO RBACT-SKIPDEF-FG
      *             IN REBATE-ACTUARIAL-F
      *  021098 JTG ADDED TEST OF REB-EARN-FULL-MONTH, TFC #637
      *             RE: SP-EARNACCRL-FG() = 'B'
      *  042798  CS ADDED TEST OF RENEWAL CODES "RB" AND "RO"
      *  102198 BAH ADDED SP-RBEARLY 22 FOR FREEDOM, AL #775, WITHIN 90 DAYS
      *             DO PRORATA, OTHERWISE, NO REFUND
      *  122198 JTG ADDED SP-RBSPOPT1 = 16 OHIO PREPAY PENALTY, REGENCY #001
      *  021299 BAH REMOVED THE CLEARING OF REB-MS-PENALTY ON THE FIRST
      *             LINE OF CODE, DOING A "PO", THE "RS" WIPED OUT THE
      *             PENALTY COMPUTED IN THE "RI", LOANS INC.
      *  021799 BAH ADDED DECIMAL TO REB-HALF-ORGTERM FOR DEDCHG 9999.02
      *  022699 BAH ADDED REB-HALF-ORGTERM-DEC AND DEDCHG 9999.04, AND PUT
      *             9999.02 BACK TO HOW IT WAS PRIOR TO 2/17/99 CHANGE
      *  JTG 990519 ADDED SP-RBFRMLA2 = '3', MEAN RULE 78THS       REGACC   #N/A
      *  BAH 990603 ADDED SP-RBEARLY = 23, WORLD (MO) #206
      *  BAH 990603 ADDED SP-RBSPOPT1 = 17, REGACC PR#875
      *  BAH 991021 ADDED SP-RBDEDCHG = 9999.05, HOME CREDIT, EXACTLY LIKE
      *             9999.03 EXCEPT $30.00 INSTEAD OF $25.00 PR#987
      *  JTG 000104 ADDED SET OF RBACT-PENALTY-FG RE: SP-RBREDUC = 9999.04
      *             WISCONSIN IB REAL ESTATE PREPAY PENALTY, WISCONSIN #1031
      *  JTG 000119 ADDED SP-RBFRMLA2 '4', TN PROPERTY REDUND (SHORT RATE
      *             METHOD) CONSUMER FINANCIAL #1062
      *  JTG 000317 CHANGED LOGIC FOR EP10 TO CARRY INITIAL CALC OF DAILY FACTOR
      *             TO MORE DECIMALS THAN 2 RE: WORLD BR 588 #01-006564
      *             WRITTEN UP BY AUDITORS
      *  JTG 000322 ALLOWED LOGIC FOR EP10 TO WORK FOR SERVICE CHARGE REFUNDS
      *             ALSO, RE: WORLD BR 588 #01-006564 WRITTEN UP BY AUDITORS
      *  BAH 000407 ADDED RBSPOPT1 = 18 MULLEN PR# 1118, IF REPO, RENEWED OR
      *             <= 60 DAYS, REBATE PRORATA
      *  KEC 000523 {PR#00000} MERCURY FINANCE [CINDY SHAFFER];
      *              ADDED 'B02-DEF-STOP' FOR THE PURPOSE OF NOT
      *              ALLOWING THE 'SEND-MESS' WITHIN CL/REBB02.C FROM
      *              HAPPENING SO THAT MERCURY CAN HAVE THEIR CUSTOMER
      *              STATEMENTS TO WORK (NOT STOPPING IN BATCH).
      *  JTG 000626 CORRECTED LOGIC FOR EP10 TO CARRY INITIAL CALC OF DAILY
      *             FACTOR TO MORE DECIMALS THAN 2 RE: WORLD BR 588 #01-006564
      *             WRITTEN UP BY AUDITORS, NO SERCHG REFUND FOR LOANS <= $100
      *  BAH 010413 ADDED SPOPT2 = 9 FOR FULL REFUND UP TO "SAME AS CASH" DATE
      *             LENDMARK PR# 1443
      *  JTG 010503 NEW CODE 'B' FOR SP-RBUNITPER-CD(OCCURS 16) PAACO PR#1466
      *  JTG 010706 ADDED SET OF REB-EARN-FULL-MONTH             REGENCY PR#1456
      *             RE: SP-ERNACCRL-FG() 'C'
      *  BAH 010910 ADDED RBSPOPT2 = 10, FULL REFUND WITHIN 60 DAYS, REGACC
      *             PR# 1550
      *  BAH 010928 RBREDUC = 9999.01, "MS" STATE BANK DEPT SAID WHENEVER
      *             THERE ARE REMAINING DAYS, BUMP INTO THE NEXT MONTH,
      *             WHICH COULD CAUSE A DIFFERENT PERCENT !!, PL# 334 LOANS
      *  JTG 011026 CHANGED RBACT-APRATE TO RBACT-RATE FOR NEW REFUND FORMULA
      *             '0 6'  AND CHANGED TO SET REB-LN-SMPRATE    REGENCY PR#1631
      *  JTG 011102 NEW DEFERMENT REFUND SP-RBFRMLA2 = 5 SMALL LOANS
      *                                                           CITIZENS #1622
      *  JTG 011107 PLUS NEW SP-RBFRMLA (0 7) CL & AH REFUNDS     MULLEN PR#1641
      *  JTG 020219 ADDED "CT" COUNTY TAX CODE KENTUCKY AND PERCENTS
      *             ADDED "CY" CITY   TAX CODE KENTUCKY AND PERCENTS
      *             ADDED LOGIC FOR INS-TAX                           WORLD #288
      *  JTG 020402 CHANGED INS-TAX TO INS-TAX-RB                     WORLD #288
      *  JTG 020930 ADDED NEW SHORT RATE FORMULA SP-RBEARLY = 24 (PP)    TFC #96
      *  JTG 030305 ALLOW RBFRMLA "8" TO WORK FOR A&H AND ALL INSURANCES
      *                                                               PACE #2012
      *  JTG 030513 ADDED SP-RBFRMLA2 (0 8) WISCONSIN CPI REFUND FORMULA
      *                                                           CITIZENS #2065
      *  JTG 030709 NEW INTEREST REFUND FORMULA (0 9) STATE OF TEXAS BASED
      *             ON DAILY INTEREST USING 365 DAYS AND SIMPLE      EXCEL #2111
      *  JTG 030717 CORRECTED INTEREST REFUND FORMULA (0 9) STATE OF TEXAS BASED
      *             ON DAILY INTEREST USING 365 DAYS AND SIMPLE
      *             STOPPED AMTFIN FROM GOING NEGITIVE               EXCEL #2111
      *  JTG 030728 NEW INSURANCE REFUND 2ND FORMULAS:
      *             (0 A) MEAN OF PRORATA & RULE 78
      *             (0 B) RULE 78 FOR NET + 1                        WORLD #326
      *  JTG 040603 MODIFY SP-RBSPOPT2 = 8, DO NOT SWING IF INS. COMPANY
      *             = 75, AND ROUND REFUND TO WHOLE DOLLARS         REGACC #0054
      *  JTG 040608 ADDED NEW SP-RBFRMLA (0 C) SHORT RATE FORMULA   MULLEN #2302
      *  BAH 040623 ADDED RBSPOPT1 = 21, THRIFT INVESTMENT PR# 2334
      *  JTG 040624 CHANGED 'REBATE-RBEARLY-21' TO CONSIDER A DEDUCT FROM CHARGE
      *             FOR COLORADO SERVICE CHARGE                       WORLD #353
      *  BAH 040630 REMOVED THE REGACC #0054 CHANGE DONE ON 040603 BY JTG
      *  JTG 040917 ADDED NEW FIELDS FOR SP-RBFRMLA (0 D)
      *             RULE 78THS USING DAYS IN TERM AND ELAPSED DAYS INSTEAD
      *             OF UNIT PERIODS IN TERM AND ELAPSE UNIT PERIODS
      *             ADDED REB-LN-INSEFF & REB-LN-INSEXP
      *             ALSO ADDED SP-RBSPOPT2 = 11 NEW ROUNDING OPTION TO
      *             TAKE COMPUTED REBATE AND ROUNDED UP OR DOWN TO
      *             WHOLE DOLLARS   ADDED 'REB-REBATE-CENTS'        REGACC #0074
      *  JTG 041102 ADDED ALAMAMA REFUND FRMLA ACTUARIAL (0 E)      WORLD  #J050
      *  JTG 041201 ALLOWED FORMULA (0 D) TO TEST FOR SWING OF 1 MONTH
      *             VIA ADD DAYS SP-RBDAYS(REB-SUB,1) FOR PRIOR TO
      *             FIRST PAYMENT                             REGACC #0074 #0454
      *  JTG 041220 ALLOWED FORMULA (0 D) TO TEST FOR SWING OF 1 MONTH
      *             VIA ADD DAYS SP-RBDAYS(REB-SUB,1) FOR PRIOR TO
      *             FIRST PAYMENT, THAN DO A FULL FULL REFUND REGACC #0074 #0454
      *             WHEN SPR FIELD SP-RBDAYS(REB-SUB,1) IS CODED FOR SWING
      *             AND ELAPSED DAYS PRIOR TO 1ST PAYMENT
      *             IS LESS THAN OR EQUAL TO SP-RBDAYS(REB-SUB,1) (NO SWING)
      *             FORCE A FLAT CANCEL, FULL REFUND
      *             NOTE: IF A SWING TAKES PLACE REB-ELAPSED-MONTHS WILL = 1
      *
      *             ---- TO  N O T  CAUSE A SWING LIKE IN THE FOLLOWING EX:
      *                  SPR 1STPAY YEAR TYPE SHOULD BE '360' NOT '365' ETC
      *
      *                                                360      365
      *                                 ------  ---      ---
      *                EFFECTIVE     08/29/04  DAYS     29       30
      *                REBATE DATE   09/28/04  MONTHS    0        1
      *                                        REM      29        0
      *                                               NO SWING  WILL SWING
      *                                                       REGACC #0074 #0454
      *  JTG 050210 CORRECTED LOGIC FOR REBATES AFTER INSURANCE EXPIRATION
      *             WHICH WAS CAUSING NEGATIVE DAYS-IN-FORCE AND
      *             YIELDED A POSITIVE REFUND   ---- WRONG -----
      *             FORMULA (0 D)                             REGACC #0074 #0454
      *  CS  050323 CHANGED REBATE-TX-INTEREST 'RI' TO 1ST PAYMENT DUE DATE
      *             WE WERE COMPUTING DAILY INTEREST FOR ELAPSED DAYS & THEN
      *             MULTIPLY BY -1 (?).  WHEN COMPUTING THE REBATE...
      *             (1.50 + LN-INTCHG + LN-EXTCHG - CALCULATED INTEREST) CALC
      *             INTEREST IS NEGATIVE SO IT ENDED UP ADDING TO REB-REBATE
      *FOR EX:      LOAN DATE   11/13/01
      *             1ST DUE     12/20/01
      *             'RI' DATE   12/20/01
      *             INTEREST    437.38
      *             EXTCHG         8.03
      *             CALCULATED INT  38.87
      *    WAS:
      *         (1.50) + 437.38 + 8.03 - (-38.87) SO REBATE 485.78 IS > INTCHG
      *    IT NOW DOES:
      *             (1.50) + 437.38 + 8.03 - 38.87 ( CALC INTEREST)= 408.04
      *                                                   DAVE SINCLAIR
      *  BAH 050405 ADDED SP-RBSPOPT1 = 22, SUN "LA" PR# 2504
      *             IF PAID BY "PB" OR "RN" REFUND RULE OF 78TH'S, IF PAID
      *             OFF WITH "PO", NO REFUND
      *  JTG 050418 NEW REFUND FORMULA '0 F' TRUE DAILY PRORATA REFUND FORMULA
      *             FOR STATE OF COLORADO                            WORLD #0401
      *  BAH 050518 STORE THE PENALTY IN REB-MS-PENALTY FOR THRIFT, MESSING
      *             UP DEFERMENT AMOUNT WITHOUT IT..., PL# 493
      *   CS 050523 NEW REBATE FORUMULA 2 (SP-RBFRMLA2 = H) SAME AS TEXAS 0 9
      *             EXCEPT USES THE SPLIT RATE TABLE ON PG 4 OF SPR #2527 REGMGT
      *             HARD CODED TO USE THE 1ST SPR TABLE(PG 4) PER JOHN WHEN
      *             I ASKED HIM HOW TO GET THE RIGHT TABLE
      *  JTG 050519 ADDED NEW FORMULAS FOR MEXICO
      *             SP-MFFRMLA-05 SP-RBFRMLA2 (G) SP-ERNFRMLA (24)   WORLD #0408
      *  JTG 050708 ADDED REB-LN-INT-REBATE REB-LN-SC-REBATE REB-LN-MF-REBATE
      *             REB-LN-DF-REBATE
      *             ADDED NEW FORMULAS FOR MEXICO
      *             SP-MFFRMLA-05 SP-RBFRMLA2 (G) SP-ERNFRMLA (24)   WORLD #0408
      *  JTG 050818 CHANGED SP-RBFRMLA2 (G) TO USE THE LN-ANTICERN(4)
      *             MAINTENANCE FEE ANTICIPATED INSTEAD OF THE STORED
      *             LN-MAINTFEE * LN-ORGTERM
      *             ADDED NEW FORMULAS FOR MEXICO
      *             SP-MFFRMLA-05 SP-RBFRMLA2 (G) SP-ERNFRMLA (24)   WORLD #0408
      *  BAH 050913 ALLOW SP-RBFRMLA2 (0 F) TO WORK WITH INSURANCES, PFSC
      *                SECURITY PR# 2600, LIBERAL PR# 2559
      *  CS  060203 ADD SP-RBSPOPT1 23 DONT ROUND TO WHOLE DOLLARS WHEN REFUND        *             IS REBATE-SHORT-RATE-0C [PEOPLE 2670]
      *  BAH 060213 WHEN THE CLEAR OF REB-MS-PENALTY WAS REMOVED FROM THE FIRST
      *             LINE(2/12/99), AND THE REFUND WAS 0, FULLY EARNED ALREADY,
      *             YOU WOULDNT GET INTO THE RBREDUC SECTION TO CLEAR THE
      *             PENALTY, SO IT WAS COMING OUT WITH JUNK LIKE 989762.88 IN
      *             IT ON MANUAL REBATES, SO I MOVED IT BACK UP TOP BUT ONLY
      *             CLEAR IT ON "RI"....LOANS INC PL# 529
      *   CS 060216 ADD SP-RBSPOPT1 = 24 USED IN CONJUNCTION WITH SP-RBFRMLA 0F
      *             REFUNDS 100% IF REFUNDED WITHIN 30 DAYS USES A 360 YR TYPE
      *                                                        PEOPLES 2680
      *   CS 060622 EARLY PROVISION 10 NEEDS TO WORK WITH ADDONS... IT WAS
      *             REBATING BACK ENTIRE LN-INTCHG IF REFUNDED WITH 10 DAYS
      *             & WASNT LOOKING AT THE ODDON CHARGE PR#534 CENTRAL ILL
      *             USE LT-ANTICERN(1)
      *   CS 060630 ADDED LT TO REBATE-CALL-SUBPROG SECTION CENTILL PR#534
      *  MJD 061207 ADDED SP-RBSPOPT1 = 25 OHIO PREPAY PENALTY, REGENCY #2878
      *  BAH 070814 ADDED SP-RBSPOPT1 = 26 TO USE APR INSTEAD OF SMPRATE
      *             ONLY IN RBFRMLA 'Q', LENDMARK PR# 3026
      *  JTG 071030 NEW INSURANCE REFUND FORMULA (0 I) FOR CPI POLICYS
      *             WHICH ARE ALWAYS 1 (ONE) YEAR TERMS          CITIZENS #3097
      *  MJD 080111 NEW INSURANCE REBATE FORMULA (0 J) FOR MX CL WORLD #563
      *   CS 080529 CHANGED  TEST FOR REBATE 78'S WITH FIRST PAY EXTENSION.
      *             WAS ADDING LN-EXTCHG TO REB-TOTCHG FOR ADDONS, THE LOAN
      *             EXT CHARGE SHOULD NOT AFFECT THE ADDON-REBATE SO...
      *             CHANGED TO :
      *             IF REB-ADDON-FG NOT = "Y"
      *                ADD LN-EXTCHG TO REB-TOTCHG.
      *             THIS WAS ALSO CAUSING CANCELS OF ADDON INTEREST > THAN
      *             ORIGINAL CHARGE
      *   CS 080603 DONT PERFORM EARLY PROVISION 10 (EP10) WHEN REFUNDING
      *             AN ADDON PR#630  CENTRAL ILL
      *  BAH 080910 ADDED RBFRMLA2 "K" FOR MULLEN PR# 3250
      *   CS 100304 ADDED RBFRMLA2 "L" FOR UNITED PR#3548, ACTS LIKE 0 9 EXCEPT
      *  BAH 100415 ADDED RBSPOPT2 12, FULL REFUND WITHIN 3 DAYS,
      *                                                         REGMGM PR# 3570
      *   CS 100805 CHANGED REBATE-ACTUARIAL-7-B IF REBATE-FRMLA 'B', TO COMPUTE
      *             THE RATE TO AMORTIZE THE LOAN USING UNITPER-PER-YEAR INSTEAD
      *             OF A MONTHLY RATE.  FOR THIS TO HAPPEN, SP-ORGST MUST BE
      *             'MX', MUST BE INTEREST REFUND, SP-RBUNITPER-CD = 'B'
      *                                                  WORLD PL#692
      *  100810 BAH ADDED SP-RBEARLY 25 FOR REGMGM, AL, WITHIN 90 DAYS DO
      *             PRORATA, OTHERWISE, DO SPR REFUND TABLE REGMGM PR# 3614
      *  BAH 100908 ADDED RBFRMLA2 "M" FOR WORLD TX ANTICIPATED PR# 711
      *             JUST LIKE RBFRMLA 8 WITHOUT TRUNCATING SPR RATE
      *   CS 110106 ADDED SP-RBEARLY 26 FOR WORLD, IL, IF PAID OFF BY "PO"
      *             WITHIN 60 DAYS, COMPUTE PRO-RATA REFUND, THIS IS THE SAME
      *             AS SP-RBEARLY 21 EXCEPT THAT IS ONLY CALCULATES A REFUND
      *             IF A 'PO'. ONLY FOR SERVICE CHARGE  WORLD PR#733
      *  110907  CS ADDED SP-RBEARLY = 98, FLAT CANCEL IF WITHIN 10 DAYS, IF
      *             > 10 DAYS, NO REFUND, DONT PUT A REBATE FORMULA IN SPR
      *             COMPONENT  REGMGM PR#3865
      *  110908  CS PER DAVID, FORCE 365 AS YEAR TYPE WITH SP-RBEARLY =98
      *                                                      REGMGM PR#3865
      *  111031 BAH ADDED SP-RBSPOPT2 = 13 FOR COLTN, PR# 3900
      *  120223 MJD ADDED REBATE FORMULA (0 N) FOR INDIANA,
      *             RULE OF ANTICIPATION LIFE                      CFSC #3795
      *  120502 MJD ADDED REBATE FORMULA (0 O) FOR TEXAS,
      *             RULE OF ANTICIPATION LIFE                      REGMGT #3938
      *  120517 MJD INSURANCE REBATE FORMULA 0-N TO USE A CONSTANTS
      *             RATE OF 3.7% AS THE STATE DISCOUNT RATE FOR THE
      *             CALCULATION OD LIFE INSURANCE REFUNDS.  AS PER RICHARD
      *             RODRIGUEZ AT ASSURANT.                         CFSC #4037
      *  120821 MJD CORRECTED RBFRMLA "O" (3938) TO ALWAYS USE FIXED
      *             RATE OF .035 RATHER THAN CALC BASED ON SPR DONE PER EMAIL
      *             FROM JIM R.
      *  130709 MJD ADDED EARLY PROVISION AND REBATE FOR GA 4% CLOSING FEE (54)
      *             THIS EARLY PROVISION IS ONLY UTILIZED BY SCFRMLA 54 AND
      *             RBFRMLA "I".                                    WORLD PR#920
      *             MODIFIED RBFRMLA "I" TO CALCULATE EARLY PROVISION AND
      *             THEN CALCULTE REBATE BASED ON THE REMAINING AMOUNT OF SERCHG
      *             4% CLOSING FEE STORED IN LN-POINTS              WORLD PR#876
      *  130913 BAH INSURANCE REBATE FORMULA 0-P TO USE A CONSTANT RATE OF
      *             1.42% AS THE STATE DISCOUNT RATE FOR THE CALCULATION OF
      *             LIFE INSURANCE REFUNDS.                      CFSC PR# 4367
      *  140117 MJD ADDED LOGIC FOR MX VYBA PREPAYMENT PENALTY      WORLD PR#954
      *  141010 MJD ADDED LOGIC FOR MX VYBA PREPYMNT PENALTY "PB"  WORLD PR#1030
      *  150611 BAH BOGUS JUNK CODE (:Q:F) SOMEHOW INSERTED IN THE
      *             REBATE-TX-INTEREST SECTION, ALONG WITH AN EXTRA GO TO
      *             STATEMENT WHICH CAUSED REBATE FORMULA 0 9 TO NOT WORK
      *                                                        SUPPORT PL#885
      *  160122 MJD WITHIN REBATE-EP54 CHANGED TO USE REB-EP54-AMT INSTEAD OF
      *             REB-WORK2 AS THE WORKER.  THIS VALUE NEED TO BE PART OF
      *             THE REBATE AND PASSED BACK TO BE STORED AND USED AT A
      *              LATER DATE.    REGMGT #4915
      *  160421 BAH CHANGED RBFRMLA2 "K" TO ALWAYS USE INSURANCE EFFECTE DATE
      *             AND INSURANCE TERM, NOT LOANDATE AND ORGTERM.
      *                                                  MULLEN/KSTREET PR#5049
      *  160511 MJD ADDED SP-RBDTE = "D"                             71105#0918
      *  CS 191204 ADD SP-RBEARLY 27 INDIANA EARLY PROVISION, NO REFUND OF
      *            EXTENSION CHARGE, FIRST MONTH INTEREST REBATED PRORATA 78'S
      *                                         WORLD PR#1406
      *            UNUSED DAYS FROM PAYDATE TO REFDATE(USED DAYS) COUNTED
      *            BY 365 YEAR TYPE AND SUBTRACTED FROM 30 TO GIVE US THE
      *            UNEARED PORTION OF THE SLICE OF EARNINGS
      *  2020.01.28 BAH ADDED SP-RBEARLY = 28, "IL" #1417
      *  2021.02.16 BAH CHANGE SPOPT1 = 3, IF B4 FIRST PAY, DO NOT INCLUDE THE
      *                 EXTENSION CHG IN THE REBATE CALC, IT SHOULD BE FULLY
      *                 REBATED INSTEAD. #1489
      *  2021.03.12 BAH SPOPT1 = 3, WAS INCLUDING "ON" THE FIRST PAY, SHOULD
      *                 ONLY BE PRIOR TO FIRST PAY. #1489A
      *  2021.0420 CS SP-RBFRMLA =0, SP-RBFRMLA2 = "H", PROBLEMS WITH INDEX
      *            OUT OF BALANCE IN REBATE-CALC-INT-0H. IT TESTS IF REBTX-
      *            STEP > 5, GO TO END BUT IF WAS = 5, IT ADDED 1 AND 
      *            CONTINUED TO TRY AND PROCESS RESULTING IN BAD REFUNDS, ERRORS
      *            ON INDEX THAT YOU DIDNT SEE UNLESS YOU WERE IN DEBUG. CHANGED
      *            INCREMENT OF REBTX-STEP TO HAPPEN PRIOR TO TEST AGAINST
      *            > 5.
      *  2021.0617 BAH ADDED SP-RBEARLY = 97, "TN" COMBINES RBEARLY 99 WITH
      *                AN EARLY PROVISION FOR NEW CLOSING FEE FROM SCFRMLA 60
      *                                                         #1500
      *  2021.0924 CS MOVED PERFORM OF EP11 BELOW THE SELECT-SP-ELAPSED-TIMTBL
      *               EP11 NEEDS TO KNOW IF PRIOR TO FIRST PAYMENT DUE DATE,
      *               (POFF-B4-1STPYDATE) WHICH IS REB-SUB2
      *               AS EP11 NEEDS TO KNOW IF PRIOR TO FIRST PAYMENT DUE DATE
      *               AS EP11 NEEDS TO KNOW IF PRIOR TO FIRST PAYMENT DUE DATE
      *  2022.0103 CS REMOVED BELOW, IT WILL NEVER HIT IT.  SP-RBFRMLA = "0" AND
      *               SP-RBFRMLA2 = "5", IS TESTED AS A DEFERMENT FORMULA AND 
      *               EXITS REBATE. YOU CANNOT ENTER ANYTHING OTHER THAN A 0 IN
      *               SP-RBFRMLA TO GET TO SP-RBFRMLA2. LOOKS LIKE WAS JUST
      *               COPIED FROM SP-RBFRMLA = "0" AND SP-RBFRMLA2 = "4"
      *               *** REMOVED*** WI SMALL LOAN DEFERMENT REFUND #1622
      *               IF SP-RBFRMLA2(REB-SUB) = "5"
      *                   PERFORM TN-PP-SHORT-RATE
      *  BAH 2023.0801 ADDED SP-RBFRMLA2 "Q" FOR "AL" CLOSING FEE #1619
      *   CS 2023.1012 IF WORLD DECIDES TO USE ADDONS, THE EARLY PROVISIONS
      *                NEED WORKED ON.  FOR EXAMPLE: RBEARLY(7) =19
      *                A REBATE IS CALCULATED ON THE ADDON PORTION AND SETS
      *                REB-SUB TO 0 WHICH IS A TRIGGER TO EXIT REBATE.
      *                PROBLEM WITH THAT IS WHEN YOU GET BACK TO FAPOFF:
      *                WITHIN PAYOFF-INT-ADDONS-NEXT, AFTER THE PERFORM OF
      *                ADDONRB-GET-IT-REBATE....
      *                    IF REB-SUB NOT = 0    ITS 0
      *                        MULTIPLY POFF-ONE BY REB-REBATE
      *                        ADD REB-REBATE TO POFF-ADDON-INT-REBATE
      *                    ELSE
      *                        MOVE 0 TO REB-REBATE. <----------
      *      IN THE CASE OF SP-RBEARLY(7) = 16 A NEW CALCULATION WOULD NEED
      *      TO BE ADDEDED IF REB-ADDON-FG = "Y" (SET IN FAPOFF) AS THIS
      *      RBEARLY FORMULA IS USING THE LN-LNAMT,LN-INTCHG,LN-EXTCHG BUT
      *      IS USING THE ELAPSED-DAYS FOR THE TIME PERIOD THE ADDON WAS IN
      *      EFFECT.
      **************************************************************************
       REBATE SECTION.
           MOVE 0 TO REB-REBATE REB-PRES-VALUE INS-TAX-RB REB-EP54-AMT.

      * ONLY CLEAR FOR INTEREST REBATE, OTHERWISE PAYOFF WILL WIPE IT OUT
      * WITH OTHER REBATES
           IF REB-SUB = 7
              MOVE 0 TO REB-MS-PENALTY.

           IF SP-RBFRMLA(REB-SUB) = "9" OR
              ( SP-RBFRMLA(REB-SUB) = " " AND
                SP-RBEARLY(REB-SUB) NOT = 99 AND NOT = 98 AND NOT = 97 )
              GO TO REBATE-EXIT.

      *    -------------------------------------------------------------
      *    EARLY PROVISION FOR ACQUISITION CHARGES
      *    -------------------------------------------------------------
           IF SP-RBEARLY(REB-SUB) = 21
              PERFORM REBATE-RBEARLY-21
              GO TO REBATE-EXIT.

           IF SP-RBEARLY(REB-SUB) = 26
              PERFORM REBATE-RBEARLY-26
              GO TO REBATE-EXIT.

           IF BR-NOT-OURS-REFUND NOT = "Y"
      *          TEST CL:
              IF (REB-SUB > 0 AND < 5) AND
                 (LN-INSOURS(1) = "N")
                 GO TO REBATE-EXIT
              ELSE
      *          TEST AH:
              IF ( REB-SUB = 5         ) AND
                 ( LN-INSOURS(2) = "N" )
                 GO TO REBATE-EXIT
              ELSE
      *          TEST PP/PP2:
              IF ( REB-SUB = 6 OR 11   ) AND
                 ( LN-INSOURS(3) = "N" )
                 GO TO REBATE-EXIT
              ELSE
      *          TEST O1 TO O7:
              IF ( REB-SUB > 10 AND < 19         ) AND
                 ( LN-INSOURS(REB-SUB - 8) = "N" )
                 GO TO REBATE-EXIT.

      * ---------------------------------------------------------
      * TEST FOR WINCONSIN DEFERMENT FORMULA 'X:
      * WHEN PAYOFF IS PRIOR TO ORIGINAL MATURITY
      * REFUND ALL DEFERMENT CHARGES:
      * ---------------------------------------------------------
              IF REB-SUB = 10
                 IF SP-RBFRMLA(REB-SUB) = "X"
      * REBATE ON ALL RENEWALS AND PAYOFF QUOTES 1/4/96 BAH
      *             IF REB-LPTRCD = "PO"
                       MOVE "Y" TO MDTE-FLAG
                       PERFORM MATURITY-DATE-CALCULATION
                       IF MDTE-DATE > REB-PAYDATE
                          MOVE LN-TOTDEF TO REB-REBATE
                          GO TO REBATE-EXIT.

      * IF SP-DBDTE = "D" AND ADDON-FG = "Y" CHECK TO SEE IF THE INS IN
      * QUESTION IS AN ADDON OR WAS PART OF THE ORIGINAL LOAN. THE
      * ADDON-FG IS A GENERAL FLAG AND NOT INSURANCE SPECIFIC, IF THE
      * INSURANCE IN QUESTION WAS NOT AN ADDON THEN DO NOT TREAT IT LIKE
      * ON REGARDLESS OF WHETHER OR NOT OTHER INSURANCES WERE ADDON
      * ON/ADJUSTED/CANCELLED.
      * THE TEST FOR SUB 1 AND 2 = D SEEMS WEIRD BUT THERE IS NO POINT
      * IN SEARCHING LT IF THERE IS NO POSSIBILITY OF EITHER BEING "D"
      * IF PAYOFF LPPOFF ALREADY SETS UP THE REB-LN FIELDS, WE JUST DO
      * NOT WANT TO USE THEM ID THE INS IN QUESTION REALLY IS NOT AN ADDON.
      *  ALSO IF IT IS A PAYOFF, THE REB-LN-ORIG-1STPYDATE IS ALREADY
      * CHANGED TO INS EFF DATE BY THE TIME IT GETS HERE.
      *                                                  71105#0918
           IF (REB-ADDON-FG = "Y") AND
                 ((SP-RBDTE(REB-SUB, 1) = "D") OR
                  (SP-RBDTE(REB-SUB, 2) = "D"))
      *  DO ANY LOAN INS TRAILERS EXIST FOR THIS INSURANCE?
              PERFORM REBATE-CHECK-ADDON-TRAILER
              IF REB-LTI-ADDON-NOT-FOUND
      * WANT TO TEST USING LN-ORIG-1STPYDATE THIS INS IS NOT AN ADDON.
                 MOVE REB-LN-ORIG-1STPYDATE TO REB-HOLD-LNORIG1STPAY
                 MOVE LN-ORIG-1STPYDATE TO REB-LN-ORIG-1STPYDATE
      * SETUP REB-SUB2
                 PERFORM SELECT-SP-ELAPSED-TIMTBL
                 IF JULIAN-DATE = 0
                    GO TO REBATE-EXIT
                 ELSE
      * IF CONDITIONS ARE MET CONTINUE AS THOUGH ADDON-FG = "N"
                    IF SP-RBDTE(REB-SUB, REB-SUB2) = "D"
                       MOVE "N" TO REB-ADDON-FG
                    END-IF
                 END-IF
                 MOVE REB-HOLD-LNORIG1STPAY TO REB-LN-ORIG-1STPYDATE
              END-IF
           END-IF.

      *^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      * THIS SECTION OF CODE IS FOR ESTABLISHMENT OF ORIG LOAN FIELDS.
      *  NOTE: WHEN REB-ADDON-FG = "Y", IT IS ASSUMED THAT THESE FIELDS
      *        HAVE BEEN PRESET TO THE CORRECT VALUES FOR THE ADDON.
      *

           IF REB-ADDON-FG NOT = "Y"
              MOVE LN-ORIG-1STPYDATE TO REB-LN-ORIG-1STPYDATE
              MOVE LN-PURDATE     TO REB-LN-PURDATE
              MOVE LN-LOANDATE    TO REB-LN-LOANDATE
              MOVE LN-INTDATE     TO REB-LN-INTDATE
              MOVE LN-APRATE      TO REB-LN-APRATE
              MOVE LN-TOTNODEF    TO REB-LN-TOTNODEF
              IF REB-SUB < 5
                 MOVE LN-INSCOVR(1) TO REB-LN-INSCOVR
                 MOVE LN-INSEFF-DATE(1)  TO REB-LN-INSEFF
                 MOVE LN-INSEXP-DATE(1)  TO REB-LN-INSEXP
              ELSE
                IF REB-SUB = 6
                   MOVE LN-INSCOVR(3) TO REB-LN-INSCOVR
                   MOVE LN-INSEFF-DATE(3)  TO REB-LN-INSEFF
                   MOVE LN-INSEXP-DATE(3)  TO REB-LN-INSEXP
                ELSE
                  IF REB-SUB > 11 AND < 17
                     MOVE LN-INSCOVR(REB-SUB - 8) TO REB-LN-INSCOVR
                     MOVE LN-INSEFF-DATE(REB-SUB - 8)  TO REB-LN-INSEFF
                     MOVE LN-INSEXP-DATE(REB-SUB - 8)  TO REB-LN-INSEXP
                  ELSE
                     MOVE LN-INSCOVR(2) TO REB-LN-INSCOVR
                     MOVE LN-INSEFF-DATE(2)  TO REB-LN-INSEFF
                     MOVE LN-INSEXP-DATE(2)  TO REB-LN-INSEXP
                  END-IF
                END-IF
              END-IF
              MOVE LN-SALEFIN     TO REB-LN-SALEFIN

              MOVE LN-SMPRATE     TO REB-LN-SMPRATE
              MOVE LN-ORGTERM     TO REB-LN-ORGTERM
              MOVE LN-1STPYAMT    TO REB-LN-1STPYAMT
              MOVE LN-REGPYAMT    TO REB-LN-REGPYAMT
              MOVE LN-LASTPYAMT   TO REB-LN-LASTPYAMT.

           IF REB-SUB = 7 AND LN-CONVERCD = "X"
              IF LN-ADDON-FG NOT = "Y"
                      AND LN-FINCHG = LN-SUM-FINCHG
                 MOVE LN-ANTICERN(1) TO REB-TOTCHG
              ELSE
                 MOVE LN-OLDACCTNO TO REB-LN-PURDATE
                                      REB-LN-INTDATE
                                      REB-LN-LOANDATE
                                      NDTE-DATE
                 MOVE LN-PRLNNO TO REB-ORGTERM
                 MOVE 1 TO NDTE-HOLD
                 PERFORM INCREMENT-MONTHS
                 MOVE NDTE-DATE TO REB-LN-ORIG-1STPYDATE
                 COMPUTE REB-TOTCHG =
                    LN-ANTICERN(1) + LN-ANTICADJ(1) - LN-UFERN(1).

      *
      ***********   SET UNIT PERIOD INFO   **************************
            MOVE LN-UNITPER-CD      TO UPER-UNITPER-CD.
            MOVE LN-UNITPER-FREQ    TO UPER-UNITPER-FREQ.
            MOVE REB-LN-INTDATE     TO UPER-INTDATE.
            MOVE REB-LN-ORIG-1STPYDATE TO UPER-1STPYDATE.
            MOVE REB-ORGTERM        TO UPER-TERM.
            PERFORM UPER-CALCULATION.
      *^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      * IF SP-RBUNITPER-CD(REB-SUB) = "A"
      *    IF OTHER THAN MONTHLY PAY CODE OR PAYFREQ CONVERT BACK TO MONTHLY

            IF SP-RBUNITPER-CD(REB-SUB) = "A"
               IF NOT (
                       LN-UNITPER-CD = "M"
                           AND LN-UNITPER-FREQ = 1
                      )
                  COMPUTE REB-ORGTERM =
                       REB-ORGTERM / UPER-UNITPER-PER-YEAR * 12
                  IF REB-LN-TOTNODEF NOT = 0
                     MOVE LN-UNITPER-CD   TO UPWK-UNITPER-CD
                     MOVE LN-UNITPER-FREQ TO UPWK-UNITPER-FREQ
                     PERFORM UPWK-DEF-CALC
                     DIVIDE UPWK-UNITPER-WK INTO REB-LN-TOTNODEF.

      *^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      * IF SP-RBUNITPER-CD(REB-SUB) = "B"
      *    IF OTHER THAN MONTHLY PAY CODE OR PAYFREQ
      *       COMPUTATION OF ELAPSED-MONTHS, ETC WILL BE DONE ON
      *       UNIT PERIOD BASES
      *^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

      * TEST FOR TENN, CALIF, INDIANA, S. CAROLINA DEFERMENT REBATE:
           IF SP-RBFRMLA(REB-SUB) = "E" OR "O" OR "K"
                                 OR "M" OR "Y" OR "Z"
              PERFORM REBATE-DEFERMENT-EOKMYZ05
              GO TO REBATE-EXIT.

      * TEST FOR WISCONSIN DEFERMENT REBATE:
           IF SP-RBFRMLA(REB-SUB)  = "0" AND
              SP-RBFRMLA2(REB-SUB) = "5"
              PERFORM LOAN-CALCULATIONS
              IF (FINANCED-AMOUNT > 4999.99) OR
                 (LN-ORGTERM      > 36     )
                 MOVE LN-TOTDEF TO REB-REBATE
              ELSE
                 PERFORM REBATE-DEFERMENT-EOKMYZ05
              END-IF
              GO TO REBATE-EXIT.

      * TEST FOR REBATE 78THS WITH 1ST PAYMENT EXTENDED:
           IF SP-RBFRMLA(REB-SUB) = "3" OR "N"
              IF SP-RBEARLY(REB-SUB) NOT = 7
                 IF SP-RBSPOPT1(REB-SUB) NOT = 3
                    IF REB-ADDON-FG NOT = "Y"
                       ADD LN-EXTCHG TO REB-TOTCHG.

      * TEST FOR REBATE '0 9' THAT WILL INCLUDE 1ST PAYMENT EXTENSION: 'EXCEL'
           IF SP-RBFRMLA2(REB-SUB) = "9" OR
               SP-RBFRMLA2(REB-SUB) = "G"
              ADD LN-EXTCHG TO REB-TOTCHG.

      * TEST FOR REBATE 78THS W/1ST PMT EXT + DEFERMENTS:
           IF SP-RBFRMLA(REB-SUB) = "A"
              ADD LN-EXTCHG LN-TOTDEF TO REB-TOTCHG.

      * TEST FOR ACTUARIAL REBATE W/1ST PMT EXT + SERVICE CHGI
      * BUT NOT IF CALCULATED FOR EARNINGS LPCERN OR LPAERN:
           IF REB-SKIPDEF-FG NOT = "Y"
              IF SP-RBFRMLA(REB-SUB) = "D" OR "F"
                 ADD LN-EXTCHG LN-SERCHG TO REB-TOTCHG.

      * TEST FOR EARLY PAYOFF EXCEPTIONS:
           IF SP-RBEARLY(REB-SUB) NOT = 0
      *    TEST FOR MISSISSIPPI COMPANY PAYOFF PRORATA REBATE:
      *    TEST FOR ALABAMA COMPANY PAYOFF PRORATA REBATE( 90DAYS):
      *    TEST FOR ALABAMA COMPANY PAYOFF PRORATA REBATE(120DAYS):
              IF SP-RBEARLY(REB-SUB) = 3 OR 12 OR 15 OR 16
                 PERFORM REBATE-EP3
                 IF REB-SUB = 0
                    GO TO REBATE-EXIT
                 ELSE
                    NEXT SENTENCE
              ELSE
      * WORLD SOUTH CAROLINA COMPANY PAYOFF PRORATA INTEREST REBATE:
              IF SP-RBEARLY(REB-SUB) = 19
                 PERFORM REBATE-EP19
                 IF REB-SUB = 0
                    GO TO REBATE-EXIT
                 ELSE
                    NEXT SENTENCE
              ELSE
      * WORLD SOUTH CAROLINA SERVICE CHARGE REBATE:
              IF SP-RBEARLY(REB-SUB) = 20
                 PERFORM REBATE-EP20
                 IF REB-SUB = 0
                    GO TO REBATE-EXIT
                 ELSE
                    NEXT SENTENCE
              ELSE
      * TEST FOR ALABAMA PRIOR TO 90 DAY REBATE (SUN) :
              IF SP-RBEARLY(REB-SUB) = 14
                 PERFORM REBATE-EP14
                 GO TO REBATE-EXIT
              ELSE
      * TEST FOR ALABAMA PRIOR TO 90 DAY REBATE (FREEDOM) :
              IF SP-RBEARLY(REB-SUB) = 22
                 PERFORM REBATE-EP22
                 GO TO REBATE-EXIT
              ELSE
      * REGMGM ALABAMA, LIKE 22 EXCEPT AFTER 90 DAYS, USE SPR TABLE
              IF SP-RBEARLY(REB-SUB) = 25
                 PERFORM REBATE-EP22
                 IF REB-SUB = 0
                    GO TO REBATE-EXIT
                 ELSE
                    NEXT SENTENCE
              ELSE
                 IF SP-RBEARLY(REB-SUB) = 99
                    MOVE REB-SUB TO REB-SUB2
                    PERFORM REBATE-EARLY-99
                    IF REB-SUB2 = 0
                      GO TO REBATE-EXIT
                    ELSE
                      NEXT SENTENCE
                 ELSE
                  IF SP-RBEARLY(REB-SUB) = 97
                    MOVE REB-SUB TO REB-SUB2
                    PERFORM REBATE-EARLY-97
                    IF REB-SUB2 = 0
                      GO TO REBATE-EXIT
                    ELSE
                      NEXT SENTENCE
                  ELSE
                  IF SP-RBEARLY(REB-SUB) = 98
                     MOVE REB-SUB TO REB-SUB2
                     PERFORM REBATE-EARLY-98
                     IF REB-SUB2 = 0
                       GO TO REBATE-EXIT.



      * IF ON OR BEFORE START DATE, FULL REFUND (MERCURY),
      * WHERE START DATE IS 1 MONTH FROM 1ST PAY DATE:
           IF SP-RBEARLY(REB-SUB) = 9
              MOVE REB-PAYDATE TO NUM-DATE
              MOVE LN-ORIG-1STPYDATE TO SYS-DATE
              PERFORM TIM360
              IF ELAPSED-MONTHS > 0
                 MOVE REB-TOTCHG TO REB-REBATE
                 GO TO REBATE-EXIT.

      * REBATE FORMULA2 "Q" "AL" CLOSING FEE
      *  THEY ALSO USE RBEARLY 99 FOR A FULL REFUND OF SERVICE CHARGE SO
      *  THIS CHECK MUST STAY BELOW TESTING FOR THAT.
      * IF RBFRMLA2 = "Q", AND IT ISNT WITHIN THE EARLY PROVISION OF 99,
      *  THEN YOU ARE ONLY REFUNDING THE CLOSING FEE (LN-POINTS)
           IF SP-RBFRMLA2(REB-SUB) = "Q"
              MOVE LN-POINTS TO REB-TOTCHG.

      *************************************************************
      *NORMAL:
      *  ESTABLISH REB-SUB2 PER REBATE DONE [BEFORE (1)]
      *  OR [ON OR AFTER (2)] 1STPAYDATE:
      *MISSISSIPPI OPT1=4:
      *  ESTABLISH REB-SUB2 PER REBATE DONE [ON OR BEFORE (2)]
      *  OR [AFTER (2)] 1STPAYDATE:
      *************************************************************
           PERFORM SELECT-SP-ELAPSED-TIMTBL.
           IF JULIAN-DATE = 0
              GO TO REBATE-EXIT.

      *THIS WAS BEING PERFORMED ABOVE THE SELECT-SP-ELAPSED-TIMTBL.
      *IT NEEDS TO COME AFTER THAT AS WE NEED TO KNOW IF PAYING PRIOR TO
      *1ST PAYMENT DUE(POFF-B4-1STPYDATE) WHICH IS SET IN 
      *SELECT-SP-ELAPSED-TIMTBL
      * TEST FOR MERCURY MISSISSIPPI PRORATA REBATE:
           IF SP-RBEARLY(REB-SUB) = 11
              PERFORM REBATE-EP11
              IF REB-SUB = 0
                 GO TO REBATE-EXIT.

      *   TEST FOR CLAY FINANCIAL, SINGLE PAY 78TH:
           IF SP-RBEARLY(REB-SUB) = 17
              PERFORM REBATE-EP17
              IF REB-SUB = 0
                 GO TO REBATE-EXIT.

      *  TEST FOR MISSISSIPPI 90 DAY RULE;
      *  AND FOR MERCURY ALABAMA INTEREST REFUND
      * IF SO WHEN PAYOFF IS ON OR BEFORE 1ST PAYDATE
      * INCLUDE 1ST PAY EXTENSION CHARGE:
           IF PODATE-B4-1STPYDATE
              IF SP-RBSPOPT1(REB-SUB) = 4 OR 12
                 ADD LN-EXTCHG TO REB-TOTCHG.

      * GET REBATE REFERENCE DATE:
           PERFORM REBATE-REFDATE.
           IF REB-REFDATE = 0
              MOVE 0 TO REB-SUB
              GO TO REBATE-EXIT.


      * CALCULATE ELAPSED TIME FROM REF THRU PAYDATE:
           PERFORM CALC-ELAPSED-REF-THRU-PODATE.
           IF JULIAN-DATE = 0
              MOVE 0 TO REB-SUB
              GO TO REBATE-EXIT.

      * TEST TO SEE IF PAYOFF IS PRIOR TO REF-DATE:
           IF REB-ELAPSED-DAYS NOT > 0
              IF NOT (REB-HOLD-RBDTE = "C" OR "D")
                            OR SP-RBEARLY(REB-SUB) = 7
                 MOVE 0 TO REB-ELAPSED-REM
                           REB-ELAPSED-MONTHS
              ELSE
                 IF REB-PAYDATE NOT = REB-LN-INTDATE
                    MOVE 0 TO REB-ELAPSED-MONTHS
                    MOVE 1 TO REB-ELAPSED-REM.

      * TEST FOR HOME CREDIT (NC), IF ELAPSED DAYS < 31
      * FULL REFUND:
           IF SP-RBDEDCHG(REB-SUB) = 9999.03 OR 9999.05
              IF REB-ELAPSED-DAYS < 31
                 MOVE REB-TOTCHG TO REB-REBATE
                 GO TO REBATE-EXIT.

           IF SP-RBSPOPT2(REB-SUB) = 12
              IF REB-ELAPSED-DAYS NOT > 3
                 MOVE REB-TOTCHG TO REB-REBATE
                 GO TO REBATE-EXIT.
           IF SP-RBSPOPT2(REB-SUB) = 4
              IF REB-ELAPSED-DAYS NOT > 10
                 MOVE REB-TOTCHG TO REB-REBATE
                 GO TO REBATE-EXIT.
           IF SP-RBSPOPT2(REB-SUB) = 5
              IF REB-ELAPSED-DAYS NOT > 15
                 MOVE REB-TOTCHG TO REB-REBATE
                 GO TO REBATE-EXIT.
      * TEST FOR LIBERAL/ARROW FULL REFUND IF PAYOFF WITHIN 30 DAYS:
           IF SP-RBSPOPT2(REB-SUB) = 6
              IF REB-ELAPSED-DAYS NOT > 30
                 MOVE REB-TOTCHG TO REB-REBATE
                 GO TO REBATE-EXIT.
           IF SP-RBSPOPT2(REB-SUB) = 10
              IF REB-ELAPSED-DAYS NOT > 60
                 MOVE REB-TOTCHG TO REB-REBATE
                 GO TO REBATE-EXIT.

      * LENDMARK * FULL REFUND UP TO "SAME AS CASH" DATE
           IF SP-RBSPOPT2(REB-SUB) = 9
              IF REB-PAYDATE NOT > LN-CASHDATE
                 MOVE REB-TOTCHG TO REB-REBATE
                 GO TO REBATE-EXIT.

      * PEOPLES * FULL REFUND IF PAID WITHIN 30 DAYS
      *         * USES 360 YEAR IN TIME CALCULATIONS
           IF SP-RBSPOPT1(REB-SUB) = 24
              IF ELAPSED-DAYS NOT > 30
                 MOVE REB-TOTCHG TO REB-REBATE
                 GO TO REBATE-EXIT.

           PERFORM REBATE-TEST-SWING.

           PERFORM REBATE-DEDUCT-CHARGE.

           IF SP-RBEARLY(REB-SUB) = 2
              IF PODATE-B4-1STPYDATE
                 PERFORM REBATE-EP2
                 GO TO REBATE-EXIT.

      * PR1406 "IN"
           IF SP-RBEARLY(REB-SUB) = 27
              IF LN-EXTCHG NOT = 0
                 IF PODATE-B4-1STPYDATE
                    PERFORM REBATE-EP27
                    GO TO REBATE-EXIT.


           IF SP-RBEARLY(REB-SUB) = 18
              IF (LN-LNAMT - LN-INTCHG - LN-SERCHG - LN-EXTCHG)
                                                         < 100.01
                 MOVE 0 TO REB-REBATE
                 GO TO REBATE-EXIT
              ELSE
                 IF PODATE-B4-1STPYDATE
                    PERFORM REBATE-EP18
                    GO TO REBATE-EXIT.

           IF SP-RBEARLY(REB-SUB) = 10
              IF REB-SUB = 7
                 IF REB-ADDON-FG = "Y"
                    MOVE LTI-ANTICERN(1)   TO REB-TOTCHG
                 ELSE
                    MOVE LN-INTCHG TO REB-TOTCHG
                 END-IF
              END-IF
              IF REB-SUB = 8
                 IF (LN-LNAMT - LN-INTCHG - LN-SERCHG - LN-EXTCHG)
                                                         < 100.01
                    MOVE 0 TO REB-REBATE
                    GO TO REBATE-EXIT
                 END-IF
              END-IF
              IF PODATE-B4-1STPYDATE
                 IF REB-ADDON-FG NOT = "Y"
                 PERFORM REBATE-EP10
                 GO TO REBATE-EXIT.

      * WORLD MISSOURI 6/03/1999 23
      * WORLD ILLINOIS 1/28/2020 28
           IF SP-RBEARLY(REB-SUB) = 23 OR 28
              MOVE LN-INTCHG TO REB-TOTCHG
              IF PODATE-B4-1STPYDATE
                 PERFORM REBATE-EP23-28
                 GO TO REBATE-EXIT.


      * TEST FOR MERCURY NEVADA PRORATA REBATE:
           IF SP-RBEARLY(REB-SUB) = 13
              PERFORM REBATE-EP13
              IF REB-SUB = 0
                 GO TO REBATE-EXIT.

      * TEST FOR TFC PHYSICAL DAMAGE COVERAGE SHORT RATE REBATE:
           IF SP-RBEARLY(REB-SUB) = 24
              PERFORM REBATE-EP24
              IF REB-SUB = 0
                 GO TO REBATE-EXIT.


      * INTSUB IS INT LEVEL OF INS/INT ARRAY; MUST COME LAST
           IF REB-SUB < 1 OR > 18 OR REB-PAYDATE = 0
              MOVE 0 TO REB-SUB
              GO TO REBATE-EXIT.

           IF REB-TOTCHG NOT > 0 OR SP-RBFRMLA(REB-SUB) = " "
              GO TO REBATE-EXIT.
           IF REB-ADDON-FG = "Y" AND REB-SUB = 7
              NEXT SENTENCE
           ELSE
              IF REB-DEDCHG > REB-TOTCHG
                 GO TO REBATE-EXIT.

      * TEST FOR ACTUARIAL-IB-REBATE:
           IF SP-RBFRMLA(REB-SUB) = "6"
              PERFORM REBATE-ACTUARIAL-IB
              PERFORM REBATE-ADJUST-REB-REBATE
              GO TO REBATE-EXIT.

      * SKIP THIS TEST FOR (0 I)
           IF NOT ( SP-RBFRMLA(REB-SUB)  = "0" AND
                    SP-RBFRMLA2(REB-SUB) = "I"
                  )
      * BELOW THIS FLOOR CONSIDERED FULLY EARNED
              IF REB-REMTERM < SP-RBNOMON(REB-SUB)
                 IF NOT (SP-RBFRMLA(REB-SUB) = "D" OR "F")
                    GO TO REBATE-EXIT.

           IF REB-RECAST = "Y" AND SP-RBRECAST(REB-SUB) = 1
              MOVE "C" TO REB-FORM-PROG-TYPE
              MOVE 01 TO REB-FORM-PROG-NO
              PERFORM REBATE-CALL-SUBPROG
              IF REB-COMMON-RTNCD = " "
                 MOVE REB-COMMON-REBATE TO REB-REBATE
                 GO TO REBATE-END-ADJ
              ELSE
                 MOVE 0 TO REB-REBATE REB-SUB
                 GO TO REBATE-EXIT.

      * CHOOSE REBATE METHOD:
           IF SP-RBSPOPT2(REB-SUB) = 1
              IF REB-LPTRCD = "PB" OR "RN" OR "SC"
                                OR "RB" OR "RO"
                 PERFORM REBATE-PRORATA
                 GO TO REBATE-END-ADJ.

           IF SP-RBSPOPT2(REB-SUB) = 3
              IF REB-LPTRCD = "RI"
                 PERFORM REBATE-PRORATA
                 GO TO REBATE-END-ADJ.

      * WDT 1-18-96
           IF SP-RBSPOPT2(REB-SUB) = 7
              IF REB-LPTRCD = "PB" OR "RN" OR "RB" OR "RO"
                 PERFORM REBATE-ACTUARIAL-F-06
                 GO TO REBATE-END-ADJ.

      * COLTN 10/31/2011 PR# 3900
      *  IF RENEWAL, USE FMLA "F", IF PAYOFF WITHIN 24 MONTHS, USE SPR,
      *   OTHERWISE USE "F"
           IF SP-RBSPOPT2(REB-SUB) = 13
              IF REB-LPTRCD = "PB" OR "RN" OR "RB" OR "RO" OR "SC"
                 PERFORM REBATE-ACTUARIAL-F-06
                 GO TO REBATE-END-ADJ
              ELSE
              IF REB-LPTRCD = "PO"
      * IF PAYOFF WITHIN 24 MONTHS, FALL THRU HERE AND USE SPR
      * IF PAYOFF > 24 MONTHS, USE FORMULA "F"
                 IF REB-ELAPSED-MONTHS > 24
                    PERFORM REBATE-ACTUARIAL-F-06
                    GO TO REBATE-END-ADJ.

      * SUN, LA IF PAID BY "PB" OR "RN" REFUND RULE OF 78TH'S, IF PAID
      *         OFF WITH "PO", NO REFUND
           IF SP-RBSPOPT1(REB-SUB) = 22
               IF REB-LPTRCD = "PO"
                 MOVE 0 TO REB-REBATE
                 GO TO REBATE-END-ADJ.

      * MULLEN, CA IF REPO REBATE PRORATA, EXACT DAILY:
           IF SP-RBSPOPT1(REB-SUB) = 7
              IF (LN-REPOCD = "X" OR "S")
                         OR (REB-LPTRCD = "PB" OR "RN"
                             OR "RB" OR "RO")
                 PERFORM REBATE-PRORATA-EXACT
                 GO TO REBATE-END-ADJ.

      * MULLEN, CA IF REPO, RENEWED OR <= 60 DAYS, REBATE PRORATA,
      *            EXACT DAILY:
           IF SP-RBSPOPT1(REB-SUB) = 18
              IF (LN-REPOCD = "X" OR "S") OR
                   (REB-LPTRCD = "PB" OR "RN" OR "RB" OR "RO") OR
                     (REB-ELAPSED-DAYS NOT > 60)
                 PERFORM REBATE-PRORATA-EXACT
                 GO TO REBATE-END-ADJ.

      * REGIONAL ACCPT, IF REPO, REBATE PRORATA, MONTHLY:
           IF SP-RBSPOPT1(REB-SUB) = 17
              IF (LN-REPOCD = "X" OR "S")
                 PERFORM REBATE-PRORATA
                 GO TO REBATE-END-ADJ.

      **** BEGINNING OF RBFRMLA PERFORMS: ***

           IF SP-RBFRMLA(REB-SUB) = "1" OR SP-RBFRMLA2(REB-SUB) = "Q"
              PERFORM REBATE-78
           ELSE
           IF SP-RBFRMLA(REB-SUB) = "2"
              PERFORM REBATE-ACTUARIAL-2
           ELSE
      * EXT. CHARGE HAS ALREADY BEEN ADDED IN:
           IF SP-RBFRMLA(REB-SUB) = "3" OR "N"
              PERFORM REBATE-78
           ELSE
           IF SP-RBFRMLA(REB-SUB) = "4"
              PERFORM REBATE-ANTICIPATED
           ELSE
           IF SP-RBFRMLA(REB-SUB) = "5"
              PERFORM REBATE-PRORATA
           ELSE
      * ACTUARIAL USING WHOLE MONTHS ONLY:
           IF SP-RBFRMLA(REB-SUB) = "7" OR "B"
              PERFORM REBATE-ACTUARIAL-7-B
           ELSE
      * INSURANCE ANTICIPATED:
           IF SP-RBFRMLA(REB-SUB) = "8"
              PERFORM REBATE-INS-ANTICIPATED
           ELSE
      * NOTE:  EXT. CHARGE AND DEFERMENTS HAVE ALREADY
      *        BEEN ADDED IN IF SP-RBFRMLA(REB-SUB) = "A"
           IF SP-RBFRMLA(REB-SUB) = "A"
              PERFORM REBATE-78
           ELSE
           IF SP-RBFRMLA(REB-SUB) = "C"
              PERFORM REBATE-ACTUARIAL-C
           ELSE
           IF SP-RBFRMLA(REB-SUB) = "D"
              PERFORM REBATE-ACTUARIAL-D
           ELSE
           IF SP-RBFRMLA(REB-SUB) = "F"
              PERFORM REBATE-ACTUARIAL-F-06
           ELSE
      * MASS. A&H ANTICIPATED (IDEAL):
           IF SP-RBFRMLA(REB-SUB) = "G"
              PERFORM REBATE-MA-AH-ANTICIPATED
           ELSE
      * "H" (GA) SERCHG REBATE (ROGER WILLIAMS)
      * "I" (GA)   "      "    (JOE DOUGLAS SR):
           IF SP-RBFRMLA(REB-SUB) = "H" OR "I"
              PERFORM REBATE-GA-SC
           ELSE
      * MULLEN, CA INSURANCE:
           IF SP-RBFRMLA(REB-SUB) = "J"
              PERFORM REBATE-PRORATA-EXACT
           ELSE
      * MULLEN, CA A&H ANTICIPATED:
           IF SP-RBFRMLA(REB-SUB) = "L"
              PERFORM REBATE-CA-AH-ANTICIPATED
           ELSE
      * UVALDE, TX A&H ANTICIPATED:
           IF SP-RBFRMLA(REB-SUB) = "P"
              PERFORM REBATE-TX-ANTICIPATED
           ELSE
      * INSURANCE ACTUARIAL (VA) USING WHOLE MONTHS ONLY:
           IF SP-RBFRMLA(REB-SUB) = "Q"
              PERFORM REBATE-ACTUARIAL-Q
           ELSE
      * TIME LOAN, CA A&H ANTICIPATED:
           IF SP-RBFRMLA(REB-SUB) = "R"
              PERFORM REBATE-CA-ANTICIPATED
           ELSE
      * TIME LOAN, CA 'CL' ANTICIPATED REFUND:
           IF SP-RBFRMLA(REB-SUB) = "S"
              PERFORM REBATE-CA-CL-ANTICIPATED
           ELSE
      * LIBERAL NJ TABLE FORMULA:
           IF SP-RBFRMLA(REB-SUB) = "T"
              PERFORM REBATE-TABLE-FORMULA
           ELSE
      * MERCURY A&H ANTICIPATED :
           IF SP-RBFRMLA(REB-SUB) = "U"
              PERFORM REBATE-MERC-AH-ANTIC
           ELSE
      * MERCURY DAILY PRORATA REFUND OF DEFERMENT CHARGES
           IF SP-RBFRMLA(REB-SUB) = "V" OR "W"
              PERFORM REBATE-MERC-DAILY-PRORATA
           ELSE
           IF SP-RBFRMLA(REB-SUB) = "0"
      *************************************************
      *    SP-RBFRMLA2 FORMULAS   (SP-RBFRMLA ='0')
      *************************************************
      * MERCURY DAILY PRORATA REFUND 'AZ' (RP)
              IF SP-RBFRMLA2(REB-SUB) = "1"
                 PERFORM REBATE-MERC-TO-THE-DAY
              ELSE
      * MULLEN CA, CL NET PAYOFF BALBOA INSURANCE
              IF SP-RBFRMLA2(REB-SUB) = "2"
                 PERFORM REBATE-NET-POFF-MULL
              ELSE
      * MEAN RULE 78THS, REGACC #NA
              IF SP-RBFRMLA2(REB-SUB) = "3"
                 PERFORM RULE-78THS-MEAN
              ELSE
      * TN SHORT RATE, CONSUMERS #1062
              IF SP-RBFRMLA2(REB-SUB) = "4"
                 PERFORM TN-PP-SHORT-RATE
              ELSE
      * TN ACTUARIAL REFUND LIKE 'F' USING EQUIVALENT SIMPLE RATE
              IF SP-RBFRMLA2(REB-SUB) = "6"
                 PERFORM REBATE-ACTUARIAL-F-06
              ELSE
      * CA 'CL' TRUNCATED NET AND 'AH' 14 DAY NON RETRO PROTECTIVE LIFE
              IF SP-RBFRMLA2(REB-SUB) = "7"
                 PERFORM REBATE-MULLEN-CL-AH-07
              ELSE
      * WI CPI REFUND FORMULA
              IF SP-RBFRMLA2(REB-SUB) = "8"
                 PERFORM REBATE-WI-CPI
              ELSE
      * TX INTEREST REFUND FORMULA .....EXCEL
              IF SP-RBFRMLA2(REB-SUB) = "9"
                 PERFORM REBATE-TX-INTEREST
              ELSE
              IF SP-RBFRMLA2(REB-SUB) = "L"
                 PERFORM REBATE-TX-INT-UNITED
              ELSE
              IF SP-RBFRMLA2(REB-SUB) = "H"
                 PERFORM REBATE-TX-INT-0H
              ELSE
              IF SP-RBFRMLA2(REB-SUB) = "I"
                 PERFORM REBATE-TRIST-CPI-0I
              ELSE
      * MEAN OF PRORATE & RULE 78THS ...WORLD
              IF SP-RBFRMLA2(REB-SUB) = "A"
                 PERFORM REBATE-MEAN-OF-PRORATA-78
              ELSE
      * RULE 78THS FOR NET + 1 LIFE REFUND
              IF SP-RBFRMLA2(REB-SUB) = "B"
                 PERFORM REBATE-78-NET-1
              ELSE
      * CA COLLATERAL PROTECTION INSURANCE (SHORT RATE REBATE)
              IF SP-RBFRMLA2(REB-SUB) = "C" OR "K"
                 PERFORM REBATE-SHORT-RATE-0C
              ELSE
      * RULE 78THS USING DAYS IN TERM .........REGACC
              IF SP-RBFRMLA2(REB-SUB) = "D"
                 PERFORM REBATE-78-DAYS-0D
              ELSE
      * ACTUARIAL NET PAYOFF REBATE   .........WORLD
              IF SP-RBFRMLA2(REB-SUB) = "E"
                 PERFORM REBATE-ACTUARIAL-0E
              ELSE
      * TRUE DAILY PRORATE REBATE     .........WORLD
              IF SP-RBFRMLA2(REB-SUB) = "F"
                 PERFORM REBATE-TRUE-PRORATA-0F
              ELSE
      * MF REBATE SAME PROPORTION AS INT & SCHG  ....MEXICO WORLD
              IF SP-RBFRMLA2(REB-SUB) = "G"
                 PERFORM REBATE-SAME-PROP-INT-SC-0G
              ELSE
              IF SP-RBFRMLA2(REB-SUB) = "J"
                 PERFORM REBATE-MX-CL-ANTICIPATED
              ELSE
              IF SP-RBFRMLA2(REB-SUB) = "M"
                 PERFORM REBATE-INS-ANTICIPATED
              ELSE
              IF SP-RBFRMLA2(REB-SUB) = "N" OR "P"
                 PERFORM REBATE-ANTICIPATED-N-P
              ELSE
              IF SP-RBFRMLA2(REB-SUB) = "O"
                 PERFORM REBATE-ANTICIPATED-O.

       REBATE-END-ADJ.
           PERFORM REBATE-ADJUST-REB-REBATE.

       REBATE-EXIT.
           IF BR-FORCE-VALID-CITY-COUNTY = "Y"
      *      CREDIT LIFE SALES TAX:
              IF REB-SUB < 5
                 COMPUTE INS-TAX-RB ROUNDED =
                    LN-FEEAMT(5) * REB-REBATE / REB-TOTCHG
                 ADD INS-TAX-RB TO REB-REBATE
              ELSE
      *      A&H SALES TAX:
              IF REB-SUB = 5
                 COMPUTE INS-TAX-RB ROUNDED =
                    LN-FEEAMT(6) * REB-REBATE / REB-TOTCHG
                 ADD INS-TAX-RB TO REB-REBATE
              ELSE
      *      PP & PP2 SALES TAX:
              IF REB-SUB = 6 OR 11
                 COMPUTE INS-TAX-RB ROUNDED =
                    LN-FEEAMT(7) * REB-REBATE / REB-TOTCHG
                 ADD INS-TAX-RB TO REB-REBATE
              ELSE
      *      O1 OR O2 OR O3 OR O4 OR O5 SALES TAX:
              IF REB-SUB > 11 AND < 17
                 COMPUTE INS-TAX-RB ROUNDED =
                    LN-FEEAMT(REB-SUB - 4) * REB-REBATE / REB-TOTCHG
                 ADD INS-TAX-RB TO REB-REBATE.

           MOVE 0 TO REB-STATEWK.
           MOVE SPACES TO REB-SKIPDEF-FG
                          REB-ADDON-FG.


      *********************************
      *    RULE OF 78'S ROUTINE   (1)
      *********************************
