      *    IF ( SQL-CONNECT-STAT-BAD )
      *       PERFORM SQL-CONNECT.
      *-----------------------------------------------------------------
       START-SPA1-FILE.
           PERFORM START-IT.
           MOVE SPA-PATH-SQL TO E-FILE.
           MOVE SPA1-KEY TO E-KEYX.

           IF ( SPA1-CURSOR-STAT-GOOD )
              PERFORM CLOSE-SPA1-FILE.

           IF ( QSP1-WEND-LAWCODE = 0  ) OR
              ( QSP1-WEND-LAWCODE NOT NUMERIC)
              MOVE SPA-ORGST            TO QSP1-WBEG-ORGST 
              MOVE ALL "Z"              TO QSP1-WEND-ORGST 
              MOVE SPA-SPRCLASS         TO QSP1-WBEG-SPRCLASS
              MOVE ALL "9"              TO QSP1-WEND-SPRCLASS
              MOVE SPA-SUBCLASS         TO QSP1-WBEG-SUBCLASS
              MOVE ALL "9"              TO QSP1-WEND-SUBCLASS
              MOVE SPA-LAWCODE          TO QSP1-WBEG-LAWCODE
              MOVE ALL "9"              TO QSP1-WEND-LAWCODE.

           EXEC SQL
            DECLARE SPA1_CURSOR CURSOR FOR
            SELECT SPAFILE.SPA_ORGST,
                   SPAFILE.SPA_SPRCLASS,
                   SPAFILE.SPA_SUBCLASS,
                   SPAFILE.SPA_LAWCODE,
                   CAST(SPAFILE.SPA_LTOUCH_DATE
                                                  AS VARCHAR(10)),
                   SPAFILE.SPA_DESC,
                   SPAFILE.SPA_NOTES,
                   CAST(SPAFILE.SPA_EFFDATE
                                                  AS VARCHAR(10)),
                   CAST(SPAFILE.SPA_EXPDATE
                                                  AS VARCHAR(10)),
                   SPAFILE.SPA_EXPD_MONTHS,
                   SPAFILE.SPA_EXPD_DAYS,
                   SPAFILE.SPA_EXPD_FRMLA,
                   SPAFILE.SPA_EXPD_EXCEPT,
                   SPAFILE.SPA_EXPR_FRMLA,
                   SPAFILE.SPA_EXPR_REDU_FRMLA,
                   SPAFILE.SPA_EXPR_RATE_1,
                   SPAFILE.SPA_EXPR_BREAK_1,
                   SPAFILE.SPA_EXPR_YRTYPE_1,
                   SPAFILE.SPA_EXPR_INTMETH_1,
                   SPAFILE.SPA_EXPR_RATE_2,
                   SPAFILE.SPA_EXPR_BREAK_2,
                   SPAFILE.SPA_EXPR_YRTYPE_2,
                   SPAFILE.SPA_EXPR_INTMETH_2,
                   SPAFILE.SPA_EXPR_RATE_3,
                   SPAFILE.SPA_EXPR_BREAK_3,
                   SPAFILE.SPA_EXPR_YRTYPE_3,
                   SPAFILE.SPA_EXPR_INTMETH_3,
                   SPAFILE.SPA_EXPR_RATE_4,
                   SPAFILE.SPA_EXPR_BREAK_4,
                   SPAFILE.SPA_EXPR_YRTYPE_4,
                   SPAFILE.SPA_EXPR_INTMETH_4,
                   SPAFILE.SPA_EXPR_RATE_5,
                   SPAFILE.SPA_EXPR_BREAK_5,
                   SPAFILE.SPA_EXPR_YRTYPE_5,
                   SPAFILE.SPA_EXPR_INTMETH_5,
                   SPAFILE.SPA_EXPR_LCHG,
                   SPAFILE.SPA_JUDGFRMLA,
                   SPAFILE.SPA_JUDGRATE,
                   SPAFILE.SPA_JUDGYRTYPE,
                   SPAFILE.SPA_JUDGINTMETH,
                   SPAFILE.SPA_ACC_FRMLA,
                   SPAFILE.SPA_ACC_YRTYPE,
                   SPAFILE.SPA_ACC_INTMETH,
                   SPAFILE.SPA_ACC_RATE_1,
                   SPAFILE.SPA_ACC_BREAK_1,
                   SPAFILE.SPA_ACC_RATE_2,
                   SPAFILE.SPA_ACC_BREAK_2,
                   SPAFILE.SPA_ACC_RATE_3,
                   SPAFILE.SPA_ACC_BREAK_3,
                   SPAFILE.SPA_ACC_RATE_4,
                   SPAFILE.SPA_ACC_BREAK_4,
                   SPAFILE.SPA_ACC_RATE_5,
                   SPAFILE.SPA_ACC_BREAK_5,
                   SPAFILE.SPA_1098FRMLA,
                   SPAFILE.SPA_DISFRMLA,
                   SPAFILE.SPA_CONTRFRMLA,
                   SPAFILE.SPA_BANKRULE,
                   SPAFILE.SPA_CONTPDTH,
                   SPAFILE.SPA_FINCHG,
                   SPAFILE.SPA_BANKUNITPER_CD,
                   SPAFILE.SPA_TRWBANKRULE,
                   SPAFILE.SPA_TRWCONTPDTH,
                   SPAFILE.SPA_TRWBANKUNITPER_CD,
                   SPAFILE.SPA_RECFRMLA,
                   SPAFILE.SPA_RECPAYCD,
                   SPAFILE.SPA_RECPDTH,
                   SPAFILE.SPA_DISFRMLA_SPAY_FG,
                   SPAFILE.SPA_ERNFRMLA_1,
                   SPAFILE.SPA_ERNAMT_1,
                   SPAFILE.SPA_ERNPERCT_1,
                   SPAFILE.SPA_ERNPERCD_1,
                   SPAFILE.SPA_ERNACCRL_FG_1,
                   SPAFILE.SPA_ERNACCRL_START_CD_1,
                   SPAFILE.SPA_ERNACCRL_DFCD_1,
                   SPAFILE.SPA_ERN_DAYS_1,
                   SPAFILE.SPA_ERN_TERM_1,
                   SPAFILE.SPA_ERN_TYPE_1,
                   SPAFILE.SPA_ERNFRMLA_2,
                   SPAFILE.SPA_ERNAMT_2,
                   SPAFILE.SPA_ERNPERCT_2,
                   SPAFILE.SPA_ERNPERCD_2,
                   SPAFILE.SPA_ERNACCRL_FG_2,
                   SPAFILE.SPA_ERNACCRL_START_CD_2,
                   SPAFILE.SPA_ERNACCRL_DFCD_2,
                   SPAFILE.SPA_ERN_DAYS_2,
                   SPAFILE.SPA_ERN_TERM_2,
                   SPAFILE.SPA_ERN_TYPE_2,
                   SPAFILE.SPA_ERNFRMLA_3,
                   SPAFILE.SPA_ERNAMT_3,
                   SPAFILE.SPA_ERNPERCT_3,
                   SPAFILE.SPA_ERNPERCD_3,
                   SPAFILE.SPA_ERNACCRL_FG_3,
                   SPAFILE.SPA_ERNACCRL_START_CD_3,
                   SPAFILE.SPA_ERNACCRL_DFCD_3,
                   SPAFILE.SPA_ERN_DAYS_3,
                   SPAFILE.SPA_ERN_TERM_3,
                   SPAFILE.SPA_ERN_TYPE_3,
                   SPAFILE.SPA_ERNFRMLA_4,
                   SPAFILE.SPA_ERNAMT_4,
                   SPAFILE.SPA_ERNPERCT_4,
                   SPAFILE.SPA_ERNPERCD_4,
                   SPAFILE.SPA_ERNACCRL_FG_4,
                   SPAFILE.SPA_ERNACCRL_START_CD_4,
                   SPAFILE.SPA_ERNACCRL_DFCD_4,
                   SPAFILE.SPA_ERN_DAYS_4,
                   SPAFILE.SPA_ERN_TERM_4,
                   SPAFILE.SPA_ERN_TYPE_4,
                   SPAFILE.SPA_ERNFRMLA_5,
                   SPAFILE.SPA_ERNAMT_5,
                   SPAFILE.SPA_ERNPERCT_5,
                   SPAFILE.SPA_ERNPERCD_5,
                   SPAFILE.SPA_ERNACCRL_FG_5,
                   SPAFILE.SPA_ERNACCRL_START_CD_5,
                   SPAFILE.SPA_ERNACCRL_DFCD_5,
                   SPAFILE.SPA_ERN_DAYS_5,
                   SPAFILE.SPA_ERN_TERM_5,
                   SPAFILE.SPA_ERN_TYPE_5,
                   SPAFILE.SPA_ERNFRMLA_6,
                   SPAFILE.SPA_ERNAMT_6,
                   SPAFILE.SPA_ERNPERCT_6,
                   SPAFILE.SPA_ERNPERCD_6,
                   SPAFILE.SPA_ERNACCRL_FG_6,
                   SPAFILE.SPA_ERNACCRL_START_CD_6,
                   SPAFILE.SPA_ERNACCRL_DFCD_6,
                   SPAFILE.SPA_ERN_DAYS_6,
                   SPAFILE.SPA_ERN_TERM_6,
                   SPAFILE.SPA_ERN_TYPE_6,
                   SPAFILE.SPA_ERNFRMLA_7,
                   SPAFILE.SPA_ERNAMT_7,
                   SPAFILE.SPA_ERNPERCT_7,
                   SPAFILE.SPA_ERNPERCD_7,
                   SPAFILE.SPA_ERNACCRL_FG_7,
                   SPAFILE.SPA_ERNACCRL_START_CD_7,
                   SPAFILE.SPA_ERNACCRL_DFCD_7,
                   SPAFILE.SPA_ERN_DAYS_7,
                   SPAFILE.SPA_ERN_TERM_7,
                   SPAFILE.SPA_ERN_TYPE_7,
                   SPAFILE.SPA_ERNFRMLA_8,
                   SPAFILE.SPA_ERNAMT_8,
                   SPAFILE.SPA_ERNPERCT_8,
                   SPAFILE.SPA_ERNPERCD_8,
                   SPAFILE.SPA_ERNACCRL_FG_8,
                   SPAFILE.SPA_ERNACCRL_START_CD_8,
                   SPAFILE.SPA_ERNACCRL_DFCD_8,
                   SPAFILE.SPA_ERN_DAYS_8,
                   SPAFILE.SPA_ERN_TERM_8,
                   SPAFILE.SPA_ERN_TYPE_8,
                   SPAFILE.SPA_ERNFRMLA_9,
                   SPAFILE.SPA_ERNAMT_9,
                   SPAFILE.SPA_ERNPERCT_9,
                   SPAFILE.SPA_ERNPERCD_9,
                   SPAFILE.SPA_ERNACCRL_FG_9,
                   SPAFILE.SPA_ERNACCRL_START_CD_9,
                   SPAFILE.SPA_ERNACCRL_DFCD_9,
                   SPAFILE.SPA_ERN_DAYS_9,
                   SPAFILE.SPA_ERN_TERM_9,
                   SPAFILE.SPA_ERN_TYPE_9,
                   SPAFILE.SPA_ERNFRMLA_10,
                   SPAFILE.SPA_ERNAMT_10,
                   SPAFILE.SPA_ERNPERCT_10,
                   SPAFILE.SPA_ERNPERCD_10,
                   SPAFILE.SPA_ERNACCRL_FG_10,
                   SPAFILE.SPA_ERNACCRL_START_CD_10,
                   SPAFILE.SPA_ERNACCRL_DFCD_10,
                   SPAFILE.SPA_ERN_DAYS_10,
                   SPAFILE.SPA_ERN_TERM_10,
                   SPAFILE.SPA_ERN_TYPE_10,
                   SPAFILE.SPA_ERNACCEL_CD,
                   SPAFILE.SPA_ERNJD_CD,
                   SPAFILE.SPA_MIDSTRERNCD,
                   SPAFILE.SPA_EARN_ORDER_1,
                   SPAFILE.SPA_EARN_ORDER_2,
                   SPAFILE.SPA_EARN_ORDER_3,
                   SPAFILE.SPA_EARN_ORDER_4,
                   SPAFILE.SPA_EARN_ORDER_5,
                   SPAFILE.SPA_EARN_ORDER_6,
                   SPAFILE.SPA_EARN_ORDER_7,
                   SPAFILE.SPA_EARN_ORDER_8,
                   SPAFILE.SPA_EARN_ORDER_9,
                   SPAFILE.SPA_EARN_ORDER_10,
                   SPAFILE.SPA_ERNDELQFRMLA,
                   SPAFILE.SPA_ERNDELQ_START,
                   SPAFILE.SPA_ERNDELQ_STOP,
                   SPAFILE.SPA_1098_INC_LC,
                   SPAFILE.SPA_MAX_IB_ACR_DAYS,
                   SPAFILE.SPA_LCGRACE,
                   SPAFILE.SPA_LCGRACECD,
                   SPAFILE.SPA_LCTYPE,
                   SPAFILE.SPA_LCRATE,
                   SPAFILE.SPA_LCFRMLA,
                   SPAFILE.SPA_LCMINCHG,
                   SPAFILE.SPA_LCMAXAMT,
                   SPAFILE.SPA_LCDELFAC,
                   SPAFILE.SPA_LCYRTYPE,
                   SPAFILE.SPA_LC_CODE,
                   SPAFILE.SPA_LCUNITPER_CD,
                   SPAFILE.SPA_DEFFRMLA,
                   SPAFILE.SPA_DEFEXCEPT,
                   SPAFILE.SPA_DEFWORKER,
                   SPAFILE.SPA_DEFPERCD,
                   SPAFILE.SPA_DEFBASE,
                   SPAFILE.SPA_DEFPOLCD,
                   SPAFILE.SPA_DEFPOLMX_1,
                   SPAFILE.SPA_DEFPOLMX_2,
                   SPAFILE.SPA_DEFPOLMX_3,
                   SPAFILE.SPA_DEFMIN,
                   SPAFILE.SPA_DEFMAX,
                   SPAFILE.SPA_DEFUNITPER_CD,
                   SPAFILE.SPA_PRFORM_1,
                   SPAFILE.SPA_PRFLAG_1,
                   SPAFILE.SPA_PRFORM_2,
                   SPAFILE.SPA_PRFLAG_2,
                   SPAFILE.SPA_PRFORM_3,
                   SPAFILE.SPA_PRFLAG_3,
                   SPAFILE.SPA_PRFORM_4,
                   SPAFILE.SPA_PRFLAG_4,
                   SPAFILE.SPA_PRFORM_5,
                   SPAFILE.SPA_PRFLAG_5,
                   SPAFILE.SPA_PRFORM_6,
                   SPAFILE.SPA_PRFLAG_6,
                   SPAFILE.SPA_PRFORM_7,
                   SPAFILE.SPA_PRFLAG_7,
                   SPAFILE.SPA_PRFORM_8,
                   SPAFILE.SPA_PRFLAG_8,
                   SPAFILE.SPA_PRFORM_9,
                   SPAFILE.SPA_PRFLAG_9,
                   SPAFILE.SPA_PRFORM_10,
                   SPAFILE.SPA_PRFLAG_10,
                   SPAFILE.SPA_PRFORM_11,
                   SPAFILE.SPA_PRFLAG_11,
                   SPAFILE.SPA_PRFORM_12,
                   SPAFILE.SPA_PRFLAG_12,
                   SPAFILE.SPA_PRFORM_13,
                   SPAFILE.SPA_PRFLAG_13,
                   SPAFILE.SPA_PRFORM_14,
                   SPAFILE.SPA_PRFLAG_14,
                   SPAFILE.SPA_PRFORM_15,
                   SPAFILE.SPA_PRFLAG_15,
                   SPAFILE.SPA_PRFORM_16,
                   SPAFILE.SPA_PRFLAG_16,
                   SPAFILE.SPA_PRFORM_17,
                   SPAFILE.SPA_PRFLAG_17,
                   SPAFILE.SPA_PRFORM_18,
                   SPAFILE.SPA_PRFLAG_18,
                   SPAFILE.SPA_PRFORM_19,
                   SPAFILE.SPA_PRFLAG_19,
                   SPAFILE.SPA_PRFORM_20,
                   SPAFILE.SPA_PRFLAG_20,
                   SPAFILE.SPA_IMED_REC,
                   SPAFILE.SPA_SCFRMLA,
                   SPAFILE.SPA_SCRATE,
                   SPAFILE.SPA_SCMIN,
                   SPAFILE.SPA_SCMAX,
                   SPAFILE.SPA_MFFRMLA,
                   SPAFILE.SPA_MFRATE,
                   SPAFILE.SPA_MFMIN,
                   SPAFILE.SPA_MFMAX,
                   SPAFILE.SPA_INTMETHOD,
                   SPAFILE.SPA_YEARTYPE,
                   SPAFILE.SPA_PYEXFRMLA,
                   SPAFILE.SPA_PYEXSPCODE,
                   SPAFILE.SPA_PYEXYEARTP,
                   SPAFILE.SPA_PYEXFMDATE,
                   SPAFILE.SPA_PYEXBASECD,
                   SPAFILE.SPA_PYEXBASE,
                   SPAFILE.SPA_PYEXDAYS,
                   SPAFILE.SPA_CAL_SPFRMLA,
                   SPAFILE.SPA_CAL_RATETYPE_1,
                   SPAFILE.SPA_CAL_BREAKTYPE_1,
                   SPAFILE.SPA_CAL_CHGABLE_1,
                   SPAFILE.SPA_CAL_NORATES_1,
                   SPAFILE.SPA_CAL_TBFRMLA_1,
                   SPAFILE.SPA_CAL_RATE_1_1,
                   SPAFILE.SPA_CAL_BREAK_1_1,
                   SPAFILE.SPA_CAL_RATE_1_2,
                   SPAFILE.SPA_CAL_BREAK_1_2,
                   SPAFILE.SPA_CAL_RATE_1_3,
                   SPAFILE.SPA_CAL_BREAK_1_3,
                   SPAFILE.SPA_CAL_RATE_1_4,
                   SPAFILE.SPA_CAL_BREAK_1_4,
                   SPAFILE.SPA_CAL_RATE_1_5,
                   SPAFILE.SPA_CAL_BREAK_1_5,
                   SPAFILE.SPA_CAL_RATETYPE_2,
                   SPAFILE.SPA_CAL_BREAKTYPE_2,
                   SPAFILE.SPA_CAL_CHGABLE_2,
                   SPAFILE.SPA_CAL_NORATES_2,
                   SPAFILE.SPA_CAL_TBFRMLA_2,
                   SPAFILE.SPA_CAL_RATE_2_1,
                   SPAFILE.SPA_CAL_BREAK_2_1,
                   SPAFILE.SPA_CAL_RATE_2_2,
                   SPAFILE.SPA_CAL_BREAK_2_2,
                   SPAFILE.SPA_CAL_RATE_2_3,
                   SPAFILE.SPA_CAL_BREAK_2_3,
                   SPAFILE.SPA_CAL_RATE_2_4,
                   SPAFILE.SPA_CAL_BREAK_2_4,
                   SPAFILE.SPA_CAL_RATE_2_5,
                   SPAFILE.SPA_CAL_BREAK_2_5,
                   SPAFILE.SPA_MINSF_FRMLA,
                   SPAFILE.SPA_MINSF_CHG,
                   SPAFILE.SPA_MAXAPR_FRMLA,
                   SPAFILE.SPA_EDT_NOEDITS_1,
                   SPAFILE.SPA_EDT_TYPE_1_1,
                   SPAFILE.SPA_EDT_HL_1_1,
                   SPAFILE.SPA_EDT_COLL_1_1,
                   SPAFILE.SPA_EDT_CD_1_1,
                   SPAFILE.SPA_EDT_RATE_1_1,
                   SPAFILE.SPA_EDT_RATETYPE_1_1,
                   SPAFILE.SPA_EDT_AMT_1_1,
                   SPAFILE.SPA_EDT_AMTYPE_1_1,
                   SPAFILE.SPA_EDT_TERM_1_1,
                   SPAFILE.SPA_EDT_TYPE_1_2,
                   SPAFILE.SPA_EDT_HL_1_2,
                   SPAFILE.SPA_EDT_COLL_1_2,
                   SPAFILE.SPA_EDT_CD_1_2,
                   SPAFILE.SPA_EDT_RATE_1_2,
                   SPAFILE.SPA_EDT_RATETYPE_1_2,
                   SPAFILE.SPA_EDT_AMT_1_2,
                   SPAFILE.SPA_EDT_AMTYPE_1_2,
                   SPAFILE.SPA_EDT_TERM_1_2,
                   SPAFILE.SPA_EDT_TYPE_1_3,
                   SPAFILE.SPA_EDT_HL_1_3,
                   SPAFILE.SPA_EDT_COLL_1_3,
                   SPAFILE.SPA_EDT_CD_1_3,
                   SPAFILE.SPA_EDT_RATE_1_3,
                   SPAFILE.SPA_EDT_RATETYPE_1_3,
                   SPAFILE.SPA_EDT_AMT_1_3,
                   SPAFILE.SPA_EDT_AMTYPE_1_3,
                   SPAFILE.SPA_EDT_TERM_1_3,
                   SPAFILE.SPA_EDT_TYPE_1_4,
                   SPAFILE.SPA_EDT_HL_1_4,
                   SPAFILE.SPA_EDT_COLL_1_4,
                   SPAFILE.SPA_EDT_CD_1_4,
                   SPAFILE.SPA_EDT_RATE_1_4,
                   SPAFILE.SPA_EDT_RATETYPE_1_4,
                   SPAFILE.SPA_EDT_AMT_1_4,
                   SPAFILE.SPA_EDT_AMTYPE_1_4,
                   SPAFILE.SPA_EDT_TERM_1_4,
                   SPAFILE.SPA_EDT_TYPE_1_5,
                   SPAFILE.SPA_EDT_HL_1_5,
                   SPAFILE.SPA_EDT_COLL_1_5,
                   SPAFILE.SPA_EDT_CD_1_5,
                   SPAFILE.SPA_EDT_RATE_1_5,
                   SPAFILE.SPA_EDT_RATETYPE_1_5,
                   SPAFILE.SPA_EDT_AMT_1_5,
                   SPAFILE.SPA_EDT_AMTYPE_1_5,
                   SPAFILE.SPA_EDT_TERM_1_5,
                   SPAFILE.SPA_EDT_TYPE_1_6,
                   SPAFILE.SPA_EDT_HL_1_6,
                   SPAFILE.SPA_EDT_COLL_1_6,
                   SPAFILE.SPA_EDT_CD_1_6,
                   SPAFILE.SPA_EDT_RATE_1_6,
                   SPAFILE.SPA_EDT_RATETYPE_1_6,
                   SPAFILE.SPA_EDT_AMT_1_6,
                   SPAFILE.SPA_EDT_AMTYPE_1_6,
                   SPAFILE.SPA_EDT_TERM_1_6,
                   SPAFILE.SPA_EDT_NOEDITS_2,
                   SPAFILE.SPA_EDT_TYPE_2_1,
                   SPAFILE.SPA_EDT_HL_2_1,
                   SPAFILE.SPA_EDT_COLL_2_1,
                   SPAFILE.SPA_EDT_CD_2_1,
                   SPAFILE.SPA_EDT_RATE_2_1,
                   SPAFILE.SPA_EDT_RATETYPE_2_1,
                   SPAFILE.SPA_EDT_AMT_2_1,
                   SPAFILE.SPA_EDT_AMTYPE_2_1,
                   SPAFILE.SPA_EDT_TERM_2_1,
                   SPAFILE.SPA_EDT_TYPE_2_2,
                   SPAFILE.SPA_EDT_HL_2_2,
                   SPAFILE.SPA_EDT_COLL_2_2,
                   SPAFILE.SPA_EDT_CD_2_2,
                   SPAFILE.SPA_EDT_RATE_2_2,
                   SPAFILE.SPA_EDT_RATETYPE_2_2,
                   SPAFILE.SPA_EDT_AMT_2_2,
                   SPAFILE.SPA_EDT_AMTYPE_2_2,
                   SPAFILE.SPA_EDT_TERM_2_2,
                   SPAFILE.SPA_EDT_TYPE_2_3,
                   SPAFILE.SPA_EDT_HL_2_3,
                   SPAFILE.SPA_EDT_COLL_2_3,
                   SPAFILE.SPA_EDT_CD_2_3,
                   SPAFILE.SPA_EDT_RATE_2_3,
                   SPAFILE.SPA_EDT_RATETYPE_2_3,
                   SPAFILE.SPA_EDT_AMT_2_3,
                   SPAFILE.SPA_EDT_AMTYPE_2_3,
                   SPAFILE.SPA_EDT_TERM_2_3,
                   SPAFILE.SPA_EDT_TYPE_2_4,
                   SPAFILE.SPA_EDT_HL_2_4,
                   SPAFILE.SPA_EDT_COLL_2_4,
                   SPAFILE.SPA_EDT_CD_2_4,
                   SPAFILE.SPA_EDT_RATE_2_4,
                   SPAFILE.SPA_EDT_RATETYPE_2_4,
                   SPAFILE.SPA_EDT_AMT_2_4,
                   SPAFILE.SPA_EDT_AMTYPE_2_4,
                   SPAFILE.SPA_EDT_TERM_2_4,
                   SPAFILE.SPA_EDT_TYPE_2_5,
                   SPAFILE.SPA_EDT_HL_2_5,
                   SPAFILE.SPA_EDT_COLL_2_5,
                   SPAFILE.SPA_EDT_CD_2_5,
                   SPAFILE.SPA_EDT_RATE_2_5,
                   SPAFILE.SPA_EDT_RATETYPE_2_5,
                   SPAFILE.SPA_EDT_AMT_2_5,
                   SPAFILE.SPA_EDT_AMTYPE_2_5,
                   SPAFILE.SPA_EDT_TERM_2_5,
                   SPAFILE.SPA_EDT_TYPE_2_6,
                   SPAFILE.SPA_EDT_HL_2_6,
                   SPAFILE.SPA_EDT_COLL_2_6,
                   SPAFILE.SPA_EDT_CD_2_6,
                   SPAFILE.SPA_EDT_RATE_2_6,
                   SPAFILE.SPA_EDT_RATETYPE_2_6,
                   SPAFILE.SPA_EDT_AMT_2_6,
                   SPAFILE.SPA_EDT_AMTYPE_2_6,
                   SPAFILE.SPA_EDT_TERM_2_6
            FROM DBO.SPAFILE
            WHERE SPAFILE.SPA_ORGST >= :QSP1-WBEG-ORGST
              AND SPAFILE.SPA_ORGST <= :QSP1-WEND-ORGST
              AND SPAFILE.SPA_SPRCLASS >= :QSP1-WBEG-SPRCLASS
              AND SPAFILE.SPA_SPRCLASS <= :QSP1-WEND-SPRCLASS
              AND SPAFILE.SPA_SUBCLASS >= :QSP1-WBEG-SUBCLASS
              AND SPAFILE.SPA_SUBCLASS <= :QSP1-WEND-SUBCLASS
              AND SPAFILE.SPA_LAWCODE >= :QSP1-WBEG-LAWCODE 
              AND SPAFILE.SPA_LAWCODE <= :QSP1-WEND-LAWCODE 
            ORDER BY SPAFILE.SPA_ORGST,
                     SPAFILE.SPA_SPRCLASS,
                     SPAFILE.SPA_SUBCLASS,
                     SPAFILE.SPA_LAWCODE
           END-EXEC.

           EXEC SQL
               OPEN SPA1_CURSOR
           END-EXEC.

           PERFORM SQL-IO-VALIDATION.

           MOVE SPACES TO QSP1-WBEG-ORGST
                          QSP1-WEND-ORGST.

           MOVE ZEROES TO QSP1-WBEG-SPRCLASS
                          QSP1-WEND-SPRCLASS
                          QSP1-WBEG-SUBCLASS
                          QSP1-WEND-SUBCLASS
                          QSP1-WBEG-LAWCODE
                          QSP1-WEND-LAWCODE.

           MOVE STAT---GOOD TO SPA1-CURSOR-STAT.

      *-----------------------------------------------------------------
